// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bladewatch/v1/auth.proto
// Protobuf Java Version: 4.35.0

package net.bladewatch.app.grpc.v1;

@com.google.protobuf.Generated
public final class Auth extends com.google.protobuf.GeneratedFile {
  private Auth() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 0,
      /* suffix= */ "",
      "Auth");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_InvalidateAuthCacheRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_InvalidateAuthCacheRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_InvalidateAuthCacheResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_InvalidateAuthCacheResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030bladewatch/v1/auth.proto\022\rbladewatch.v" +
      "1\"\034\n\032InvalidateAuthCacheRequest\"7\n\033Inval" +
      "idateAuthCacheResponse\022\030\n\007success\030\001 \001(\010R" +
      "\007success2{\n\013AuthService\022l\n\023InvalidateAut" +
      "hCache\022).bladewatch.v1.InvalidateAuthCac" +
      "heRequest\032*.bladewatch.v1.InvalidateAuth" +
      "CacheResponseB\036\n\032net.bladewatch.app.grpc" +
      ".v1P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_bladewatch_v1_InvalidateAuthCacheRequest_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_bladewatch_v1_InvalidateAuthCacheRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_InvalidateAuthCacheRequest_descriptor,
        new java.lang.String[] { });
    internal_static_bladewatch_v1_InvalidateAuthCacheResponse_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_bladewatch_v1_InvalidateAuthCacheResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_InvalidateAuthCacheResponse_descriptor,
        new java.lang.String[] { "Success", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
