// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bladewatch/v1/vehicle.proto
// Protobuf Java Version: 4.35.0

package net.bladewatch.app.grpc.v1;

@com.google.protobuf.Generated
public interface BatteryStatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bladewatch.v1.BatteryStatus)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double soc = 1 [json_name = "soc"];</code>
   * @return The soc.
   */
  double getSoc();

  /**
   * <code>int32 range_km = 2 [json_name = "rangeKm"];</code>
   * @return The rangeKm.
   */
  int getRangeKm();

  /**
   * <code>int32 bodywork_range_km = 3 [json_name = "bodyworkRangeKm"];</code>
   * @return The bodyworkRangeKm.
   */
  int getBodyworkRangeKm();

  /**
   * <pre>
   * PHEV fuel leg. Both are OMITTED on a BEV rather than sent as 0: the
   * collector leaves fuel_percent NaN and fuel_range_km UNAVAILABLE there, and
   * a zero would render as a real "0%" / "0 km" readout on a car that has no
   * tank. Clients therefore treat "absent" as "not a fuel vehicle", which is
   * also how they decide whether to show the fuel readout at all -- there is no
   * separate is_phev flag on this message.
   * </pre>
   *
   * <code>double fuel_percent = 4 [json_name = "fuelPercent"];</code>
   * @return The fuelPercent.
   */
  double getFuelPercent();

  /**
   * <code>int32 fuel_range_km = 5 [json_name = "fuelRangeKm"];</code>
   * @return The fuelRangeKm.
   */
  int getFuelRangeKm();
}
