// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bladewatch/v1/vehicle.proto
// Protobuf Java Version: 4.35.0

package net.bladewatch.app.grpc.v1;

@com.google.protobuf.Generated
public interface ClimateStatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bladewatch.v1.ClimateStatus)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool ac_on = 1 [json_name = "acOn"];</code>
   * @return The acOn.
   */
  boolean getAcOn();

  /**
   * <code>double setpoint_c = 2 [json_name = "setpointC"];</code>
   * @return The setpointC.
   */
  double getSetpointC();

  /**
   * <code>int32 wind_mode = 4 [json_name = "windMode"];</code>
   * @return The windMode.
   */
  int getWindMode();

  /**
   * <code>int32 fan_level = 5 [json_name = "fanLevel"];</code>
   * @return The fanLevel.
   */
  int getFanLevel();

  /**
   * <code>bool max_cooling = 6 [json_name = "maxCooling"];</code>
   * @return The maxCooling.
   */
  boolean getMaxCooling();

  /**
   * <pre>
   * Outside air, BYDAutoInstrumentDevice.getOutCarTemperature(). Absent when unavailable --
   * optional, because 0 C is a real outside temperature.
   * </pre>
   *
   * <code>optional double outside_temp_c = 7 [json_name = "outsideTempC"];</code>
   * @return Whether the outsideTempC field is set.
   */
  boolean hasOutsideTempC();
  /**
   * <pre>
   * Outside air, BYDAutoInstrumentDevice.getOutCarTemperature(). Absent when unavailable --
   * optional, because 0 C is a real outside temperature.
   * </pre>
   *
   * <code>optional double outside_temp_c = 7 [json_name = "outsideTempC"];</code>
   * @return The outsideTempC.
   */
  double getOutsideTempC();
}
