// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bladewatch/v1/system.proto
// Protobuf Java Version: 4.35.0

package net.bladewatch.app.grpc.v1;

/**
 * <pre>
 * DriveStatus: labels only where measured on a head unit, "UNKNOWN" otherwise; the raw SDK values
 * (-1 when unavailable) always, so an unmeasured one can be mapped from a status query alone.
 * </pre>
 *
 * Protobuf type {@code bladewatch.v1.DriveStatus}
 */
@com.google.protobuf.Generated
public final class DriveStatus extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:bladewatch.v1.DriveStatus)
    DriveStatusOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 0,
      /* suffix= */ "",
      "DriveStatus");
  }
  // Use DriveStatus.newBuilder() to construct.
  private DriveStatus(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private DriveStatus() {
    gear_ = "";
    driveMode_ = "";
    autoHold_ = "";
    energyMode_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return net.bladewatch.app.grpc.v1.System.internal_static_bladewatch_v1_DriveStatus_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return net.bladewatch.app.grpc.v1.System.internal_static_bladewatch_v1_DriveStatus_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return net.bladewatch.app.grpc.v1.System.internal_static_bladewatch_v1_DriveStatus_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            net.bladewatch.app.grpc.v1.DriveStatus.class, net.bladewatch.app.grpc.v1.DriveStatus.Builder.class);
  }

  public static final int GEAR_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object gear_ = "";
  /**
   * <pre>
   * "P" / "R" / "N" / "D" / "M" / "S", or "UNKNOWN".
   * </pre>
   *
   * <code>string gear = 1 [json_name = "gear"];</code>
   * @return The gear.
   */
  @java.lang.Override
  public java.lang.String getGear() {
    java.lang.Object ref = gear_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      gear_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * "P" / "R" / "N" / "D" / "M" / "S", or "UNKNOWN".
   * </pre>
   *
   * <code>string gear = 1 [json_name = "gear"];</code>
   * @return The bytes for gear.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getGearBytes() {
    java.lang.Object ref = gear_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      gear_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DRIVE_MODE_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object driveMode_ = "";
  /**
   * <pre>
   * "ECO/NORMAL" (the car reads one value for both) / "SPORT", or "UNKNOWN".
   * </pre>
   *
   * <code>string drive_mode = 2 [json_name = "driveMode"];</code>
   * @return The driveMode.
   */
  @java.lang.Override
  public java.lang.String getDriveMode() {
    java.lang.Object ref = driveMode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      driveMode_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * "ECO/NORMAL" (the car reads one value for both) / "SPORT", or "UNKNOWN".
   * </pre>
   *
   * <code>string drive_mode = 2 [json_name = "driveMode"];</code>
   * @return The bytes for driveMode.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDriveModeBytes() {
    java.lang.Object ref = driveMode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      driveMode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DRIVE_MODE_RAW_FIELD_NUMBER = 3;
  private int driveModeRaw_ = 0;
  /**
   * <pre>
   * BYDAutoEnergyDevice.getOperationMode().
   * </pre>
   *
   * <code>int32 drive_mode_raw = 3 [json_name = "driveModeRaw"];</code>
   * @return The driveModeRaw.
   */
  @java.lang.Override
  public int getDriveModeRaw() {
    return driveModeRaw_;
  }

  public static final int AUTO_HOLD_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object autoHold_ = "";
  /**
   * <pre>
   * "DISABLED" / "ENABLED" / "ACTIVE", or "UNKNOWN".
   * </pre>
   *
   * <code>string auto_hold = 4 [json_name = "autoHold"];</code>
   * @return The autoHold.
   */
  @java.lang.Override
  public java.lang.String getAutoHold() {
    java.lang.Object ref = autoHold_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      autoHold_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * "DISABLED" / "ENABLED" / "ACTIVE", or "UNKNOWN".
   * </pre>
   *
   * <code>string auto_hold = 4 [json_name = "autoHold"];</code>
   * @return The bytes for autoHold.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAutoHoldBytes() {
    java.lang.Object ref = autoHold_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      autoHold_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AUTO_HOLD_RAW_FIELD_NUMBER = 5;
  private int autoHoldRaw_ = 0;
  /**
   * <pre>
   * BYDAutoADASDevice.getAVHState().
   * </pre>
   *
   * <code>int32 auto_hold_raw = 5 [json_name = "autoHoldRaw"];</code>
   * @return The autoHoldRaw.
   */
  @java.lang.Override
  public int getAutoHoldRaw() {
    return autoHoldRaw_;
  }

  public static final int ENERGY_MODE_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object energyMode_ = "";
  /**
   * <pre>
   * "EV" / "HEV", or "UNKNOWN".
   * </pre>
   *
   * <code>string energy_mode = 6 [json_name = "energyMode"];</code>
   * @return The energyMode.
   */
  @java.lang.Override
  public java.lang.String getEnergyMode() {
    java.lang.Object ref = energyMode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      energyMode_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * "EV" / "HEV", or "UNKNOWN".
   * </pre>
   *
   * <code>string energy_mode = 6 [json_name = "energyMode"];</code>
   * @return The bytes for energyMode.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEnergyModeBytes() {
    java.lang.Object ref = energyMode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      energyMode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ENERGY_MODE_RAW_FIELD_NUMBER = 7;
  private int energyModeRaw_ = 0;
  /**
   * <pre>
   * BYDAutoEnergyDevice.getEnergyMode().
   * </pre>
   *
   * <code>int32 energy_mode_raw = 7 [json_name = "energyModeRaw"];</code>
   * @return The energyModeRaw.
   */
  @java.lang.Override
  public int getEnergyModeRaw() {
    return energyModeRaw_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(gear_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, gear_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(driveMode_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, driveMode_);
    }
    if (driveModeRaw_ != 0) {
      output.writeInt32(3, driveModeRaw_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(autoHold_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, autoHold_);
    }
    if (autoHoldRaw_ != 0) {
      output.writeInt32(5, autoHoldRaw_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(energyMode_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 6, energyMode_);
    }
    if (energyModeRaw_ != 0) {
      output.writeInt32(7, energyModeRaw_);
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(gear_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, gear_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(driveMode_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, driveMode_);
    }
    if (driveModeRaw_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, driveModeRaw_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(autoHold_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, autoHold_);
    }
    if (autoHoldRaw_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, autoHoldRaw_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(energyMode_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(6, energyMode_);
    }
    if (energyModeRaw_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(7, energyModeRaw_);
    }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof net.bladewatch.app.grpc.v1.DriveStatus)) {
      return super.equals(obj);
    }
    net.bladewatch.app.grpc.v1.DriveStatus other = (net.bladewatch.app.grpc.v1.DriveStatus) obj;

    if (!getGear()
        .equals(other.getGear())) return false;
    if (!getDriveMode()
        .equals(other.getDriveMode())) return false;
    if (getDriveModeRaw()
        != other.getDriveModeRaw()) return false;
    if (!getAutoHold()
        .equals(other.getAutoHold())) return false;
    if (getAutoHoldRaw()
        != other.getAutoHoldRaw()) return false;
    if (!getEnergyMode()
        .equals(other.getEnergyMode())) return false;
    if (getEnergyModeRaw()
        != other.getEnergyModeRaw()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + GEAR_FIELD_NUMBER;
    hash = (53 * hash) + getGear().hashCode();
    hash = (37 * hash) + DRIVE_MODE_FIELD_NUMBER;
    hash = (53 * hash) + getDriveMode().hashCode();
    hash = (37 * hash) + DRIVE_MODE_RAW_FIELD_NUMBER;
    hash = (53 * hash) + getDriveModeRaw();
    hash = (37 * hash) + AUTO_HOLD_FIELD_NUMBER;
    hash = (53 * hash) + getAutoHold().hashCode();
    hash = (37 * hash) + AUTO_HOLD_RAW_FIELD_NUMBER;
    hash = (53 * hash) + getAutoHoldRaw();
    hash = (37 * hash) + ENERGY_MODE_FIELD_NUMBER;
    hash = (53 * hash) + getEnergyMode().hashCode();
    hash = (37 * hash) + ENERGY_MODE_RAW_FIELD_NUMBER;
    hash = (53 * hash) + getEnergyModeRaw();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static net.bladewatch.app.grpc.v1.DriveStatus parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.bladewatch.app.grpc.v1.DriveStatus parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.bladewatch.app.grpc.v1.DriveStatus parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.bladewatch.app.grpc.v1.DriveStatus parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.bladewatch.app.grpc.v1.DriveStatus parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.bladewatch.app.grpc.v1.DriveStatus parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.bladewatch.app.grpc.v1.DriveStatus parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static net.bladewatch.app.grpc.v1.DriveStatus parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static net.bladewatch.app.grpc.v1.DriveStatus parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static net.bladewatch.app.grpc.v1.DriveStatus parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static net.bladewatch.app.grpc.v1.DriveStatus parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static net.bladewatch.app.grpc.v1.DriveStatus parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(net.bladewatch.app.grpc.v1.DriveStatus prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * DriveStatus: labels only where measured on a head unit, "UNKNOWN" otherwise; the raw SDK values
   * (-1 when unavailable) always, so an unmeasured one can be mapped from a status query alone.
   * </pre>
   *
   * Protobuf type {@code bladewatch.v1.DriveStatus}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:bladewatch.v1.DriveStatus)
      net.bladewatch.app.grpc.v1.DriveStatusOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.bladewatch.app.grpc.v1.System.internal_static_bladewatch_v1_DriveStatus_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.bladewatch.app.grpc.v1.System.internal_static_bladewatch_v1_DriveStatus_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.bladewatch.app.grpc.v1.DriveStatus.class, net.bladewatch.app.grpc.v1.DriveStatus.Builder.class);
    }

    // Construct using net.bladewatch.app.grpc.v1.DriveStatus.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      gear_ = "";
      driveMode_ = "";
      driveModeRaw_ = 0;
      autoHold_ = "";
      autoHoldRaw_ = 0;
      energyMode_ = "";
      energyModeRaw_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return net.bladewatch.app.grpc.v1.System.internal_static_bladewatch_v1_DriveStatus_descriptor;
    }

    @java.lang.Override
    public net.bladewatch.app.grpc.v1.DriveStatus getDefaultInstanceForType() {
      return net.bladewatch.app.grpc.v1.DriveStatus.getDefaultInstance();
    }

    @java.lang.Override
    public net.bladewatch.app.grpc.v1.DriveStatus build() {
      net.bladewatch.app.grpc.v1.DriveStatus result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public net.bladewatch.app.grpc.v1.DriveStatus buildPartial() {
      net.bladewatch.app.grpc.v1.DriveStatus result = new net.bladewatch.app.grpc.v1.DriveStatus(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(net.bladewatch.app.grpc.v1.DriveStatus result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.gear_ = gear_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.driveMode_ = driveMode_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.driveModeRaw_ = driveModeRaw_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.autoHold_ = autoHold_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.autoHoldRaw_ = autoHoldRaw_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.energyMode_ = energyMode_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.energyModeRaw_ = energyModeRaw_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof net.bladewatch.app.grpc.v1.DriveStatus) {
        return mergeFrom((net.bladewatch.app.grpc.v1.DriveStatus)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(net.bladewatch.app.grpc.v1.DriveStatus other) {
      if (other == net.bladewatch.app.grpc.v1.DriveStatus.getDefaultInstance()) return this;
      if (!other.getGear().isEmpty()) {
        gear_ = other.gear_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getDriveMode().isEmpty()) {
        driveMode_ = other.driveMode_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.getDriveModeRaw() != 0) {
        setDriveModeRaw(other.getDriveModeRaw());
      }
      if (!other.getAutoHold().isEmpty()) {
        autoHold_ = other.autoHold_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (other.getAutoHoldRaw() != 0) {
        setAutoHoldRaw(other.getAutoHoldRaw());
      }
      if (!other.getEnergyMode().isEmpty()) {
        energyMode_ = other.energyMode_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      if (other.getEnergyModeRaw() != 0) {
        setEnergyModeRaw(other.getEnergyModeRaw());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              gear_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              driveMode_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              driveModeRaw_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 34: {
              autoHold_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 40: {
              autoHoldRaw_ = input.readInt32();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 50: {
              energyMode_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 56: {
              energyModeRaw_ = input.readInt32();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object gear_ = "";
    /**
     * <pre>
     * "P" / "R" / "N" / "D" / "M" / "S", or "UNKNOWN".
     * </pre>
     *
     * <code>string gear = 1 [json_name = "gear"];</code>
     * @return The gear.
     */
    public java.lang.String getGear() {
      java.lang.Object ref = gear_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        gear_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * "P" / "R" / "N" / "D" / "M" / "S", or "UNKNOWN".
     * </pre>
     *
     * <code>string gear = 1 [json_name = "gear"];</code>
     * @return The bytes for gear.
     */
    public com.google.protobuf.ByteString
        getGearBytes() {
      java.lang.Object ref = gear_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        gear_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * "P" / "R" / "N" / "D" / "M" / "S", or "UNKNOWN".
     * </pre>
     *
     * <code>string gear = 1 [json_name = "gear"];</code>
     * @param value The gear to set.
     * @return This builder for chaining.
     */
    public Builder setGear(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      gear_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * "P" / "R" / "N" / "D" / "M" / "S", or "UNKNOWN".
     * </pre>
     *
     * <code>string gear = 1 [json_name = "gear"];</code>
     * @return This builder for chaining.
     */
    public Builder clearGear() {
      gear_ = getDefaultInstance().getGear();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * "P" / "R" / "N" / "D" / "M" / "S", or "UNKNOWN".
     * </pre>
     *
     * <code>string gear = 1 [json_name = "gear"];</code>
     * @param value The bytes for gear to set.
     * @return This builder for chaining.
     */
    public Builder setGearBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      gear_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object driveMode_ = "";
    /**
     * <pre>
     * "ECO/NORMAL" (the car reads one value for both) / "SPORT", or "UNKNOWN".
     * </pre>
     *
     * <code>string drive_mode = 2 [json_name = "driveMode"];</code>
     * @return The driveMode.
     */
    public java.lang.String getDriveMode() {
      java.lang.Object ref = driveMode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        driveMode_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * "ECO/NORMAL" (the car reads one value for both) / "SPORT", or "UNKNOWN".
     * </pre>
     *
     * <code>string drive_mode = 2 [json_name = "driveMode"];</code>
     * @return The bytes for driveMode.
     */
    public com.google.protobuf.ByteString
        getDriveModeBytes() {
      java.lang.Object ref = driveMode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        driveMode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * "ECO/NORMAL" (the car reads one value for both) / "SPORT", or "UNKNOWN".
     * </pre>
     *
     * <code>string drive_mode = 2 [json_name = "driveMode"];</code>
     * @param value The driveMode to set.
     * @return This builder for chaining.
     */
    public Builder setDriveMode(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      driveMode_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * "ECO/NORMAL" (the car reads one value for both) / "SPORT", or "UNKNOWN".
     * </pre>
     *
     * <code>string drive_mode = 2 [json_name = "driveMode"];</code>
     * @return This builder for chaining.
     */
    public Builder clearDriveMode() {
      driveMode_ = getDefaultInstance().getDriveMode();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * "ECO/NORMAL" (the car reads one value for both) / "SPORT", or "UNKNOWN".
     * </pre>
     *
     * <code>string drive_mode = 2 [json_name = "driveMode"];</code>
     * @param value The bytes for driveMode to set.
     * @return This builder for chaining.
     */
    public Builder setDriveModeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      driveMode_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private int driveModeRaw_ ;
    /**
     * <pre>
     * BYDAutoEnergyDevice.getOperationMode().
     * </pre>
     *
     * <code>int32 drive_mode_raw = 3 [json_name = "driveModeRaw"];</code>
     * @return The driveModeRaw.
     */
    @java.lang.Override
    public int getDriveModeRaw() {
      return driveModeRaw_;
    }
    /**
     * <pre>
     * BYDAutoEnergyDevice.getOperationMode().
     * </pre>
     *
     * <code>int32 drive_mode_raw = 3 [json_name = "driveModeRaw"];</code>
     * @param value The driveModeRaw to set.
     * @return This builder for chaining.
     */
    public Builder setDriveModeRaw(int value) {

      driveModeRaw_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * BYDAutoEnergyDevice.getOperationMode().
     * </pre>
     *
     * <code>int32 drive_mode_raw = 3 [json_name = "driveModeRaw"];</code>
     * @return This builder for chaining.
     */
    public Builder clearDriveModeRaw() {
      bitField0_ = (bitField0_ & ~0x00000004);
      driveModeRaw_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object autoHold_ = "";
    /**
     * <pre>
     * "DISABLED" / "ENABLED" / "ACTIVE", or "UNKNOWN".
     * </pre>
     *
     * <code>string auto_hold = 4 [json_name = "autoHold"];</code>
     * @return The autoHold.
     */
    public java.lang.String getAutoHold() {
      java.lang.Object ref = autoHold_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        autoHold_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * "DISABLED" / "ENABLED" / "ACTIVE", or "UNKNOWN".
     * </pre>
     *
     * <code>string auto_hold = 4 [json_name = "autoHold"];</code>
     * @return The bytes for autoHold.
     */
    public com.google.protobuf.ByteString
        getAutoHoldBytes() {
      java.lang.Object ref = autoHold_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        autoHold_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * "DISABLED" / "ENABLED" / "ACTIVE", or "UNKNOWN".
     * </pre>
     *
     * <code>string auto_hold = 4 [json_name = "autoHold"];</code>
     * @param value The autoHold to set.
     * @return This builder for chaining.
     */
    public Builder setAutoHold(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      autoHold_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * "DISABLED" / "ENABLED" / "ACTIVE", or "UNKNOWN".
     * </pre>
     *
     * <code>string auto_hold = 4 [json_name = "autoHold"];</code>
     * @return This builder for chaining.
     */
    public Builder clearAutoHold() {
      autoHold_ = getDefaultInstance().getAutoHold();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * "DISABLED" / "ENABLED" / "ACTIVE", or "UNKNOWN".
     * </pre>
     *
     * <code>string auto_hold = 4 [json_name = "autoHold"];</code>
     * @param value The bytes for autoHold to set.
     * @return This builder for chaining.
     */
    public Builder setAutoHoldBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      autoHold_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private int autoHoldRaw_ ;
    /**
     * <pre>
     * BYDAutoADASDevice.getAVHState().
     * </pre>
     *
     * <code>int32 auto_hold_raw = 5 [json_name = "autoHoldRaw"];</code>
     * @return The autoHoldRaw.
     */
    @java.lang.Override
    public int getAutoHoldRaw() {
      return autoHoldRaw_;
    }
    /**
     * <pre>
     * BYDAutoADASDevice.getAVHState().
     * </pre>
     *
     * <code>int32 auto_hold_raw = 5 [json_name = "autoHoldRaw"];</code>
     * @param value The autoHoldRaw to set.
     * @return This builder for chaining.
     */
    public Builder setAutoHoldRaw(int value) {

      autoHoldRaw_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * BYDAutoADASDevice.getAVHState().
     * </pre>
     *
     * <code>int32 auto_hold_raw = 5 [json_name = "autoHoldRaw"];</code>
     * @return This builder for chaining.
     */
    public Builder clearAutoHoldRaw() {
      bitField0_ = (bitField0_ & ~0x00000010);
      autoHoldRaw_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object energyMode_ = "";
    /**
     * <pre>
     * "EV" / "HEV", or "UNKNOWN".
     * </pre>
     *
     * <code>string energy_mode = 6 [json_name = "energyMode"];</code>
     * @return The energyMode.
     */
    public java.lang.String getEnergyMode() {
      java.lang.Object ref = energyMode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        energyMode_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * "EV" / "HEV", or "UNKNOWN".
     * </pre>
     *
     * <code>string energy_mode = 6 [json_name = "energyMode"];</code>
     * @return The bytes for energyMode.
     */
    public com.google.protobuf.ByteString
        getEnergyModeBytes() {
      java.lang.Object ref = energyMode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        energyMode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * "EV" / "HEV", or "UNKNOWN".
     * </pre>
     *
     * <code>string energy_mode = 6 [json_name = "energyMode"];</code>
     * @param value The energyMode to set.
     * @return This builder for chaining.
     */
    public Builder setEnergyMode(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      energyMode_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * "EV" / "HEV", or "UNKNOWN".
     * </pre>
     *
     * <code>string energy_mode = 6 [json_name = "energyMode"];</code>
     * @return This builder for chaining.
     */
    public Builder clearEnergyMode() {
      energyMode_ = getDefaultInstance().getEnergyMode();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * "EV" / "HEV", or "UNKNOWN".
     * </pre>
     *
     * <code>string energy_mode = 6 [json_name = "energyMode"];</code>
     * @param value The bytes for energyMode to set.
     * @return This builder for chaining.
     */
    public Builder setEnergyModeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      energyMode_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private int energyModeRaw_ ;
    /**
     * <pre>
     * BYDAutoEnergyDevice.getEnergyMode().
     * </pre>
     *
     * <code>int32 energy_mode_raw = 7 [json_name = "energyModeRaw"];</code>
     * @return The energyModeRaw.
     */
    @java.lang.Override
    public int getEnergyModeRaw() {
      return energyModeRaw_;
    }
    /**
     * <pre>
     * BYDAutoEnergyDevice.getEnergyMode().
     * </pre>
     *
     * <code>int32 energy_mode_raw = 7 [json_name = "energyModeRaw"];</code>
     * @param value The energyModeRaw to set.
     * @return This builder for chaining.
     */
    public Builder setEnergyModeRaw(int value) {

      energyModeRaw_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * BYDAutoEnergyDevice.getEnergyMode().
     * </pre>
     *
     * <code>int32 energy_mode_raw = 7 [json_name = "energyModeRaw"];</code>
     * @return This builder for chaining.
     */
    public Builder clearEnergyModeRaw() {
      bitField0_ = (bitField0_ & ~0x00000040);
      energyModeRaw_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:bladewatch.v1.DriveStatus)
  }

  // @@protoc_insertion_point(class_scope:bladewatch.v1.DriveStatus)
  private static final net.bladewatch.app.grpc.v1.DriveStatus DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new net.bladewatch.app.grpc.v1.DriveStatus();
  }

  public static net.bladewatch.app.grpc.v1.DriveStatus getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DriveStatus>
      PARSER = new com.google.protobuf.AbstractParser<DriveStatus>() {
    @java.lang.Override
    public DriveStatus parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<DriveStatus> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DriveStatus> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public net.bladewatch.app.grpc.v1.DriveStatus getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

