// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bladewatch/v1/settings.proto
// Protobuf Java Version: 4.35.0

package net.bladewatch.app.grpc.v1;

@com.google.protobuf.Generated
public interface FieldListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bladewatch.v1.FieldList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string fields = 1 [json_name = "fields"];</code>
   * @return A list containing the fields.
   */
  java.util.List<java.lang.String>
      getFieldsList();
  /**
   * <code>repeated string fields = 1 [json_name = "fields"];</code>
   * @return The count of fields.
   */
  int getFieldsCount();
  /**
   * <code>repeated string fields = 1 [json_name = "fields"];</code>
   * @param index The index of the element to return.
   * @return The fields at the given index.
   */
  java.lang.String getFields(int index);
  /**
   * <code>repeated string fields = 1 [json_name = "fields"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the fields at the given index.
   */
  com.google.protobuf.ByteString
      getFieldsBytes(int index);
}
