// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bladewatch/v1/settings.proto
// Protobuf Java Version: 4.35.0

package net.bladewatch.app.grpc.v1;

@com.google.protobuf.Generated
public interface GetSettingsLockResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bladewatch.v1.GetSettingsLockResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool enabled = 1 [json_name = "enabled"];</code>
   * @return The enabled.
   */
  boolean getEnabled();

  /**
   * <pre>
   * &gt; 0 while wrong PINs have locked entry out: ms until VerifySettingsPin should be tried again.
   * </pre>
   *
   * <code>int64 retry_after_ms = 2 [json_name = "retryAfterMs"];</code>
   * @return The retryAfterMs.
   */
  long getRetryAfterMs();
}
