// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bladewatch/v1/notifications.proto
// Protobuf Java Version: 4.35.0

package net.bladewatch.app.grpc.v1;

/**
 * <pre>
 * One notification the car raised, kept for companions (BladeWatch-rdtj.14).
 * </pre>
 *
 * Protobuf type {@code bladewatch.v1.InboxEntry}
 */
@com.google.protobuf.Generated
public final class InboxEntry extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:bladewatch.v1.InboxEntry)
    InboxEntryOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 0,
      /* suffix= */ "",
      "InboxEntry");
  }
  // Use InboxEntry.newBuilder() to construct.
  private InboxEntry(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private InboxEntry() {
    category_ = "";
    severity_ = 0;
    title_ = "";
    body_ = "";
    clickUrl_ = "";
    tag_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return net.bladewatch.app.grpc.v1.Notifications.internal_static_bladewatch_v1_InboxEntry_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return net.bladewatch.app.grpc.v1.Notifications.internal_static_bladewatch_v1_InboxEntry_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return net.bladewatch.app.grpc.v1.Notifications.internal_static_bladewatch_v1_InboxEntry_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            net.bladewatch.app.grpc.v1.InboxEntry.class, net.bladewatch.app.grpc.v1.InboxEntry.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private long id_ = 0L;
  /**
   * <pre>
   * Strictly increasing, and never reused -- also across daemon restarts.
   * </pre>
   *
   * <code>int64 id = 1 [json_name = "id"];</code>
   * @return The id.
   */
  @java.lang.Override
  public long getId() {
    return id_;
  }

  public static final int TIMESTAMP_MS_FIELD_NUMBER = 2;
  private long timestampMs_ = 0L;
  /**
   * <code>int64 timestamp_ms = 2 [json_name = "timestampMs"];</code>
   * @return The timestampMs.
   */
  @java.lang.Override
  public long getTimestampMs() {
    return timestampMs_;
  }

  public static final int CATEGORY_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object category_ = "";
  /**
   * <pre>
   * Dotted category, e.g. "surveillance.motion".
   * </pre>
   *
   * <code>string category = 3 [json_name = "category"];</code>
   * @return The category.
   */
  @java.lang.Override
  public java.lang.String getCategory() {
    java.lang.Object ref = category_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      category_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Dotted category, e.g. "surveillance.motion".
   * </pre>
   *
   * <code>string category = 3 [json_name = "category"];</code>
   * @return The bytes for category.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCategoryBytes() {
    java.lang.Object ref = category_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      category_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SEVERITY_FIELD_NUMBER = 4;
  private int severity_ = 0;
  /**
   * <code>.bladewatch.v1.NotificationSeverity severity = 4 [json_name = "severity"];</code>
   * @return The enum numeric value on the wire for severity.
   */
  @java.lang.Override public int getSeverityValue() {
    return severity_;
  }
  /**
   * <code>.bladewatch.v1.NotificationSeverity severity = 4 [json_name = "severity"];</code>
   * @return The severity.
   */
  @java.lang.Override public net.bladewatch.app.grpc.v1.NotificationSeverity getSeverity() {
    net.bladewatch.app.grpc.v1.NotificationSeverity result = net.bladewatch.app.grpc.v1.NotificationSeverity.forNumber(severity_);
    return result == null ? net.bladewatch.app.grpc.v1.NotificationSeverity.UNRECOGNIZED : result;
  }

  public static final int TITLE_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object title_ = "";
  /**
   * <code>string title = 5 [json_name = "title"];</code>
   * @return The title.
   */
  @java.lang.Override
  public java.lang.String getTitle() {
    java.lang.Object ref = title_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      title_ = s;
      return s;
    }
  }
  /**
   * <code>string title = 5 [json_name = "title"];</code>
   * @return The bytes for title.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTitleBytes() {
    java.lang.Object ref = title_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      title_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BODY_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object body_ = "";
  /**
   * <code>string body = 6 [json_name = "body"];</code>
   * @return The body.
   */
  @java.lang.Override
  public java.lang.String getBody() {
    java.lang.Object ref = body_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      body_ = s;
      return s;
    }
  }
  /**
   * <code>string body = 6 [json_name = "body"];</code>
   * @return The bytes for body.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getBodyBytes() {
    java.lang.Object ref = body_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      body_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CLICK_URL_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private volatile java.lang.Object clickUrl_ = "";
  /**
   * <pre>
   * Deep link the source gave, e.g. to the recording; empty when none.
   * </pre>
   *
   * <code>string click_url = 7 [json_name = "clickUrl"];</code>
   * @return The clickUrl.
   */
  @java.lang.Override
  public java.lang.String getClickUrl() {
    java.lang.Object ref = clickUrl_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      clickUrl_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Deep link the source gave, e.g. to the recording; empty when none.
   * </pre>
   *
   * <code>string click_url = 7 [json_name = "clickUrl"];</code>
   * @return The bytes for clickUrl.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getClickUrlBytes() {
    java.lang.Object ref = clickUrl_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      clickUrl_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TAG_FIELD_NUMBER = 8;
  @SuppressWarnings("serial")
  private volatile java.lang.Object tag_ = "";
  /**
   * <pre>
   * Events with the same tag supersede each other (e.g. "recording in progress" by the final
   * alert): the car keeps only the newest, and a companion should show only the newest it has.
   * Empty when the source gave none.
   * </pre>
   *
   * <code>string tag = 8 [json_name = "tag"];</code>
   * @return The tag.
   */
  @java.lang.Override
  public java.lang.String getTag() {
    java.lang.Object ref = tag_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      tag_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Events with the same tag supersede each other (e.g. "recording in progress" by the final
   * alert): the car keeps only the newest, and a companion should show only the newest it has.
   * Empty when the source gave none.
   * </pre>
   *
   * <code>string tag = 8 [json_name = "tag"];</code>
   * @return The bytes for tag.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTagBytes() {
    java.lang.Object ref = tag_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      tag_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0L) {
      output.writeInt64(1, id_);
    }
    if (timestampMs_ != 0L) {
      output.writeInt64(2, timestampMs_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(category_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, category_);
    }
    if (severity_ != net.bladewatch.app.grpc.v1.NotificationSeverity.NOTIFICATION_SEVERITY_UNSPECIFIED.getNumber()) {
      output.writeEnum(4, severity_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(title_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 5, title_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(body_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 6, body_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(clickUrl_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 7, clickUrl_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(tag_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 8, tag_);
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;
    if (id_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, id_);
    }
    if (timestampMs_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, timestampMs_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(category_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, category_);
    }
    if (severity_ != net.bladewatch.app.grpc.v1.NotificationSeverity.NOTIFICATION_SEVERITY_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(4, severity_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(title_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(5, title_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(body_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(6, body_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(clickUrl_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(7, clickUrl_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(tag_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(8, tag_);
    }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof net.bladewatch.app.grpc.v1.InboxEntry)) {
      return super.equals(obj);
    }
    net.bladewatch.app.grpc.v1.InboxEntry other = (net.bladewatch.app.grpc.v1.InboxEntry) obj;

    if (getId()
        != other.getId()) return false;
    if (getTimestampMs()
        != other.getTimestampMs()) return false;
    if (!getCategory()
        .equals(other.getCategory())) return false;
    if (severity_ != other.severity_) return false;
    if (!getTitle()
        .equals(other.getTitle())) return false;
    if (!getBody()
        .equals(other.getBody())) return false;
    if (!getClickUrl()
        .equals(other.getClickUrl())) return false;
    if (!getTag()
        .equals(other.getTag())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getId());
    hash = (37 * hash) + TIMESTAMP_MS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTimestampMs());
    hash = (37 * hash) + CATEGORY_FIELD_NUMBER;
    hash = (53 * hash) + getCategory().hashCode();
    hash = (37 * hash) + SEVERITY_FIELD_NUMBER;
    hash = (53 * hash) + severity_;
    hash = (37 * hash) + TITLE_FIELD_NUMBER;
    hash = (53 * hash) + getTitle().hashCode();
    hash = (37 * hash) + BODY_FIELD_NUMBER;
    hash = (53 * hash) + getBody().hashCode();
    hash = (37 * hash) + CLICK_URL_FIELD_NUMBER;
    hash = (53 * hash) + getClickUrl().hashCode();
    hash = (37 * hash) + TAG_FIELD_NUMBER;
    hash = (53 * hash) + getTag().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static net.bladewatch.app.grpc.v1.InboxEntry parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.bladewatch.app.grpc.v1.InboxEntry parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.bladewatch.app.grpc.v1.InboxEntry parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.bladewatch.app.grpc.v1.InboxEntry parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.bladewatch.app.grpc.v1.InboxEntry parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.bladewatch.app.grpc.v1.InboxEntry parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.bladewatch.app.grpc.v1.InboxEntry parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static net.bladewatch.app.grpc.v1.InboxEntry parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static net.bladewatch.app.grpc.v1.InboxEntry parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static net.bladewatch.app.grpc.v1.InboxEntry parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static net.bladewatch.app.grpc.v1.InboxEntry parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static net.bladewatch.app.grpc.v1.InboxEntry parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(net.bladewatch.app.grpc.v1.InboxEntry prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * One notification the car raised, kept for companions (BladeWatch-rdtj.14).
   * </pre>
   *
   * Protobuf type {@code bladewatch.v1.InboxEntry}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:bladewatch.v1.InboxEntry)
      net.bladewatch.app.grpc.v1.InboxEntryOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.bladewatch.app.grpc.v1.Notifications.internal_static_bladewatch_v1_InboxEntry_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.bladewatch.app.grpc.v1.Notifications.internal_static_bladewatch_v1_InboxEntry_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.bladewatch.app.grpc.v1.InboxEntry.class, net.bladewatch.app.grpc.v1.InboxEntry.Builder.class);
    }

    // Construct using net.bladewatch.app.grpc.v1.InboxEntry.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      id_ = 0L;
      timestampMs_ = 0L;
      category_ = "";
      severity_ = 0;
      title_ = "";
      body_ = "";
      clickUrl_ = "";
      tag_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return net.bladewatch.app.grpc.v1.Notifications.internal_static_bladewatch_v1_InboxEntry_descriptor;
    }

    @java.lang.Override
    public net.bladewatch.app.grpc.v1.InboxEntry getDefaultInstanceForType() {
      return net.bladewatch.app.grpc.v1.InboxEntry.getDefaultInstance();
    }

    @java.lang.Override
    public net.bladewatch.app.grpc.v1.InboxEntry build() {
      net.bladewatch.app.grpc.v1.InboxEntry result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public net.bladewatch.app.grpc.v1.InboxEntry buildPartial() {
      net.bladewatch.app.grpc.v1.InboxEntry result = new net.bladewatch.app.grpc.v1.InboxEntry(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(net.bladewatch.app.grpc.v1.InboxEntry result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.id_ = id_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.timestampMs_ = timestampMs_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.category_ = category_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.severity_ = severity_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.title_ = title_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.body_ = body_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.clickUrl_ = clickUrl_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.tag_ = tag_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof net.bladewatch.app.grpc.v1.InboxEntry) {
        return mergeFrom((net.bladewatch.app.grpc.v1.InboxEntry)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(net.bladewatch.app.grpc.v1.InboxEntry other) {
      if (other == net.bladewatch.app.grpc.v1.InboxEntry.getDefaultInstance()) return this;
      if (other.getId() != 0L) {
        setId(other.getId());
      }
      if (other.getTimestampMs() != 0L) {
        setTimestampMs(other.getTimestampMs());
      }
      if (!other.getCategory().isEmpty()) {
        category_ = other.category_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (other.severity_ != 0) {
        setSeverityValue(other.getSeverityValue());
      }
      if (!other.getTitle().isEmpty()) {
        title_ = other.title_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (!other.getBody().isEmpty()) {
        body_ = other.body_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      if (!other.getClickUrl().isEmpty()) {
        clickUrl_ = other.clickUrl_;
        bitField0_ |= 0x00000040;
        onChanged();
      }
      if (!other.getTag().isEmpty()) {
        tag_ = other.tag_;
        bitField0_ |= 0x00000080;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              id_ = input.readInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              timestampMs_ = input.readInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              category_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 32: {
              severity_ = input.readEnum();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 42: {
              title_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              body_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              clickUrl_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            case 66: {
              tag_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000080;
              break;
            } // case 66
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long id_ ;
    /**
     * <pre>
     * Strictly increasing, and never reused -- also across daemon restarts.
     * </pre>
     *
     * <code>int64 id = 1 [json_name = "id"];</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }
    /**
     * <pre>
     * Strictly increasing, and never reused -- also across daemon restarts.
     * </pre>
     *
     * <code>int64 id = 1 [json_name = "id"];</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(long value) {

      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Strictly increasing, and never reused -- also across daemon restarts.
     * </pre>
     *
     * <code>int64 id = 1 [json_name = "id"];</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      id_ = 0L;
      onChanged();
      return this;
    }

    private long timestampMs_ ;
    /**
     * <code>int64 timestamp_ms = 2 [json_name = "timestampMs"];</code>
     * @return The timestampMs.
     */
    @java.lang.Override
    public long getTimestampMs() {
      return timestampMs_;
    }
    /**
     * <code>int64 timestamp_ms = 2 [json_name = "timestampMs"];</code>
     * @param value The timestampMs to set.
     * @return This builder for chaining.
     */
    public Builder setTimestampMs(long value) {

      timestampMs_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int64 timestamp_ms = 2 [json_name = "timestampMs"];</code>
     * @return This builder for chaining.
     */
    public Builder clearTimestampMs() {
      bitField0_ = (bitField0_ & ~0x00000002);
      timestampMs_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object category_ = "";
    /**
     * <pre>
     * Dotted category, e.g. "surveillance.motion".
     * </pre>
     *
     * <code>string category = 3 [json_name = "category"];</code>
     * @return The category.
     */
    public java.lang.String getCategory() {
      java.lang.Object ref = category_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        category_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Dotted category, e.g. "surveillance.motion".
     * </pre>
     *
     * <code>string category = 3 [json_name = "category"];</code>
     * @return The bytes for category.
     */
    public com.google.protobuf.ByteString
        getCategoryBytes() {
      java.lang.Object ref = category_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        category_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Dotted category, e.g. "surveillance.motion".
     * </pre>
     *
     * <code>string category = 3 [json_name = "category"];</code>
     * @param value The category to set.
     * @return This builder for chaining.
     */
    public Builder setCategory(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      category_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Dotted category, e.g. "surveillance.motion".
     * </pre>
     *
     * <code>string category = 3 [json_name = "category"];</code>
     * @return This builder for chaining.
     */
    public Builder clearCategory() {
      category_ = getDefaultInstance().getCategory();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Dotted category, e.g. "surveillance.motion".
     * </pre>
     *
     * <code>string category = 3 [json_name = "category"];</code>
     * @param value The bytes for category to set.
     * @return This builder for chaining.
     */
    public Builder setCategoryBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      category_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private int severity_ = 0;
    /**
     * <code>.bladewatch.v1.NotificationSeverity severity = 4 [json_name = "severity"];</code>
     * @return The enum numeric value on the wire for severity.
     */
    @java.lang.Override public int getSeverityValue() {
      return severity_;
    }
    /**
     * <code>.bladewatch.v1.NotificationSeverity severity = 4 [json_name = "severity"];</code>
     * @param value The enum numeric value on the wire for severity to set.
     * @return This builder for chaining.
     */
    public Builder setSeverityValue(int value) {
      severity_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.bladewatch.v1.NotificationSeverity severity = 4 [json_name = "severity"];</code>
     * @return The severity.
     */
    @java.lang.Override
    public net.bladewatch.app.grpc.v1.NotificationSeverity getSeverity() {
      net.bladewatch.app.grpc.v1.NotificationSeverity result = net.bladewatch.app.grpc.v1.NotificationSeverity.forNumber(severity_);
      return result == null ? net.bladewatch.app.grpc.v1.NotificationSeverity.UNRECOGNIZED : result;
    }
    /**
     * <code>.bladewatch.v1.NotificationSeverity severity = 4 [json_name = "severity"];</code>
     * @param value The severity to set.
     * @throws IllegalArgumentException if UNRECOGNIZED is provided.
     * @return This builder for chaining.
     */
    public Builder setSeverity(net.bladewatch.app.grpc.v1.NotificationSeverity value) {
      if (value == null) { throw new NullPointerException(); }
      bitField0_ |= 0x00000008;
      severity_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.bladewatch.v1.NotificationSeverity severity = 4 [json_name = "severity"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSeverity() {
      bitField0_ = (bitField0_ & ~0x00000008);
      severity_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object title_ = "";
    /**
     * <code>string title = 5 [json_name = "title"];</code>
     * @return The title.
     */
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        title_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string title = 5 [json_name = "title"];</code>
     * @return The bytes for title.
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string title = 5 [json_name = "title"];</code>
     * @param value The title to set.
     * @return This builder for chaining.
     */
    public Builder setTitle(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      title_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>string title = 5 [json_name = "title"];</code>
     * @return This builder for chaining.
     */
    public Builder clearTitle() {
      title_ = getDefaultInstance().getTitle();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>string title = 5 [json_name = "title"];</code>
     * @param value The bytes for title to set.
     * @return This builder for chaining.
     */
    public Builder setTitleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      title_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private java.lang.Object body_ = "";
    /**
     * <code>string body = 6 [json_name = "body"];</code>
     * @return The body.
     */
    public java.lang.String getBody() {
      java.lang.Object ref = body_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        body_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string body = 6 [json_name = "body"];</code>
     * @return The bytes for body.
     */
    public com.google.protobuf.ByteString
        getBodyBytes() {
      java.lang.Object ref = body_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        body_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string body = 6 [json_name = "body"];</code>
     * @param value The body to set.
     * @return This builder for chaining.
     */
    public Builder setBody(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      body_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>string body = 6 [json_name = "body"];</code>
     * @return This builder for chaining.
     */
    public Builder clearBody() {
      body_ = getDefaultInstance().getBody();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <code>string body = 6 [json_name = "body"];</code>
     * @param value The bytes for body to set.
     * @return This builder for chaining.
     */
    public Builder setBodyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      body_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private java.lang.Object clickUrl_ = "";
    /**
     * <pre>
     * Deep link the source gave, e.g. to the recording; empty when none.
     * </pre>
     *
     * <code>string click_url = 7 [json_name = "clickUrl"];</code>
     * @return The clickUrl.
     */
    public java.lang.String getClickUrl() {
      java.lang.Object ref = clickUrl_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        clickUrl_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Deep link the source gave, e.g. to the recording; empty when none.
     * </pre>
     *
     * <code>string click_url = 7 [json_name = "clickUrl"];</code>
     * @return The bytes for clickUrl.
     */
    public com.google.protobuf.ByteString
        getClickUrlBytes() {
      java.lang.Object ref = clickUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clickUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Deep link the source gave, e.g. to the recording; empty when none.
     * </pre>
     *
     * <code>string click_url = 7 [json_name = "clickUrl"];</code>
     * @param value The clickUrl to set.
     * @return This builder for chaining.
     */
    public Builder setClickUrl(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      clickUrl_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Deep link the source gave, e.g. to the recording; empty when none.
     * </pre>
     *
     * <code>string click_url = 7 [json_name = "clickUrl"];</code>
     * @return This builder for chaining.
     */
    public Builder clearClickUrl() {
      clickUrl_ = getDefaultInstance().getClickUrl();
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Deep link the source gave, e.g. to the recording; empty when none.
     * </pre>
     *
     * <code>string click_url = 7 [json_name = "clickUrl"];</code>
     * @param value The bytes for clickUrl to set.
     * @return This builder for chaining.
     */
    public Builder setClickUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      clickUrl_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }

    private java.lang.Object tag_ = "";
    /**
     * <pre>
     * Events with the same tag supersede each other (e.g. "recording in progress" by the final
     * alert): the car keeps only the newest, and a companion should show only the newest it has.
     * Empty when the source gave none.
     * </pre>
     *
     * <code>string tag = 8 [json_name = "tag"];</code>
     * @return The tag.
     */
    public java.lang.String getTag() {
      java.lang.Object ref = tag_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tag_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Events with the same tag supersede each other (e.g. "recording in progress" by the final
     * alert): the car keeps only the newest, and a companion should show only the newest it has.
     * Empty when the source gave none.
     * </pre>
     *
     * <code>string tag = 8 [json_name = "tag"];</code>
     * @return The bytes for tag.
     */
    public com.google.protobuf.ByteString
        getTagBytes() {
      java.lang.Object ref = tag_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tag_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Events with the same tag supersede each other (e.g. "recording in progress" by the final
     * alert): the car keeps only the newest, and a companion should show only the newest it has.
     * Empty when the source gave none.
     * </pre>
     *
     * <code>string tag = 8 [json_name = "tag"];</code>
     * @param value The tag to set.
     * @return This builder for chaining.
     */
    public Builder setTag(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      tag_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Events with the same tag supersede each other (e.g. "recording in progress" by the final
     * alert): the car keeps only the newest, and a companion should show only the newest it has.
     * Empty when the source gave none.
     * </pre>
     *
     * <code>string tag = 8 [json_name = "tag"];</code>
     * @return This builder for chaining.
     */
    public Builder clearTag() {
      tag_ = getDefaultInstance().getTag();
      bitField0_ = (bitField0_ & ~0x00000080);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Events with the same tag supersede each other (e.g. "recording in progress" by the final
     * alert): the car keeps only the newest, and a companion should show only the newest it has.
     * Empty when the source gave none.
     * </pre>
     *
     * <code>string tag = 8 [json_name = "tag"];</code>
     * @param value The bytes for tag to set.
     * @return This builder for chaining.
     */
    public Builder setTagBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      tag_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:bladewatch.v1.InboxEntry)
  }

  // @@protoc_insertion_point(class_scope:bladewatch.v1.InboxEntry)
  private static final net.bladewatch.app.grpc.v1.InboxEntry DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new net.bladewatch.app.grpc.v1.InboxEntry();
  }

  public static net.bladewatch.app.grpc.v1.InboxEntry getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<InboxEntry>
      PARSER = new com.google.protobuf.AbstractParser<InboxEntry>() {
    @java.lang.Override
    public InboxEntry parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<InboxEntry> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<InboxEntry> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public net.bladewatch.app.grpc.v1.InboxEntry getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

