// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bladewatch/v1/notifications.proto
// Protobuf Java Version: 4.35.0

package net.bladewatch.app.grpc.v1;

@com.google.protobuf.Generated
public interface InboxEntryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bladewatch.v1.InboxEntry)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Strictly increasing, and never reused -- also across daemon restarts.
   * </pre>
   *
   * <code>int64 id = 1 [json_name = "id"];</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>int64 timestamp_ms = 2 [json_name = "timestampMs"];</code>
   * @return The timestampMs.
   */
  long getTimestampMs();

  /**
   * <pre>
   * Dotted category, e.g. "surveillance.motion".
   * </pre>
   *
   * <code>string category = 3 [json_name = "category"];</code>
   * @return The category.
   */
  java.lang.String getCategory();
  /**
   * <pre>
   * Dotted category, e.g. "surveillance.motion".
   * </pre>
   *
   * <code>string category = 3 [json_name = "category"];</code>
   * @return The bytes for category.
   */
  com.google.protobuf.ByteString
      getCategoryBytes();

  /**
   * <code>.bladewatch.v1.NotificationSeverity severity = 4 [json_name = "severity"];</code>
   * @return The enum numeric value on the wire for severity.
   */
  int getSeverityValue();
  /**
   * <code>.bladewatch.v1.NotificationSeverity severity = 4 [json_name = "severity"];</code>
   * @return The severity.
   */
  net.bladewatch.app.grpc.v1.NotificationSeverity getSeverity();

  /**
   * <code>string title = 5 [json_name = "title"];</code>
   * @return The title.
   */
  java.lang.String getTitle();
  /**
   * <code>string title = 5 [json_name = "title"];</code>
   * @return The bytes for title.
   */
  com.google.protobuf.ByteString
      getTitleBytes();

  /**
   * <code>string body = 6 [json_name = "body"];</code>
   * @return The body.
   */
  java.lang.String getBody();
  /**
   * <code>string body = 6 [json_name = "body"];</code>
   * @return The bytes for body.
   */
  com.google.protobuf.ByteString
      getBodyBytes();

  /**
   * <pre>
   * Deep link the source gave, e.g. to the recording; empty when none.
   * </pre>
   *
   * <code>string click_url = 7 [json_name = "clickUrl"];</code>
   * @return The clickUrl.
   */
  java.lang.String getClickUrl();
  /**
   * <pre>
   * Deep link the source gave, e.g. to the recording; empty when none.
   * </pre>
   *
   * <code>string click_url = 7 [json_name = "clickUrl"];</code>
   * @return The bytes for clickUrl.
   */
  com.google.protobuf.ByteString
      getClickUrlBytes();

  /**
   * <pre>
   * Events with the same tag supersede each other (e.g. "recording in progress" by the final
   * alert): the car keeps only the newest, and a companion should show only the newest it has.
   * Empty when the source gave none.
   * </pre>
   *
   * <code>string tag = 8 [json_name = "tag"];</code>
   * @return The tag.
   */
  java.lang.String getTag();
  /**
   * <pre>
   * Events with the same tag supersede each other (e.g. "recording in progress" by the final
   * alert): the car keeps only the newest, and a companion should show only the newest it has.
   * Empty when the source gave none.
   * </pre>
   *
   * <code>string tag = 8 [json_name = "tag"];</code>
   * @return The bytes for tag.
   */
  com.google.protobuf.ByteString
      getTagBytes();
}
