// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bladewatch/v1/notifications.proto
// Protobuf Java Version: 4.35.0

package net.bladewatch.app.grpc.v1;

@com.google.protobuf.Generated
public interface ListInboxResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bladewatch.v1.ListInboxResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .bladewatch.v1.InboxEntry entries = 1 [json_name = "entries"];</code>
   */
  java.util.List<net.bladewatch.app.grpc.v1.InboxEntry> 
      getEntriesList();
  /**
   * <code>repeated .bladewatch.v1.InboxEntry entries = 1 [json_name = "entries"];</code>
   */
  net.bladewatch.app.grpc.v1.InboxEntry getEntries(int index);
  /**
   * <code>repeated .bladewatch.v1.InboxEntry entries = 1 [json_name = "entries"];</code>
   */
  int getEntriesCount();
  /**
   * <code>repeated .bladewatch.v1.InboxEntry entries = 1 [json_name = "entries"];</code>
   */
  java.util.List<? extends net.bladewatch.app.grpc.v1.InboxEntryOrBuilder> 
      getEntriesOrBuilderList();
  /**
   * <code>repeated .bladewatch.v1.InboxEntry entries = 1 [json_name = "entries"];</code>
   */
  net.bladewatch.app.grpc.v1.InboxEntryOrBuilder getEntriesOrBuilder(
      int index);

  /**
   * <pre>
   * The newest and oldest ids the car still holds (0 when empty). The inbox is bounded: a
   * companion whose after_id is below oldest_id - 1 missed entries that were dropped.
   * </pre>
   *
   * <code>int64 latest_id = 2 [json_name = "latestId"];</code>
   * @return The latestId.
   */
  long getLatestId();

  /**
   * <code>int64 oldest_id = 3 [json_name = "oldestId"];</code>
   * @return The oldestId.
   */
  long getOldestId();
}
