// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bladewatch/v1/notifications.proto
// Protobuf Java Version: 4.35.0

package net.bladewatch.app.grpc.v1;

@com.google.protobuf.Generated
public final class Notifications extends com.google.protobuf.GeneratedFile {
  private Notifications() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 0,
      /* suffix= */ "",
      "Notifications");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_GetCategoriesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_GetCategoriesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_GetCategoriesResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_GetCategoriesResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_SendTestRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_SendTestRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_SendTestResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_SendTestResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_InboxEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_InboxEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_ListInboxRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_ListInboxRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_ListInboxResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_ListInboxResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!bladewatch/v1/notifications.proto\022\rbla" +
      "dewatch.v1\"\026\n\024GetCategoriesRequest\"X\n\025Ge" +
      "tCategoriesResponse\022\'\n\017categories_json\030\001" +
      " \001(\tR\016categoriesJsonJ\004\010\002\020\003R\020vapid_public" +
      "_key\"I\n\017SendTestRequest\022\032\n\010category\030\001 \001(" +
      "\tR\010category\022\032\n\010severity\030\002 \001(\tR\010severity\"" +
      ",\n\020SendTestResponse\022\030\n\007success\030\001 \001(\010R\007su" +
      "ccess\"\365\001\n\nInboxEntry\022\016\n\002id\030\001 \001(\003R\002id\022!\n\014" +
      "timestamp_ms\030\002 \001(\003R\013timestampMs\022\032\n\010categ" +
      "ory\030\003 \001(\tR\010category\022?\n\010severity\030\004 \001(\0162#." +
      "bladewatch.v1.NotificationSeverityR\010seve" +
      "rity\022\024\n\005title\030\005 \001(\tR\005title\022\022\n\004body\030\006 \001(\t" +
      "R\004body\022\033\n\tclick_url\030\007 \001(\tR\010clickUrl\022\020\n\003t" +
      "ag\030\010 \001(\tR\003tag\"C\n\020ListInboxRequest\022\031\n\010aft" +
      "er_id\030\001 \001(\003R\007afterId\022\024\n\005limit\030\002 \001(\005R\005lim" +
      "it\"\202\001\n\021ListInboxResponse\0223\n\007entries\030\001 \003(" +
      "\0132\031.bladewatch.v1.InboxEntryR\007entries\022\033\n" +
      "\tlatest_id\030\002 \001(\003R\010latestId\022\033\n\toldest_id\030" +
      "\003 \001(\003R\010oldestId*\242\001\n\024NotificationSeverity" +
      "\022%\n!NOTIFICATION_SEVERITY_UNSPECIFIED\020\000\022" +
      "\036\n\032NOTIFICATION_SEVERITY_INFO\020\001\022\037\n\033NOTIF" +
      "ICATION_SEVERITY_ALERT\020\002\022\"\n\036NOTIFICATION" +
      "_SEVERITY_CRITICAL\020\0032\217\002\n\024NotificationsSe" +
      "rvice\022Z\n\rGetCategories\022#.bladewatch.v1.G" +
      "etCategoriesRequest\032$.bladewatch.v1.GetC" +
      "ategoriesResponse\022K\n\010SendTest\022\036.bladewat" +
      "ch.v1.SendTestRequest\032\037.bladewatch.v1.Se" +
      "ndTestResponse\022N\n\tListInbox\022\037.bladewatch" +
      ".v1.ListInboxRequest\032 .bladewatch.v1.Lis" +
      "tInboxResponseB\036\n\032net.bladewatch.app.grp" +
      "c.v1P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_bladewatch_v1_GetCategoriesRequest_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_bladewatch_v1_GetCategoriesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_GetCategoriesRequest_descriptor,
        new java.lang.String[] { });
    internal_static_bladewatch_v1_GetCategoriesResponse_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_bladewatch_v1_GetCategoriesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_GetCategoriesResponse_descriptor,
        new java.lang.String[] { "CategoriesJson", });
    internal_static_bladewatch_v1_SendTestRequest_descriptor =
      getDescriptor().getMessageType(2);
    internal_static_bladewatch_v1_SendTestRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_SendTestRequest_descriptor,
        new java.lang.String[] { "Category", "Severity", });
    internal_static_bladewatch_v1_SendTestResponse_descriptor =
      getDescriptor().getMessageType(3);
    internal_static_bladewatch_v1_SendTestResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_SendTestResponse_descriptor,
        new java.lang.String[] { "Success", });
    internal_static_bladewatch_v1_InboxEntry_descriptor =
      getDescriptor().getMessageType(4);
    internal_static_bladewatch_v1_InboxEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_InboxEntry_descriptor,
        new java.lang.String[] { "Id", "TimestampMs", "Category", "Severity", "Title", "Body", "ClickUrl", "Tag", });
    internal_static_bladewatch_v1_ListInboxRequest_descriptor =
      getDescriptor().getMessageType(5);
    internal_static_bladewatch_v1_ListInboxRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_ListInboxRequest_descriptor,
        new java.lang.String[] { "AfterId", "Limit", });
    internal_static_bladewatch_v1_ListInboxResponse_descriptor =
      getDescriptor().getMessageType(6);
    internal_static_bladewatch_v1_ListInboxResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_ListInboxResponse_descriptor,
        new java.lang.String[] { "Entries", "LatestId", "OldestId", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
