// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bladewatch/v1/system.proto
// Protobuf Java Version: 4.35.0

package net.bladewatch.app.grpc.v1;

@com.google.protobuf.Generated
public interface PerformanceConnectRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bladewatch.v1.PerformanceConnectRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Caller-chosen id. The server echoes back the id it registered, which is the one that must
   * be used for heartbeat and disconnect.
   * </pre>
   *
   * <code>string client_id = 1 [json_name = "clientId"];</code>
   * @return The clientId.
   */
  java.lang.String getClientId();
  /**
   * <pre>
   * Caller-chosen id. The server echoes back the id it registered, which is the one that must
   * be used for heartbeat and disconnect.
   * </pre>
   *
   * <code>string client_id = 1 [json_name = "clientId"];</code>
   * @return The bytes for clientId.
   */
  com.google.protobuf.ByteString
      getClientIdBytes();
}
