// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bladewatch/v1/storage.proto
// Protobuf Java Version: 4.35.0

package net.bladewatch.app.grpc.v1;

/**
 * Protobuf type {@code bladewatch.v1.PreviewStorageLimitChangeResponse}
 */
@com.google.protobuf.Generated
public final class PreviewStorageLimitChangeResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:bladewatch.v1.PreviewStorageLimitChangeResponse)
    PreviewStorageLimitChangeResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 0,
      /* suffix= */ "",
      "PreviewStorageLimitChangeResponse");
  }
  // Use PreviewStorageLimitChangeResponse.newBuilder() to construct.
  private PreviewStorageLimitChangeResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private PreviewStorageLimitChangeResponse() {
    error_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return net.bladewatch.app.grpc.v1.Storage.internal_static_bladewatch_v1_PreviewStorageLimitChangeResponse_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return net.bladewatch.app.grpc.v1.Storage.internal_static_bladewatch_v1_PreviewStorageLimitChangeResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return net.bladewatch.app.grpc.v1.Storage.internal_static_bladewatch_v1_PreviewStorageLimitChangeResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            net.bladewatch.app.grpc.v1.PreviewStorageLimitChangeResponse.class, net.bladewatch.app.grpc.v1.PreviewStorageLimitChangeResponse.Builder.class);
  }

  private int bitField0_;
  public static final int SUCCESS_FIELD_NUMBER = 1;
  private boolean success_ = false;
  /**
   * <code>bool success = 1 [json_name = "success"];</code>
   * @return The success.
   */
  @java.lang.Override
  public boolean getSuccess() {
    return success_;
  }

  public static final int ERROR_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object error_ = "";
  /**
   * <code>string error = 2 [json_name = "error"];</code>
   * @return The error.
   */
  @java.lang.Override
  public java.lang.String getError() {
    java.lang.Object ref = error_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      error_ = s;
      return s;
    }
  }
  /**
   * <code>string error = 2 [json_name = "error"];</code>
   * @return The bytes for error.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getErrorBytes() {
    java.lang.Object ref = error_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      error_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RECORDINGS_IMPACT_FIELD_NUMBER = 3;
  private net.bladewatch.app.grpc.v1.CleanupImpact recordingsImpact_;
  /**
   * <pre>
   * Present iff recordings_limit_mb was set in the request.
   * </pre>
   *
   * <code>.bladewatch.v1.CleanupImpact recordings_impact = 3 [json_name = "recordingsImpact"];</code>
   * @return Whether the recordingsImpact field is set.
   */
  @java.lang.Override
  public boolean hasRecordingsImpact() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * Present iff recordings_limit_mb was set in the request.
   * </pre>
   *
   * <code>.bladewatch.v1.CleanupImpact recordings_impact = 3 [json_name = "recordingsImpact"];</code>
   * @return The recordingsImpact.
   */
  @java.lang.Override
  public net.bladewatch.app.grpc.v1.CleanupImpact getRecordingsImpact() {
    return recordingsImpact_ == null ? net.bladewatch.app.grpc.v1.CleanupImpact.getDefaultInstance() : recordingsImpact_;
  }
  /**
   * <pre>
   * Present iff recordings_limit_mb was set in the request.
   * </pre>
   *
   * <code>.bladewatch.v1.CleanupImpact recordings_impact = 3 [json_name = "recordingsImpact"];</code>
   */
  @java.lang.Override
  public net.bladewatch.app.grpc.v1.CleanupImpactOrBuilder getRecordingsImpactOrBuilder() {
    return recordingsImpact_ == null ? net.bladewatch.app.grpc.v1.CleanupImpact.getDefaultInstance() : recordingsImpact_;
  }

  public static final int SURVEILLANCE_IMPACT_FIELD_NUMBER = 4;
  private net.bladewatch.app.grpc.v1.CleanupImpact surveillanceImpact_;
  /**
   * <pre>
   * Present iff surveillance_limit_mb was set in the request.
   * </pre>
   *
   * <code>.bladewatch.v1.CleanupImpact surveillance_impact = 4 [json_name = "surveillanceImpact"];</code>
   * @return Whether the surveillanceImpact field is set.
   */
  @java.lang.Override
  public boolean hasSurveillanceImpact() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * Present iff surveillance_limit_mb was set in the request.
   * </pre>
   *
   * <code>.bladewatch.v1.CleanupImpact surveillance_impact = 4 [json_name = "surveillanceImpact"];</code>
   * @return The surveillanceImpact.
   */
  @java.lang.Override
  public net.bladewatch.app.grpc.v1.CleanupImpact getSurveillanceImpact() {
    return surveillanceImpact_ == null ? net.bladewatch.app.grpc.v1.CleanupImpact.getDefaultInstance() : surveillanceImpact_;
  }
  /**
   * <pre>
   * Present iff surveillance_limit_mb was set in the request.
   * </pre>
   *
   * <code>.bladewatch.v1.CleanupImpact surveillance_impact = 4 [json_name = "surveillanceImpact"];</code>
   */
  @java.lang.Override
  public net.bladewatch.app.grpc.v1.CleanupImpactOrBuilder getSurveillanceImpactOrBuilder() {
    return surveillanceImpact_ == null ? net.bladewatch.app.grpc.v1.CleanupImpact.getDefaultInstance() : surveillanceImpact_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (success_ != false) {
      output.writeBool(1, success_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(error_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, error_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(3, getRecordingsImpact());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(4, getSurveillanceImpact());
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;
    if (success_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, success_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(error_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, error_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getRecordingsImpact());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getSurveillanceImpact());
    }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof net.bladewatch.app.grpc.v1.PreviewStorageLimitChangeResponse)) {
      return super.equals(obj);
    }
    net.bladewatch.app.grpc.v1.PreviewStorageLimitChangeResponse other = (net.bladewatch.app.grpc.v1.PreviewStorageLimitChangeResponse) obj;

    if (getSuccess()
        != other.getSuccess()) return false;
    if (!getError()
        .equals(other.getError())) return false;
    if (hasRecordingsImpact() != other.hasRecordingsImpact()) return false;
    if (hasRecordingsImpact()) {
      if (!getRecordingsImpact()
          .equals(other.getRecordingsImpact())) return false;
    }
    if (hasSurveillanceImpact() != other.hasSurveillanceImpact()) return false;
    if (hasSurveillanceImpact()) {
      if (!getSurveillanceImpact()
          .equals(other.getSurveillanceImpact())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SUCCESS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getSuccess());
    hash = (37 * hash) + ERROR_FIELD_NUMBER;
    hash = (53 * hash) + getError().hashCode();
    if (hasRecordingsImpact()) {
      hash = (37 * hash) + RECORDINGS_IMPACT_FIELD_NUMBER;
      hash = (53 * hash) + getRecordingsImpact().hashCode();
    }
    if (hasSurveillanceImpact()) {
      hash = (37 * hash) + SURVEILLANCE_IMPACT_FIELD_NUMBER;
      hash = (53 * hash) + getSurveillanceImpact().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static net.bladewatch.app.grpc.v1.PreviewStorageLimitChangeResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.bladewatch.app.grpc.v1.PreviewStorageLimitChangeResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.bladewatch.app.grpc.v1.PreviewStorageLimitChangeResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.bladewatch.app.grpc.v1.PreviewStorageLimitChangeResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.bladewatch.app.grpc.v1.PreviewStorageLimitChangeResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.bladewatch.app.grpc.v1.PreviewStorageLimitChangeResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.bladewatch.app.grpc.v1.PreviewStorageLimitChangeResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static net.bladewatch.app.grpc.v1.PreviewStorageLimitChangeResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static net.bladewatch.app.grpc.v1.PreviewStorageLimitChangeResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static net.bladewatch.app.grpc.v1.PreviewStorageLimitChangeResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static net.bladewatch.app.grpc.v1.PreviewStorageLimitChangeResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static net.bladewatch.app.grpc.v1.PreviewStorageLimitChangeResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(net.bladewatch.app.grpc.v1.PreviewStorageLimitChangeResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code bladewatch.v1.PreviewStorageLimitChangeResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:bladewatch.v1.PreviewStorageLimitChangeResponse)
      net.bladewatch.app.grpc.v1.PreviewStorageLimitChangeResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.bladewatch.app.grpc.v1.Storage.internal_static_bladewatch_v1_PreviewStorageLimitChangeResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.bladewatch.app.grpc.v1.Storage.internal_static_bladewatch_v1_PreviewStorageLimitChangeResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.bladewatch.app.grpc.v1.PreviewStorageLimitChangeResponse.class, net.bladewatch.app.grpc.v1.PreviewStorageLimitChangeResponse.Builder.class);
    }

    // Construct using net.bladewatch.app.grpc.v1.PreviewStorageLimitChangeResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetRecordingsImpactFieldBuilder();
        internalGetSurveillanceImpactFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      success_ = false;
      error_ = "";
      recordingsImpact_ = null;
      if (recordingsImpactBuilder_ != null) {
        recordingsImpactBuilder_.dispose();
        recordingsImpactBuilder_ = null;
      }
      surveillanceImpact_ = null;
      if (surveillanceImpactBuilder_ != null) {
        surveillanceImpactBuilder_.dispose();
        surveillanceImpactBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return net.bladewatch.app.grpc.v1.Storage.internal_static_bladewatch_v1_PreviewStorageLimitChangeResponse_descriptor;
    }

    @java.lang.Override
    public net.bladewatch.app.grpc.v1.PreviewStorageLimitChangeResponse getDefaultInstanceForType() {
      return net.bladewatch.app.grpc.v1.PreviewStorageLimitChangeResponse.getDefaultInstance();
    }

    @java.lang.Override
    public net.bladewatch.app.grpc.v1.PreviewStorageLimitChangeResponse build() {
      net.bladewatch.app.grpc.v1.PreviewStorageLimitChangeResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public net.bladewatch.app.grpc.v1.PreviewStorageLimitChangeResponse buildPartial() {
      net.bladewatch.app.grpc.v1.PreviewStorageLimitChangeResponse result = new net.bladewatch.app.grpc.v1.PreviewStorageLimitChangeResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(net.bladewatch.app.grpc.v1.PreviewStorageLimitChangeResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.success_ = success_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.error_ = error_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.recordingsImpact_ = recordingsImpactBuilder_ == null
            ? recordingsImpact_
            : recordingsImpactBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.surveillanceImpact_ = surveillanceImpactBuilder_ == null
            ? surveillanceImpact_
            : surveillanceImpactBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof net.bladewatch.app.grpc.v1.PreviewStorageLimitChangeResponse) {
        return mergeFrom((net.bladewatch.app.grpc.v1.PreviewStorageLimitChangeResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(net.bladewatch.app.grpc.v1.PreviewStorageLimitChangeResponse other) {
      if (other == net.bladewatch.app.grpc.v1.PreviewStorageLimitChangeResponse.getDefaultInstance()) return this;
      if (other.getSuccess() != false) {
        setSuccess(other.getSuccess());
      }
      if (!other.getError().isEmpty()) {
        error_ = other.error_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.hasRecordingsImpact()) {
        mergeRecordingsImpact(other.getRecordingsImpact());
      }
      if (other.hasSurveillanceImpact()) {
        mergeSurveillanceImpact(other.getSurveillanceImpact());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              success_ = input.readBool();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              error_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  internalGetRecordingsImpactFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              input.readMessage(
                  internalGetSurveillanceImpactFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private boolean success_ ;
    /**
     * <code>bool success = 1 [json_name = "success"];</code>
     * @return The success.
     */
    @java.lang.Override
    public boolean getSuccess() {
      return success_;
    }
    /**
     * <code>bool success = 1 [json_name = "success"];</code>
     * @param value The success to set.
     * @return This builder for chaining.
     */
    public Builder setSuccess(boolean value) {

      success_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>bool success = 1 [json_name = "success"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSuccess() {
      bitField0_ = (bitField0_ & ~0x00000001);
      success_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object error_ = "";
    /**
     * <code>string error = 2 [json_name = "error"];</code>
     * @return The error.
     */
    public java.lang.String getError() {
      java.lang.Object ref = error_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        error_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string error = 2 [json_name = "error"];</code>
     * @return The bytes for error.
     */
    public com.google.protobuf.ByteString
        getErrorBytes() {
      java.lang.Object ref = error_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        error_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string error = 2 [json_name = "error"];</code>
     * @param value The error to set.
     * @return This builder for chaining.
     */
    public Builder setError(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      error_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string error = 2 [json_name = "error"];</code>
     * @return This builder for chaining.
     */
    public Builder clearError() {
      error_ = getDefaultInstance().getError();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string error = 2 [json_name = "error"];</code>
     * @param value The bytes for error to set.
     * @return This builder for chaining.
     */
    public Builder setErrorBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      error_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private net.bladewatch.app.grpc.v1.CleanupImpact recordingsImpact_;
    private com.google.protobuf.SingleFieldBuilder<
        net.bladewatch.app.grpc.v1.CleanupImpact, net.bladewatch.app.grpc.v1.CleanupImpact.Builder, net.bladewatch.app.grpc.v1.CleanupImpactOrBuilder> recordingsImpactBuilder_;
    /**
     * <pre>
     * Present iff recordings_limit_mb was set in the request.
     * </pre>
     *
     * <code>.bladewatch.v1.CleanupImpact recordings_impact = 3 [json_name = "recordingsImpact"];</code>
     * @return Whether the recordingsImpact field is set.
     */
    public boolean hasRecordingsImpact() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * Present iff recordings_limit_mb was set in the request.
     * </pre>
     *
     * <code>.bladewatch.v1.CleanupImpact recordings_impact = 3 [json_name = "recordingsImpact"];</code>
     * @return The recordingsImpact.
     */
    public net.bladewatch.app.grpc.v1.CleanupImpact getRecordingsImpact() {
      if (recordingsImpactBuilder_ == null) {
        return recordingsImpact_ == null ? net.bladewatch.app.grpc.v1.CleanupImpact.getDefaultInstance() : recordingsImpact_;
      } else {
        return recordingsImpactBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Present iff recordings_limit_mb was set in the request.
     * </pre>
     *
     * <code>.bladewatch.v1.CleanupImpact recordings_impact = 3 [json_name = "recordingsImpact"];</code>
     */
    public Builder setRecordingsImpact(net.bladewatch.app.grpc.v1.CleanupImpact value) {
      if (recordingsImpactBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        recordingsImpact_ = value;
      } else {
        recordingsImpactBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Present iff recordings_limit_mb was set in the request.
     * </pre>
     *
     * <code>.bladewatch.v1.CleanupImpact recordings_impact = 3 [json_name = "recordingsImpact"];</code>
     */
    public Builder setRecordingsImpact(
        net.bladewatch.app.grpc.v1.CleanupImpact.Builder builderForValue) {
      if (recordingsImpactBuilder_ == null) {
        recordingsImpact_ = builderForValue.build();
      } else {
        recordingsImpactBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Present iff recordings_limit_mb was set in the request.
     * </pre>
     *
     * <code>.bladewatch.v1.CleanupImpact recordings_impact = 3 [json_name = "recordingsImpact"];</code>
     */
    public Builder mergeRecordingsImpact(net.bladewatch.app.grpc.v1.CleanupImpact value) {
      if (recordingsImpactBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          recordingsImpact_ != null &&
          recordingsImpact_ != net.bladewatch.app.grpc.v1.CleanupImpact.getDefaultInstance()) {
          getRecordingsImpactBuilder().mergeFrom(value);
        } else {
          recordingsImpact_ = value;
        }
      } else {
        recordingsImpactBuilder_.mergeFrom(value);
      }
      if (recordingsImpact_ != null) {
        bitField0_ |= 0x00000004;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * Present iff recordings_limit_mb was set in the request.
     * </pre>
     *
     * <code>.bladewatch.v1.CleanupImpact recordings_impact = 3 [json_name = "recordingsImpact"];</code>
     */
    public Builder clearRecordingsImpact() {
      bitField0_ = (bitField0_ & ~0x00000004);
      recordingsImpact_ = null;
      if (recordingsImpactBuilder_ != null) {
        recordingsImpactBuilder_.dispose();
        recordingsImpactBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Present iff recordings_limit_mb was set in the request.
     * </pre>
     *
     * <code>.bladewatch.v1.CleanupImpact recordings_impact = 3 [json_name = "recordingsImpact"];</code>
     */
    public net.bladewatch.app.grpc.v1.CleanupImpact.Builder getRecordingsImpactBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return internalGetRecordingsImpactFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Present iff recordings_limit_mb was set in the request.
     * </pre>
     *
     * <code>.bladewatch.v1.CleanupImpact recordings_impact = 3 [json_name = "recordingsImpact"];</code>
     */
    public net.bladewatch.app.grpc.v1.CleanupImpactOrBuilder getRecordingsImpactOrBuilder() {
      if (recordingsImpactBuilder_ != null) {
        return recordingsImpactBuilder_.getMessageOrBuilder();
      } else {
        return recordingsImpact_ == null ?
            net.bladewatch.app.grpc.v1.CleanupImpact.getDefaultInstance() : recordingsImpact_;
      }
    }
    /**
     * <pre>
     * Present iff recordings_limit_mb was set in the request.
     * </pre>
     *
     * <code>.bladewatch.v1.CleanupImpact recordings_impact = 3 [json_name = "recordingsImpact"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        net.bladewatch.app.grpc.v1.CleanupImpact, net.bladewatch.app.grpc.v1.CleanupImpact.Builder, net.bladewatch.app.grpc.v1.CleanupImpactOrBuilder> 
        internalGetRecordingsImpactFieldBuilder() {
      if (recordingsImpactBuilder_ == null) {
        recordingsImpactBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            net.bladewatch.app.grpc.v1.CleanupImpact, net.bladewatch.app.grpc.v1.CleanupImpact.Builder, net.bladewatch.app.grpc.v1.CleanupImpactOrBuilder>(
                getRecordingsImpact(),
                getParentForChildren(),
                isClean());
        recordingsImpact_ = null;
      }
      return recordingsImpactBuilder_;
    }

    private net.bladewatch.app.grpc.v1.CleanupImpact surveillanceImpact_;
    private com.google.protobuf.SingleFieldBuilder<
        net.bladewatch.app.grpc.v1.CleanupImpact, net.bladewatch.app.grpc.v1.CleanupImpact.Builder, net.bladewatch.app.grpc.v1.CleanupImpactOrBuilder> surveillanceImpactBuilder_;
    /**
     * <pre>
     * Present iff surveillance_limit_mb was set in the request.
     * </pre>
     *
     * <code>.bladewatch.v1.CleanupImpact surveillance_impact = 4 [json_name = "surveillanceImpact"];</code>
     * @return Whether the surveillanceImpact field is set.
     */
    public boolean hasSurveillanceImpact() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     * Present iff surveillance_limit_mb was set in the request.
     * </pre>
     *
     * <code>.bladewatch.v1.CleanupImpact surveillance_impact = 4 [json_name = "surveillanceImpact"];</code>
     * @return The surveillanceImpact.
     */
    public net.bladewatch.app.grpc.v1.CleanupImpact getSurveillanceImpact() {
      if (surveillanceImpactBuilder_ == null) {
        return surveillanceImpact_ == null ? net.bladewatch.app.grpc.v1.CleanupImpact.getDefaultInstance() : surveillanceImpact_;
      } else {
        return surveillanceImpactBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Present iff surveillance_limit_mb was set in the request.
     * </pre>
     *
     * <code>.bladewatch.v1.CleanupImpact surveillance_impact = 4 [json_name = "surveillanceImpact"];</code>
     */
    public Builder setSurveillanceImpact(net.bladewatch.app.grpc.v1.CleanupImpact value) {
      if (surveillanceImpactBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        surveillanceImpact_ = value;
      } else {
        surveillanceImpactBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Present iff surveillance_limit_mb was set in the request.
     * </pre>
     *
     * <code>.bladewatch.v1.CleanupImpact surveillance_impact = 4 [json_name = "surveillanceImpact"];</code>
     */
    public Builder setSurveillanceImpact(
        net.bladewatch.app.grpc.v1.CleanupImpact.Builder builderForValue) {
      if (surveillanceImpactBuilder_ == null) {
        surveillanceImpact_ = builderForValue.build();
      } else {
        surveillanceImpactBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Present iff surveillance_limit_mb was set in the request.
     * </pre>
     *
     * <code>.bladewatch.v1.CleanupImpact surveillance_impact = 4 [json_name = "surveillanceImpact"];</code>
     */
    public Builder mergeSurveillanceImpact(net.bladewatch.app.grpc.v1.CleanupImpact value) {
      if (surveillanceImpactBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0) &&
          surveillanceImpact_ != null &&
          surveillanceImpact_ != net.bladewatch.app.grpc.v1.CleanupImpact.getDefaultInstance()) {
          getSurveillanceImpactBuilder().mergeFrom(value);
        } else {
          surveillanceImpact_ = value;
        }
      } else {
        surveillanceImpactBuilder_.mergeFrom(value);
      }
      if (surveillanceImpact_ != null) {
        bitField0_ |= 0x00000008;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * Present iff surveillance_limit_mb was set in the request.
     * </pre>
     *
     * <code>.bladewatch.v1.CleanupImpact surveillance_impact = 4 [json_name = "surveillanceImpact"];</code>
     */
    public Builder clearSurveillanceImpact() {
      bitField0_ = (bitField0_ & ~0x00000008);
      surveillanceImpact_ = null;
      if (surveillanceImpactBuilder_ != null) {
        surveillanceImpactBuilder_.dispose();
        surveillanceImpactBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Present iff surveillance_limit_mb was set in the request.
     * </pre>
     *
     * <code>.bladewatch.v1.CleanupImpact surveillance_impact = 4 [json_name = "surveillanceImpact"];</code>
     */
    public net.bladewatch.app.grpc.v1.CleanupImpact.Builder getSurveillanceImpactBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return internalGetSurveillanceImpactFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Present iff surveillance_limit_mb was set in the request.
     * </pre>
     *
     * <code>.bladewatch.v1.CleanupImpact surveillance_impact = 4 [json_name = "surveillanceImpact"];</code>
     */
    public net.bladewatch.app.grpc.v1.CleanupImpactOrBuilder getSurveillanceImpactOrBuilder() {
      if (surveillanceImpactBuilder_ != null) {
        return surveillanceImpactBuilder_.getMessageOrBuilder();
      } else {
        return surveillanceImpact_ == null ?
            net.bladewatch.app.grpc.v1.CleanupImpact.getDefaultInstance() : surveillanceImpact_;
      }
    }
    /**
     * <pre>
     * Present iff surveillance_limit_mb was set in the request.
     * </pre>
     *
     * <code>.bladewatch.v1.CleanupImpact surveillance_impact = 4 [json_name = "surveillanceImpact"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        net.bladewatch.app.grpc.v1.CleanupImpact, net.bladewatch.app.grpc.v1.CleanupImpact.Builder, net.bladewatch.app.grpc.v1.CleanupImpactOrBuilder> 
        internalGetSurveillanceImpactFieldBuilder() {
      if (surveillanceImpactBuilder_ == null) {
        surveillanceImpactBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            net.bladewatch.app.grpc.v1.CleanupImpact, net.bladewatch.app.grpc.v1.CleanupImpact.Builder, net.bladewatch.app.grpc.v1.CleanupImpactOrBuilder>(
                getSurveillanceImpact(),
                getParentForChildren(),
                isClean());
        surveillanceImpact_ = null;
      }
      return surveillanceImpactBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:bladewatch.v1.PreviewStorageLimitChangeResponse)
  }

  // @@protoc_insertion_point(class_scope:bladewatch.v1.PreviewStorageLimitChangeResponse)
  private static final net.bladewatch.app.grpc.v1.PreviewStorageLimitChangeResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new net.bladewatch.app.grpc.v1.PreviewStorageLimitChangeResponse();
  }

  public static net.bladewatch.app.grpc.v1.PreviewStorageLimitChangeResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PreviewStorageLimitChangeResponse>
      PARSER = new com.google.protobuf.AbstractParser<PreviewStorageLimitChangeResponse>() {
    @java.lang.Override
    public PreviewStorageLimitChangeResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<PreviewStorageLimitChangeResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PreviewStorageLimitChangeResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public net.bladewatch.app.grpc.v1.PreviewStorageLimitChangeResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

