// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bladewatch/v1/storage.proto
// Protobuf Java Version: 4.35.0

package net.bladewatch.app.grpc.v1;

@com.google.protobuf.Generated
public interface PreviewStorageLimitChangeResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bladewatch.v1.PreviewStorageLimitChangeResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1 [json_name = "success"];</code>
   * @return The success.
   */
  boolean getSuccess();

  /**
   * <code>string error = 2 [json_name = "error"];</code>
   * @return The error.
   */
  java.lang.String getError();
  /**
   * <code>string error = 2 [json_name = "error"];</code>
   * @return The bytes for error.
   */
  com.google.protobuf.ByteString
      getErrorBytes();

  /**
   * <pre>
   * Present iff recordings_limit_mb was set in the request.
   * </pre>
   *
   * <code>.bladewatch.v1.CleanupImpact recordings_impact = 3 [json_name = "recordingsImpact"];</code>
   * @return Whether the recordingsImpact field is set.
   */
  boolean hasRecordingsImpact();
  /**
   * <pre>
   * Present iff recordings_limit_mb was set in the request.
   * </pre>
   *
   * <code>.bladewatch.v1.CleanupImpact recordings_impact = 3 [json_name = "recordingsImpact"];</code>
   * @return The recordingsImpact.
   */
  net.bladewatch.app.grpc.v1.CleanupImpact getRecordingsImpact();
  /**
   * <pre>
   * Present iff recordings_limit_mb was set in the request.
   * </pre>
   *
   * <code>.bladewatch.v1.CleanupImpact recordings_impact = 3 [json_name = "recordingsImpact"];</code>
   */
  net.bladewatch.app.grpc.v1.CleanupImpactOrBuilder getRecordingsImpactOrBuilder();

  /**
   * <pre>
   * Present iff surveillance_limit_mb was set in the request.
   * </pre>
   *
   * <code>.bladewatch.v1.CleanupImpact surveillance_impact = 4 [json_name = "surveillanceImpact"];</code>
   * @return Whether the surveillanceImpact field is set.
   */
  boolean hasSurveillanceImpact();
  /**
   * <pre>
   * Present iff surveillance_limit_mb was set in the request.
   * </pre>
   *
   * <code>.bladewatch.v1.CleanupImpact surveillance_impact = 4 [json_name = "surveillanceImpact"];</code>
   * @return The surveillanceImpact.
   */
  net.bladewatch.app.grpc.v1.CleanupImpact getSurveillanceImpact();
  /**
   * <pre>
   * Present iff surveillance_limit_mb was set in the request.
   * </pre>
   *
   * <code>.bladewatch.v1.CleanupImpact surveillance_impact = 4 [json_name = "surveillanceImpact"];</code>
   */
  net.bladewatch.app.grpc.v1.CleanupImpactOrBuilder getSurveillanceImpactOrBuilder();
}
