// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bladewatch/v1/surveillance.proto
// Protobuf Java Version: 4.35.0

package net.bladewatch.app.grpc.v1;

@com.google.protobuf.Generated
public interface RoiPolygonOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bladewatch.v1.RoiPolygon)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .bladewatch.v1.RoiPoint points = 1 [json_name = "points"];</code>
   */
  java.util.List<net.bladewatch.app.grpc.v1.RoiPoint> 
      getPointsList();
  /**
   * <code>repeated .bladewatch.v1.RoiPoint points = 1 [json_name = "points"];</code>
   */
  net.bladewatch.app.grpc.v1.RoiPoint getPoints(int index);
  /**
   * <code>repeated .bladewatch.v1.RoiPoint points = 1 [json_name = "points"];</code>
   */
  int getPointsCount();
  /**
   * <code>repeated .bladewatch.v1.RoiPoint points = 1 [json_name = "points"];</code>
   */
  java.util.List<? extends net.bladewatch.app.grpc.v1.RoiPointOrBuilder> 
      getPointsOrBuilderList();
  /**
   * <code>repeated .bladewatch.v1.RoiPoint points = 1 [json_name = "points"];</code>
   */
  net.bladewatch.app.grpc.v1.RoiPointOrBuilder getPointsOrBuilder(
      int index);
}
