// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bladewatch/v1/trips.proto
// Protobuf Java Version: 4.35.0

package net.bladewatch.app.grpc.v1;

@com.google.protobuf.Generated
public interface SetConfigRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bladewatch.v1.SetConfigRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool enabled = 1 [json_name = "enabled"];</code>
   * @return The enabled.
   */
  boolean getEnabled();

  /**
   * <code>bool has_enabled = 2 [json_name = "hasEnabled"];</code>
   * @return The hasEnabled.
   */
  boolean getHasEnabled();

  /**
   * <code>double electricity_rate = 3 [json_name = "electricityRate"];</code>
   * @return The electricityRate.
   */
  double getElectricityRate();

  /**
   * <code>bool has_electricity_rate = 4 [json_name = "hasElectricityRate"];</code>
   * @return The hasElectricityRate.
   */
  boolean getHasElectricityRate();

  /**
   * <code>string currency = 5 [json_name = "currency"];</code>
   * @return The currency.
   */
  java.lang.String getCurrency();
  /**
   * <code>string currency = 5 [json_name = "currency"];</code>
   * @return The bytes for currency.
   */
  com.google.protobuf.ByteString
      getCurrencyBytes();

  /**
   * <code>string distance_unit = 6 [json_name = "distanceUnit"];</code>
   * @return The distanceUnit.
   */
  java.lang.String getDistanceUnit();
  /**
   * <code>string distance_unit = 6 [json_name = "distanceUnit"];</code>
   * @return The bytes for distanceUnit.
   */
  com.google.protobuf.ByteString
      getDistanceUnitBytes();

  /**
   * <pre>
   * PHEV pricing (BladeWatch-9uu6). New field numbers only, so a client built against the
   * old schema still parses this message.
   *
   * Each value carries an explicit has_* companion, matching the pattern above. proto3 omits
   * default scalars on the wire, so without the companion a deliberate 0 — which means "not
   * configured" for both of these — would be indistinguishable from "field not sent", and the
   * daemon would keep the previous value instead of clearing it.
   * </pre>
   *
   * <code>double fuel_price_per_l = 7 [json_name = "fuelPricePerL"];</code>
   * @return The fuelPricePerL.
   */
  double getFuelPricePerL();

  /**
   * <code>bool has_fuel_price_per_l = 8 [json_name = "hasFuelPricePerL"];</code>
   * @return The hasFuelPricePerL.
   */
  boolean getHasFuelPricePerL();

  /**
   * <code>double fuel_tank_capacity_l = 9 [json_name = "fuelTankCapacityL"];</code>
   * @return The fuelTankCapacityL.
   */
  double getFuelTankCapacityL();

  /**
   * <code>bool has_fuel_tank_capacity_l = 10 [json_name = "hasFuelTankCapacityL"];</code>
   * @return The hasFuelTankCapacityL.
   */
  boolean getHasFuelTankCapacityL();
}
