// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bladewatch/v1/vehicle.proto
// Protobuf Java Version: 4.35.0

package net.bladewatch.app.grpc.v1;

@com.google.protobuf.Generated
public interface SetMediaVolumeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bladewatch.v1.SetMediaVolumeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * One of: "set", "step_up", "step_down", "mute", "unmute".
   * </pre>
   *
   * <code>string action = 1 [json_name = "action"];</code>
   * @return The action.
   */
  java.lang.String getAction();
  /**
   * <pre>
   * One of: "set", "step_up", "step_down", "mute", "unmute".
   * </pre>
   *
   * <code>string action = 1 [json_name = "action"];</code>
   * @return The bytes for action.
   */
  com.google.protobuf.ByteString
      getActionBytes();

  /**
   * <pre>
   * Required (0-100) when action == "set"; ignored for every other action.
   * </pre>
   *
   * <code>optional int32 percent = 2 [json_name = "percent"];</code>
   * @return Whether the percent field is set.
   */
  boolean hasPercent();
  /**
   * <pre>
   * Required (0-100) when action == "set"; ignored for every other action.
   * </pre>
   *
   * <code>optional int32 percent = 2 [json_name = "percent"];</code>
   * @return The percent.
   */
  int getPercent();
}
