// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bladewatch/v1/settings.proto
// Protobuf Java Version: 4.35.0

package net.bladewatch.app.grpc.v1;

@com.google.protobuf.Generated
public interface SetSettingsLockRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bladewatch.v1.SetSettingsLockRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * false clears the PIN and disables the lock.
   * </pre>
   *
   * <code>bool enabled = 1 [json_name = "enabled"];</code>
   * @return The enabled.
   */
  boolean getEnabled();

  /**
   * <pre>
   * Exactly 6 ASCII digits when enabled. Ignored when disabled.
   * </pre>
   *
   * <code>string pin = 2 [json_name = "pin"];</code>
   * @return The pin.
   */
  java.lang.String getPin();
  /**
   * <pre>
   * Exactly 6 ASCII digits when enabled. Ignored when disabled.
   * </pre>
   *
   * <code>string pin = 2 [json_name = "pin"];</code>
   * @return The bytes for pin.
   */
  com.google.protobuf.ByteString
      getPinBytes();
}
