// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bladewatch/v1/settings.proto
// Protobuf Java Version: 4.35.0

package net.bladewatch.app.grpc.v1;

@com.google.protobuf.Generated
public interface SetStatusOverlayRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bladewatch.v1.SetStatusOverlayRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool camera_visible = 1 [json_name = "cameraVisible"];</code>
   * @return The cameraVisible.
   */
  boolean getCameraVisible();

  /**
   * <code>bool set_camera_visible = 2 [json_name = "setCameraVisible"];</code>
   * @return The setCameraVisible.
   */
  boolean getSetCameraVisible();

  /**
   * <code>bool trip_visible = 3 [json_name = "tripVisible"];</code>
   * @return The tripVisible.
   */
  boolean getTripVisible();

  /**
   * <code>bool set_trip_visible = 4 [json_name = "setTripVisible"];</code>
   * @return The setTripVisible.
   */
  boolean getSetTripVisible();
}
