// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bladewatch/v1/settings.proto
// Protobuf Java Version: 4.35.0

package net.bladewatch.app.grpc.v1;

@com.google.protobuf.Generated
public interface SetTelemetryOverlayFieldsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bladewatch.v1.SetTelemetryOverlayFieldsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * One of "continuous", "surveillance", "proximity". An unknown type is a bad request.
   * </pre>
   *
   * <code>string type = 1 [json_name = "type"];</code>
   * @return The type.
   */
  java.lang.String getType();
  /**
   * <pre>
   * One of "continuous", "surveillance", "proximity". An unknown type is a bad request.
   * </pre>
   *
   * <code>string type = 1 [json_name = "type"];</code>
   * @return The bytes for type.
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <pre>
   * OverlayField enum names. An unknown name is dropped by the resolver, not rejected here,
   * mirroring how a persisted config file is already treated by the reader.
   * </pre>
   *
   * <code>repeated string fields = 2 [json_name = "fields"];</code>
   * @return A list containing the fields.
   */
  java.util.List<java.lang.String>
      getFieldsList();
  /**
   * <pre>
   * OverlayField enum names. An unknown name is dropped by the resolver, not rejected here,
   * mirroring how a persisted config file is already treated by the reader.
   * </pre>
   *
   * <code>repeated string fields = 2 [json_name = "fields"];</code>
   * @return The count of fields.
   */
  int getFieldsCount();
  /**
   * <pre>
   * OverlayField enum names. An unknown name is dropped by the resolver, not rejected here,
   * mirroring how a persisted config file is already treated by the reader.
   * </pre>
   *
   * <code>repeated string fields = 2 [json_name = "fields"];</code>
   * @param index The index of the element to return.
   * @return The fields at the given index.
   */
  java.lang.String getFields(int index);
  /**
   * <pre>
   * OverlayField enum names. An unknown name is dropped by the resolver, not rejected here,
   * mirroring how a persisted config file is already treated by the reader.
   * </pre>
   *
   * <code>repeated string fields = 2 [json_name = "fields"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the fields at the given index.
   */
  com.google.protobuf.ByteString
      getFieldsBytes(int index);
}
