// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bladewatch/v1/settings.proto
// Protobuf Java Version: 4.35.0

package net.bladewatch.app.grpc.v1;

@com.google.protobuf.Generated
public final class Settings extends com.google.protobuf.GeneratedFile {
  private Settings() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 0,
      /* suffix= */ "",
      "Settings");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_QualityTierInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_QualityTierInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_ActiveRecordingEstimate_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_ActiveRecordingEstimate_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_GetQualityRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_GetQualityRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_GetQualityResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_GetQualityResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_GetQualityResponse_RecordingQualityOptionsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_GetQualityResponse_RecordingQualityOptionsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_GetQualityResponse_CodecOptionsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_GetQualityResponse_CodecOptionsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_GetQualityResponse_FpsOptionsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_GetQualityResponse_FpsOptionsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_SetQualityRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_SetQualityRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_SetQualityResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_SetQualityResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_GetAppearanceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_GetAppearanceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_GetAppearanceResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_GetAppearanceResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_SetAppearanceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_SetAppearanceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_SetAppearanceResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_SetAppearanceResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_GetLocaleRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_GetLocaleRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_GetLocaleResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_GetLocaleResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_GetLocaleResponse_SupportedEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_GetLocaleResponse_SupportedEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_SetLocaleRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_SetLocaleRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_SetLocaleResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_SetLocaleResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_SetRecordingModeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_SetRecordingModeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_SetRecordingModeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_SetRecordingModeResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_GetStatusOverlayRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_GetStatusOverlayRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_GetStatusOverlayResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_GetStatusOverlayResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_SetStatusOverlayRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_SetStatusOverlayRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_SetStatusOverlayResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_SetStatusOverlayResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_GetTelemetryOverlayFieldsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_GetTelemetryOverlayFieldsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_GetTelemetryOverlayFieldsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_GetTelemetryOverlayFieldsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_GetTelemetryOverlayFieldsResponse_SelectionsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_GetTelemetryOverlayFieldsResponse_SelectionsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_FieldList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_FieldList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_SetTelemetryOverlayFieldsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_SetTelemetryOverlayFieldsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_SetTelemetryOverlayFieldsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_SetTelemetryOverlayFieldsResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034bladewatch/v1/settings.proto\022\rbladewat" +
      "ch.v1\"\353\001\n\017QualityTierInfo\022!\n\014display_nam" +
      "e\030\001 \001(\tR\013displayName\022\037\n\013bitrate_bps\030\002 \001(" +
      "\003R\nbitrateBps\022!\n\014bitrate_mbps\030\003 \001(\001R\013bit" +
      "rateMbps\022\"\n\rmb_per_minute\030\004 \001(\001R\013mbPerMi" +
      "nute\022\036\n\013gb_per_hour\030\005 \001(\001R\tgbPerHour\022-\n\022" +
      "quality_equivalent\030\006 \001(\tR\021qualityEquival" +
      "ent\"\366\001\n\027ActiveRecordingEstimate\022!\n\014bitra" +
      "te_mbps\030\001 \001(\001R\013bitrateMbps\022\"\n\rmb_per_min" +
      "ute\030\002 \001(\001R\013mbPerMinute\022\037\n\014mb_per_2_min\030\003" +
      " \001(\001R\tmbPer2Min\022\036\n\013gb_per_hour\030\004 \001(\001R\tgb" +
      "PerHour\022$\n\016minutes_per_gb\030\005 \001(\005R\014minutes" +
      "PerGb\022-\n\022quality_equivalent\030\006 \001(\tR\021quali" +
      "tyEquivalent\"\023\n\021GetQualityRequest\"\244\007\n\022Ge" +
      "tQualityResponse\022\030\n\007success\030\001 \001(\010R\007succe" +
      "ss\022+\n\021recording_quality\030\002 \001(\tR\020recording" +
      "Quality\022\035\n\005codec\030\003 \001(\tR\016recordingCodec\022\026" +
      "\n\003fps\030\004 \001(\005R\tcameraFps\022z\n\031recording_qual" +
      "ity_options\030\005 \003(\0132>.bladewatch.v1.GetQua" +
      "lityResponse.RecordingQualityOptionsEntr" +
      "yR\027recordingQualityOptions\022b\n\031active_rec" +
      "ording_estimate\030\006 \001(\0132&.bladewatch.v1.Ac" +
      "tiveRecordingEstimateR\027activeRecordingEs" +
      "timate\022X\n\rcodec_options\030\007 \003(\01323.bladewat" +
      "ch.v1.GetQualityResponse.CodecOptionsEnt" +
      "ryR\014codecOptions\022R\n\013fps_options\030\010 \003(\01321." +
      "bladewatch.v1.GetQualityResponse.FpsOpti" +
      "onsEntryR\nfpsOptions\022+\n\021native_resolutio" +
      "n\030\t \001(\tR\020nativeResolution\022:\n\031recording_s" +
      "egment_minutes\030\n \001(\005R\027recordingSegmentMi" +
      "nutes\022-\n\022recording_priority\030\013 \001(\tR\021recor" +
      "dingPriority\032j\n\034RecordingQualityOptionsE" +
      "ntry\022\020\n\003key\030\001 \001(\tR\003key\0224\n\005value\030\002 \001(\0132\036." +
      "bladewatch.v1.QualityTierInfoR\005value:\0028\001" +
      "\032?\n\021CodecOptionsEntry\022\020\n\003key\030\001 \001(\tR\003key\022" +
      "\024\n\005value\030\002 \001(\tR\005value:\0028\001\032=\n\017FpsOptionsE" +
      "ntry\022\020\n\003key\030\001 \001(\tR\003key\022\024\n\005value\030\002 \001(\tR\005v" +
      "alue:\0028\001\"\200\002\n\021SetQualityRequest\022+\n\021record" +
      "ing_quality\030\001 \001(\tR\020recordingQuality\022\024\n\005c" +
      "odec\030\002 \001(\tR\005codec\022+\n\021streaming_quality\030\003" +
      " \001(\tR\020streamingQuality\022\020\n\003fps\030\004 \001(\005R\003fps" +
      "\022:\n\031recording_segment_minutes\030\005 \001(\005R\027rec" +
      "ordingSegmentMinutes\022-\n\022recording_priori" +
      "ty\030\006 \001(\tR\021recordingPriority\"\252\001\n\022SetQuali" +
      "tyResponse\022\030\n\007success\030\001 \001(\010R\007success\022+\n\021" +
      "recording_quality\030\002 \001(\tR\020recordingQualit" +
      "y\022\035\n\005codec\030\003 \001(\tR\016recordingCodec\022\030\n\007mess" +
      "age\030\004 \001(\tR\007message\022\024\n\005error\030\005 \001(\tR\005error" +
      "\"\026\n\024GetAppearanceRequest\"_\n\025GetAppearanc" +
      "eResponse\022\030\n\007success\030\001 \001(\010R\007success\022\024\n\005t" +
      "heme\030\002 \001(\tR\005theme\022\026\n\006locale\030\003 \001(\tR\006local" +
      "e\"D\n\024SetAppearanceRequest\022\024\n\005theme\030\001 \001(\t" +
      "R\005theme\022\026\n\006locale\030\002 \001(\tR\006locale\"u\n\025SetAp" +
      "pearanceResponse\022\030\n\007success\030\001 \001(\010R\007succe" +
      "ss\022\024\n\005theme\030\002 \001(\tR\005theme\022\026\n\006locale\030\003 \001(\t" +
      "R\006locale\022\024\n\005error\030\004 \001(\tR\005error\"\022\n\020GetLoc" +
      "aleRequest\"\264\001\n\021GetLocaleResponse\022\022\n\004lang" +
      "\030\001 \001(\tR\004lang\022M\n\tsupported\030\002 \003(\0132/.bladew" +
      "atch.v1.GetLocaleResponse.SupportedEntry" +
      "R\tsupported\032<\n\016SupportedEntry\022\020\n\003key\030\001 \001" +
      "(\tR\003key\022\024\n\005value\030\002 \001(\010R\005value:\0028\001\"&\n\020Set" +
      "LocaleRequest\022\022\n\004lang\030\001 \001(\tR\004lang\"\'\n\021Set" +
      "LocaleResponse\022\022\n\004lang\030\001 \001(\tR\004lang\"-\n\027Se" +
      "tRecordingModeRequest\022\022\n\004mode\030\001 \001(\tR\004mod" +
      "e\"^\n\030SetRecordingModeResponse\022\030\n\007success" +
      "\030\001 \001(\010R\007success\022\022\n\004mode\030\002 \001(\tR\004mode\022\024\n\005e" +
      "rror\030\003 \001(\tR\005error\"\031\n\027GetStatusOverlayReq" +
      "uest\"~\n\030GetStatusOverlayResponse\022\030\n\007succ" +
      "ess\030\001 \001(\010R\007success\022%\n\016camera_visible\030\002 \001" +
      "(\010R\rcameraVisible\022!\n\014trip_visible\030\003 \001(\010R" +
      "\013tripVisible\"\273\001\n\027SetStatusOverlayRequest" +
      "\022%\n\016camera_visible\030\001 \001(\010R\rcameraVisible\022" +
      ",\n\022set_camera_visible\030\002 \001(\010R\020setCameraVi" +
      "sible\022!\n\014trip_visible\030\003 \001(\010R\013tripVisible" +
      "\022(\n\020set_trip_visible\030\004 \001(\010R\016setTripVisib" +
      "le\"\224\001\n\030SetStatusOverlayResponse\022\030\n\007succe" +
      "ss\030\001 \001(\010R\007success\022%\n\016camera_visible\030\002 \001(" +
      "\010R\rcameraVisible\022!\n\014trip_visible\030\003 \001(\010R\013" +
      "tripVisible\022\024\n\005error\030\004 \001(\tR\005error\"\"\n Get" +
      "TelemetryOverlayFieldsRequest\"\243\002\n!GetTel" +
      "emetryOverlayFieldsResponse\022\030\n\007success\030\001" +
      " \001(\010R\007success\022)\n\020available_fields\030\002 \003(\tR" +
      "\017availableFields\022`\n\nselections\030\003 \003(\0132@.b" +
      "ladewatch.v1.GetTelemetryOverlayFieldsRe" +
      "sponse.SelectionsEntryR\nselections\032W\n\017Se" +
      "lectionsEntry\022\020\n\003key\030\001 \001(\tR\003key\022.\n\005value" +
      "\030\002 \001(\0132\030.bladewatch.v1.FieldListR\005value:" +
      "\0028\001\"#\n\tFieldList\022\026\n\006fields\030\001 \003(\tR\006fields" +
      "\"N\n SetTelemetryOverlayFieldsRequest\022\022\n\004" +
      "type\030\001 \001(\tR\004type\022\026\n\006fields\030\002 \003(\tR\006fields" +
      "\"S\n!SetTelemetryOverlayFieldsResponse\022\030\n" +
      "\007success\030\001 \001(\010R\007success\022\024\n\005error\030\002 \001(\tR\005" +
      "error*\354\001\n\024RecordingQualityTier\022&\n\"RECORD" +
      "ING_QUALITY_TIER_UNSPECIFIED\020\000\022\"\n\036RECORD" +
      "ING_QUALITY_TIER_ECONOMY\020\001\022#\n\037RECORDING_" +
      "QUALITY_TIER_STANDARD\020\002\022\037\n\033RECORDING_QUA" +
      "LITY_TIER_HIGH\020\003\022\"\n\036RECORDING_QUALITY_TI" +
      "ER_PREMIUM\020\004\022\036\n\032RECORDING_QUALITY_TIER_M" +
      "AX\020\005*U\n\nVideoCodec\022\033\n\027VIDEO_CODEC_UNSPEC" +
      "IFIED\020\000\022\024\n\020VIDEO_CODEC_H264\020\001\022\024\n\020VIDEO_C" +
      "ODEC_H265\020\002*b\n\010AppTheme\022\031\n\025APP_THEME_UNS" +
      "PECIFIED\020\000\022\022\n\016APP_THEME_DARK\020\001\022\023\n\017APP_TH" +
      "EME_LIGHT\020\002\022\022\n\016APP_THEME_AUTO\020\0032\276\010\n\017Sett" +
      "ingsService\022Q\n\nGetQuality\022 .bladewatch.v" +
      "1.GetQualityRequest\032!.bladewatch.v1.GetQ" +
      "ualityResponse\022Q\n\nSetQuality\022 .bladewatc" +
      "h.v1.SetQualityRequest\032!.bladewatch.v1.S" +
      "etQualityResponse\022Z\n\rGetAppearance\022#.bla" +
      "dewatch.v1.GetAppearanceRequest\032$.bladew" +
      "atch.v1.GetAppearanceResponse\022Z\n\rSetAppe" +
      "arance\022#.bladewatch.v1.SetAppearanceRequ" +
      "est\032$.bladewatch.v1.SetAppearanceRespons" +
      "e\022N\n\tGetLocale\022\037.bladewatch.v1.GetLocale" +
      "Request\032 .bladewatch.v1.GetLocaleRespons" +
      "e\022N\n\tSetLocale\022\037.bladewatch.v1.SetLocale" +
      "Request\032 .bladewatch.v1.SetLocaleRespons" +
      "e\022c\n\020SetRecordingMode\022&.bladewatch.v1.Se" +
      "tRecordingModeRequest\032\'.bladewatch.v1.Se" +
      "tRecordingModeResponse\022c\n\020GetStatusOverl" +
      "ay\022&.bladewatch.v1.GetStatusOverlayReque" +
      "st\032\'.bladewatch.v1.GetStatusOverlayRespo" +
      "nse\022c\n\020SetStatusOverlay\022&.bladewatch.v1." +
      "SetStatusOverlayRequest\032\'.bladewatch.v1." +
      "SetStatusOverlayResponse\022~\n\031GetTelemetry" +
      "OverlayFields\022/.bladewatch.v1.GetTelemet" +
      "ryOverlayFieldsRequest\0320.bladewatch.v1.G" +
      "etTelemetryOverlayFieldsResponse\022~\n\031SetT" +
      "elemetryOverlayFields\022/.bladewatch.v1.Se" +
      "tTelemetryOverlayFieldsRequest\0320.bladewa" +
      "tch.v1.SetTelemetryOverlayFieldsResponse" +
      "B\036\n\032net.bladewatch.app.grpc.v1P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_bladewatch_v1_QualityTierInfo_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_bladewatch_v1_QualityTierInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_QualityTierInfo_descriptor,
        new java.lang.String[] { "DisplayName", "BitrateBps", "BitrateMbps", "MbPerMinute", "GbPerHour", "QualityEquivalent", });
    internal_static_bladewatch_v1_ActiveRecordingEstimate_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_bladewatch_v1_ActiveRecordingEstimate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_ActiveRecordingEstimate_descriptor,
        new java.lang.String[] { "BitrateMbps", "MbPerMinute", "MbPer2Min", "GbPerHour", "MinutesPerGb", "QualityEquivalent", });
    internal_static_bladewatch_v1_GetQualityRequest_descriptor =
      getDescriptor().getMessageType(2);
    internal_static_bladewatch_v1_GetQualityRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_GetQualityRequest_descriptor,
        new java.lang.String[] { });
    internal_static_bladewatch_v1_GetQualityResponse_descriptor =
      getDescriptor().getMessageType(3);
    internal_static_bladewatch_v1_GetQualityResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_GetQualityResponse_descriptor,
        new java.lang.String[] { "Success", "RecordingQuality", "Codec", "Fps", "RecordingQualityOptions", "ActiveRecordingEstimate", "CodecOptions", "FpsOptions", "NativeResolution", "RecordingSegmentMinutes", "RecordingPriority", });
    internal_static_bladewatch_v1_GetQualityResponse_RecordingQualityOptionsEntry_descriptor =
      internal_static_bladewatch_v1_GetQualityResponse_descriptor.getNestedType(0);
    internal_static_bladewatch_v1_GetQualityResponse_RecordingQualityOptionsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_GetQualityResponse_RecordingQualityOptionsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_bladewatch_v1_GetQualityResponse_CodecOptionsEntry_descriptor =
      internal_static_bladewatch_v1_GetQualityResponse_descriptor.getNestedType(1);
    internal_static_bladewatch_v1_GetQualityResponse_CodecOptionsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_GetQualityResponse_CodecOptionsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_bladewatch_v1_GetQualityResponse_FpsOptionsEntry_descriptor =
      internal_static_bladewatch_v1_GetQualityResponse_descriptor.getNestedType(2);
    internal_static_bladewatch_v1_GetQualityResponse_FpsOptionsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_GetQualityResponse_FpsOptionsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_bladewatch_v1_SetQualityRequest_descriptor =
      getDescriptor().getMessageType(4);
    internal_static_bladewatch_v1_SetQualityRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_SetQualityRequest_descriptor,
        new java.lang.String[] { "RecordingQuality", "Codec", "StreamingQuality", "Fps", "RecordingSegmentMinutes", "RecordingPriority", });
    internal_static_bladewatch_v1_SetQualityResponse_descriptor =
      getDescriptor().getMessageType(5);
    internal_static_bladewatch_v1_SetQualityResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_SetQualityResponse_descriptor,
        new java.lang.String[] { "Success", "RecordingQuality", "Codec", "Message", "Error", });
    internal_static_bladewatch_v1_GetAppearanceRequest_descriptor =
      getDescriptor().getMessageType(6);
    internal_static_bladewatch_v1_GetAppearanceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_GetAppearanceRequest_descriptor,
        new java.lang.String[] { });
    internal_static_bladewatch_v1_GetAppearanceResponse_descriptor =
      getDescriptor().getMessageType(7);
    internal_static_bladewatch_v1_GetAppearanceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_GetAppearanceResponse_descriptor,
        new java.lang.String[] { "Success", "Theme", "Locale", });
    internal_static_bladewatch_v1_SetAppearanceRequest_descriptor =
      getDescriptor().getMessageType(8);
    internal_static_bladewatch_v1_SetAppearanceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_SetAppearanceRequest_descriptor,
        new java.lang.String[] { "Theme", "Locale", });
    internal_static_bladewatch_v1_SetAppearanceResponse_descriptor =
      getDescriptor().getMessageType(9);
    internal_static_bladewatch_v1_SetAppearanceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_SetAppearanceResponse_descriptor,
        new java.lang.String[] { "Success", "Theme", "Locale", "Error", });
    internal_static_bladewatch_v1_GetLocaleRequest_descriptor =
      getDescriptor().getMessageType(10);
    internal_static_bladewatch_v1_GetLocaleRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_GetLocaleRequest_descriptor,
        new java.lang.String[] { });
    internal_static_bladewatch_v1_GetLocaleResponse_descriptor =
      getDescriptor().getMessageType(11);
    internal_static_bladewatch_v1_GetLocaleResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_GetLocaleResponse_descriptor,
        new java.lang.String[] { "Lang", "Supported", });
    internal_static_bladewatch_v1_GetLocaleResponse_SupportedEntry_descriptor =
      internal_static_bladewatch_v1_GetLocaleResponse_descriptor.getNestedType(0);
    internal_static_bladewatch_v1_GetLocaleResponse_SupportedEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_GetLocaleResponse_SupportedEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_bladewatch_v1_SetLocaleRequest_descriptor =
      getDescriptor().getMessageType(12);
    internal_static_bladewatch_v1_SetLocaleRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_SetLocaleRequest_descriptor,
        new java.lang.String[] { "Lang", });
    internal_static_bladewatch_v1_SetLocaleResponse_descriptor =
      getDescriptor().getMessageType(13);
    internal_static_bladewatch_v1_SetLocaleResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_SetLocaleResponse_descriptor,
        new java.lang.String[] { "Lang", });
    internal_static_bladewatch_v1_SetRecordingModeRequest_descriptor =
      getDescriptor().getMessageType(14);
    internal_static_bladewatch_v1_SetRecordingModeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_SetRecordingModeRequest_descriptor,
        new java.lang.String[] { "Mode", });
    internal_static_bladewatch_v1_SetRecordingModeResponse_descriptor =
      getDescriptor().getMessageType(15);
    internal_static_bladewatch_v1_SetRecordingModeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_SetRecordingModeResponse_descriptor,
        new java.lang.String[] { "Success", "Mode", "Error", });
    internal_static_bladewatch_v1_GetStatusOverlayRequest_descriptor =
      getDescriptor().getMessageType(16);
    internal_static_bladewatch_v1_GetStatusOverlayRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_GetStatusOverlayRequest_descriptor,
        new java.lang.String[] { });
    internal_static_bladewatch_v1_GetStatusOverlayResponse_descriptor =
      getDescriptor().getMessageType(17);
    internal_static_bladewatch_v1_GetStatusOverlayResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_GetStatusOverlayResponse_descriptor,
        new java.lang.String[] { "Success", "CameraVisible", "TripVisible", });
    internal_static_bladewatch_v1_SetStatusOverlayRequest_descriptor =
      getDescriptor().getMessageType(18);
    internal_static_bladewatch_v1_SetStatusOverlayRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_SetStatusOverlayRequest_descriptor,
        new java.lang.String[] { "CameraVisible", "SetCameraVisible", "TripVisible", "SetTripVisible", });
    internal_static_bladewatch_v1_SetStatusOverlayResponse_descriptor =
      getDescriptor().getMessageType(19);
    internal_static_bladewatch_v1_SetStatusOverlayResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_SetStatusOverlayResponse_descriptor,
        new java.lang.String[] { "Success", "CameraVisible", "TripVisible", "Error", });
    internal_static_bladewatch_v1_GetTelemetryOverlayFieldsRequest_descriptor =
      getDescriptor().getMessageType(20);
    internal_static_bladewatch_v1_GetTelemetryOverlayFieldsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_GetTelemetryOverlayFieldsRequest_descriptor,
        new java.lang.String[] { });
    internal_static_bladewatch_v1_GetTelemetryOverlayFieldsResponse_descriptor =
      getDescriptor().getMessageType(21);
    internal_static_bladewatch_v1_GetTelemetryOverlayFieldsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_GetTelemetryOverlayFieldsResponse_descriptor,
        new java.lang.String[] { "Success", "AvailableFields", "Selections", });
    internal_static_bladewatch_v1_GetTelemetryOverlayFieldsResponse_SelectionsEntry_descriptor =
      internal_static_bladewatch_v1_GetTelemetryOverlayFieldsResponse_descriptor.getNestedType(0);
    internal_static_bladewatch_v1_GetTelemetryOverlayFieldsResponse_SelectionsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_GetTelemetryOverlayFieldsResponse_SelectionsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_bladewatch_v1_FieldList_descriptor =
      getDescriptor().getMessageType(22);
    internal_static_bladewatch_v1_FieldList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_FieldList_descriptor,
        new java.lang.String[] { "Fields", });
    internal_static_bladewatch_v1_SetTelemetryOverlayFieldsRequest_descriptor =
      getDescriptor().getMessageType(23);
    internal_static_bladewatch_v1_SetTelemetryOverlayFieldsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_SetTelemetryOverlayFieldsRequest_descriptor,
        new java.lang.String[] { "Type", "Fields", });
    internal_static_bladewatch_v1_SetTelemetryOverlayFieldsResponse_descriptor =
      getDescriptor().getMessageType(24);
    internal_static_bladewatch_v1_SetTelemetryOverlayFieldsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_SetTelemetryOverlayFieldsResponse_descriptor,
        new java.lang.String[] { "Success", "Error", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
