// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bladewatch/v1/settings.proto
// Protobuf Java Version: 4.35.0

package net.bladewatch.app.grpc.v1;

/**
 * Protobuf type {@code bladewatch.v1.SetTelemetryOverlayFieldsRequest}
 */
@com.google.protobuf.Generated
public final class SetTelemetryOverlayFieldsRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:bladewatch.v1.SetTelemetryOverlayFieldsRequest)
    SetTelemetryOverlayFieldsRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 0,
      /* suffix= */ "",
      "SetTelemetryOverlayFieldsRequest");
  }
  // Use SetTelemetryOverlayFieldsRequest.newBuilder() to construct.
  private SetTelemetryOverlayFieldsRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private SetTelemetryOverlayFieldsRequest() {
    type_ = "";
    fields_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return net.bladewatch.app.grpc.v1.Settings.internal_static_bladewatch_v1_SetTelemetryOverlayFieldsRequest_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return net.bladewatch.app.grpc.v1.Settings.internal_static_bladewatch_v1_SetTelemetryOverlayFieldsRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return net.bladewatch.app.grpc.v1.Settings.internal_static_bladewatch_v1_SetTelemetryOverlayFieldsRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            net.bladewatch.app.grpc.v1.SetTelemetryOverlayFieldsRequest.class, net.bladewatch.app.grpc.v1.SetTelemetryOverlayFieldsRequest.Builder.class);
  }

  public static final int TYPE_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object type_ = "";
  /**
   * <pre>
   * One of "continuous", "surveillance", "proximity". An unknown type is a bad request.
   * </pre>
   *
   * <code>string type = 1 [json_name = "type"];</code>
   * @return The type.
   */
  @java.lang.Override
  public java.lang.String getType() {
    java.lang.Object ref = type_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      type_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * One of "continuous", "surveillance", "proximity". An unknown type is a bad request.
   * </pre>
   *
   * <code>string type = 1 [json_name = "type"];</code>
   * @return The bytes for type.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTypeBytes() {
    java.lang.Object ref = type_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      type_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FIELDS_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList fields_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <pre>
   * OverlayField enum names. An unknown name is dropped by the resolver, not rejected here,
   * mirroring how a persisted config file is already treated by the reader.
   * </pre>
   *
   * <code>repeated string fields = 2 [json_name = "fields"];</code>
   * @return A list containing the fields.
   */
  public com.google.protobuf.ProtocolStringList
      getFieldsList() {
    return fields_;
  }
  /**
   * <pre>
   * OverlayField enum names. An unknown name is dropped by the resolver, not rejected here,
   * mirroring how a persisted config file is already treated by the reader.
   * </pre>
   *
   * <code>repeated string fields = 2 [json_name = "fields"];</code>
   * @return The count of fields.
   */
  public int getFieldsCount() {
    return fields_.size();
  }
  /**
   * <pre>
   * OverlayField enum names. An unknown name is dropped by the resolver, not rejected here,
   * mirroring how a persisted config file is already treated by the reader.
   * </pre>
   *
   * <code>repeated string fields = 2 [json_name = "fields"];</code>
   * @param index The index of the element to return.
   * @return The fields at the given index.
   */
  public java.lang.String getFields(int index) {
    return fields_.get(index);
  }
  /**
   * <pre>
   * OverlayField enum names. An unknown name is dropped by the resolver, not rejected here,
   * mirroring how a persisted config file is already treated by the reader.
   * </pre>
   *
   * <code>repeated string fields = 2 [json_name = "fields"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the fields at the given index.
   */
  public com.google.protobuf.ByteString
      getFieldsBytes(int index) {
    return fields_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(type_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, type_);
    }
    for (int i = 0; i < fields_.size(); i++) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, fields_.getRaw(i));
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(type_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, type_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < fields_.size(); i++) {
        dataSize += computeStringSizeNoTag(fields_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getFieldsList().size();
    }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof net.bladewatch.app.grpc.v1.SetTelemetryOverlayFieldsRequest)) {
      return super.equals(obj);
    }
    net.bladewatch.app.grpc.v1.SetTelemetryOverlayFieldsRequest other = (net.bladewatch.app.grpc.v1.SetTelemetryOverlayFieldsRequest) obj;

    if (!getType()
        .equals(other.getType())) return false;
    if (!getFieldsList()
        .equals(other.getFieldsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getType().hashCode();
    if (getFieldsCount() > 0) {
      hash = (37 * hash) + FIELDS_FIELD_NUMBER;
      hash = (53 * hash) + getFieldsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static net.bladewatch.app.grpc.v1.SetTelemetryOverlayFieldsRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.bladewatch.app.grpc.v1.SetTelemetryOverlayFieldsRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.bladewatch.app.grpc.v1.SetTelemetryOverlayFieldsRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.bladewatch.app.grpc.v1.SetTelemetryOverlayFieldsRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.bladewatch.app.grpc.v1.SetTelemetryOverlayFieldsRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.bladewatch.app.grpc.v1.SetTelemetryOverlayFieldsRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.bladewatch.app.grpc.v1.SetTelemetryOverlayFieldsRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static net.bladewatch.app.grpc.v1.SetTelemetryOverlayFieldsRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static net.bladewatch.app.grpc.v1.SetTelemetryOverlayFieldsRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static net.bladewatch.app.grpc.v1.SetTelemetryOverlayFieldsRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static net.bladewatch.app.grpc.v1.SetTelemetryOverlayFieldsRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static net.bladewatch.app.grpc.v1.SetTelemetryOverlayFieldsRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(net.bladewatch.app.grpc.v1.SetTelemetryOverlayFieldsRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code bladewatch.v1.SetTelemetryOverlayFieldsRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:bladewatch.v1.SetTelemetryOverlayFieldsRequest)
      net.bladewatch.app.grpc.v1.SetTelemetryOverlayFieldsRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.bladewatch.app.grpc.v1.Settings.internal_static_bladewatch_v1_SetTelemetryOverlayFieldsRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.bladewatch.app.grpc.v1.Settings.internal_static_bladewatch_v1_SetTelemetryOverlayFieldsRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.bladewatch.app.grpc.v1.SetTelemetryOverlayFieldsRequest.class, net.bladewatch.app.grpc.v1.SetTelemetryOverlayFieldsRequest.Builder.class);
    }

    // Construct using net.bladewatch.app.grpc.v1.SetTelemetryOverlayFieldsRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      type_ = "";
      fields_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return net.bladewatch.app.grpc.v1.Settings.internal_static_bladewatch_v1_SetTelemetryOverlayFieldsRequest_descriptor;
    }

    @java.lang.Override
    public net.bladewatch.app.grpc.v1.SetTelemetryOverlayFieldsRequest getDefaultInstanceForType() {
      return net.bladewatch.app.grpc.v1.SetTelemetryOverlayFieldsRequest.getDefaultInstance();
    }

    @java.lang.Override
    public net.bladewatch.app.grpc.v1.SetTelemetryOverlayFieldsRequest build() {
      net.bladewatch.app.grpc.v1.SetTelemetryOverlayFieldsRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public net.bladewatch.app.grpc.v1.SetTelemetryOverlayFieldsRequest buildPartial() {
      net.bladewatch.app.grpc.v1.SetTelemetryOverlayFieldsRequest result = new net.bladewatch.app.grpc.v1.SetTelemetryOverlayFieldsRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(net.bladewatch.app.grpc.v1.SetTelemetryOverlayFieldsRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.type_ = type_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        fields_.makeImmutable();
        result.fields_ = fields_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof net.bladewatch.app.grpc.v1.SetTelemetryOverlayFieldsRequest) {
        return mergeFrom((net.bladewatch.app.grpc.v1.SetTelemetryOverlayFieldsRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(net.bladewatch.app.grpc.v1.SetTelemetryOverlayFieldsRequest other) {
      if (other == net.bladewatch.app.grpc.v1.SetTelemetryOverlayFieldsRequest.getDefaultInstance()) return this;
      if (!other.getType().isEmpty()) {
        type_ = other.type_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.fields_.isEmpty()) {
        if (fields_.isEmpty()) {
          fields_ = other.fields_;
          bitField0_ |= 0x00000002;
        } else {
          ensureFieldsIsMutable();
          fields_.addAll(other.fields_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              type_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              ensureFieldsIsMutable();
              fields_.add(input.readStringRequireUtf8());
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object type_ = "";
    /**
     * <pre>
     * One of "continuous", "surveillance", "proximity". An unknown type is a bad request.
     * </pre>
     *
     * <code>string type = 1 [json_name = "type"];</code>
     * @return The type.
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        type_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * One of "continuous", "surveillance", "proximity". An unknown type is a bad request.
     * </pre>
     *
     * <code>string type = 1 [json_name = "type"];</code>
     * @return The bytes for type.
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * One of "continuous", "surveillance", "proximity". An unknown type is a bad request.
     * </pre>
     *
     * <code>string type = 1 [json_name = "type"];</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      type_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * One of "continuous", "surveillance", "proximity". An unknown type is a bad request.
     * </pre>
     *
     * <code>string type = 1 [json_name = "type"];</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      type_ = getDefaultInstance().getType();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * One of "continuous", "surveillance", "proximity". An unknown type is a bad request.
     * </pre>
     *
     * <code>string type = 1 [json_name = "type"];</code>
     * @param value The bytes for type to set.
     * @return This builder for chaining.
     */
    public Builder setTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      type_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringArrayList fields_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureFieldsIsMutable() {
      if (!fields_.isModifiable()) {
        fields_ = new com.google.protobuf.LazyStringArrayList(fields_);
      }
      bitField0_ |= 0x00000002;
    }
    /**
     * <pre>
     * OverlayField enum names. An unknown name is dropped by the resolver, not rejected here,
     * mirroring how a persisted config file is already treated by the reader.
     * </pre>
     *
     * <code>repeated string fields = 2 [json_name = "fields"];</code>
     * @return A list containing the fields.
     */
    public com.google.protobuf.ProtocolStringList
        getFieldsList() {
      fields_.makeImmutable();
      return fields_;
    }
    /**
     * <pre>
     * OverlayField enum names. An unknown name is dropped by the resolver, not rejected here,
     * mirroring how a persisted config file is already treated by the reader.
     * </pre>
     *
     * <code>repeated string fields = 2 [json_name = "fields"];</code>
     * @return The count of fields.
     */
    public int getFieldsCount() {
      return fields_.size();
    }
    /**
     * <pre>
     * OverlayField enum names. An unknown name is dropped by the resolver, not rejected here,
     * mirroring how a persisted config file is already treated by the reader.
     * </pre>
     *
     * <code>repeated string fields = 2 [json_name = "fields"];</code>
     * @param index The index of the element to return.
     * @return The fields at the given index.
     */
    public java.lang.String getFields(int index) {
      return fields_.get(index);
    }
    /**
     * <pre>
     * OverlayField enum names. An unknown name is dropped by the resolver, not rejected here,
     * mirroring how a persisted config file is already treated by the reader.
     * </pre>
     *
     * <code>repeated string fields = 2 [json_name = "fields"];</code>
     * @param index The index of the value to return.
     * @return The bytes of the fields at the given index.
     */
    public com.google.protobuf.ByteString
        getFieldsBytes(int index) {
      return fields_.getByteString(index);
    }
    /**
     * <pre>
     * OverlayField enum names. An unknown name is dropped by the resolver, not rejected here,
     * mirroring how a persisted config file is already treated by the reader.
     * </pre>
     *
     * <code>repeated string fields = 2 [json_name = "fields"];</code>
     * @param index The index to set the value at.
     * @param value The fields to set.
     * @return This builder for chaining.
     */
    public Builder setFields(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureFieldsIsMutable();
      fields_.set(index, value);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * OverlayField enum names. An unknown name is dropped by the resolver, not rejected here,
     * mirroring how a persisted config file is already treated by the reader.
     * </pre>
     *
     * <code>repeated string fields = 2 [json_name = "fields"];</code>
     * @param value The fields to add.
     * @return This builder for chaining.
     */
    public Builder addFields(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureFieldsIsMutable();
      fields_.add(value);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * OverlayField enum names. An unknown name is dropped by the resolver, not rejected here,
     * mirroring how a persisted config file is already treated by the reader.
     * </pre>
     *
     * <code>repeated string fields = 2 [json_name = "fields"];</code>
     * @param values The fields to add.
     * @return This builder for chaining.
     */
    public Builder addAllFields(
        java.lang.Iterable<java.lang.String> values) {
      ensureFieldsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, fields_);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * OverlayField enum names. An unknown name is dropped by the resolver, not rejected here,
     * mirroring how a persisted config file is already treated by the reader.
     * </pre>
     *
     * <code>repeated string fields = 2 [json_name = "fields"];</code>
     * @return This builder for chaining.
     */
    public Builder clearFields() {
      fields_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000002);;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * OverlayField enum names. An unknown name is dropped by the resolver, not rejected here,
     * mirroring how a persisted config file is already treated by the reader.
     * </pre>
     *
     * <code>repeated string fields = 2 [json_name = "fields"];</code>
     * @param value The bytes of the fields to add.
     * @return This builder for chaining.
     */
    public Builder addFieldsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureFieldsIsMutable();
      fields_.add(value);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:bladewatch.v1.SetTelemetryOverlayFieldsRequest)
  }

  // @@protoc_insertion_point(class_scope:bladewatch.v1.SetTelemetryOverlayFieldsRequest)
  private static final net.bladewatch.app.grpc.v1.SetTelemetryOverlayFieldsRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new net.bladewatch.app.grpc.v1.SetTelemetryOverlayFieldsRequest();
  }

  public static net.bladewatch.app.grpc.v1.SetTelemetryOverlayFieldsRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SetTelemetryOverlayFieldsRequest>
      PARSER = new com.google.protobuf.AbstractParser<SetTelemetryOverlayFieldsRequest>() {
    @java.lang.Override
    public SetTelemetryOverlayFieldsRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SetTelemetryOverlayFieldsRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SetTelemetryOverlayFieldsRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public net.bladewatch.app.grpc.v1.SetTelemetryOverlayFieldsRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

