// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bladewatch/v1/storage.proto
// Protobuf Java Version: 4.35.0

package net.bladewatch.app.grpc.v1;

@com.google.protobuf.Generated
public final class Storage extends com.google.protobuf.GeneratedFile {
  private Storage() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 0,
      /* suffix= */ "",
      "Storage");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_VolumeInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_VolumeInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_GetStorageSettingsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_GetStorageSettingsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_GetStorageSettingsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_GetStorageSettingsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_SetStorageSettingsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_SetStorageSettingsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_CleanupImpact_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_CleanupImpact_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_SetStorageSettingsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_SetStorageSettingsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_PreviewStorageLimitChangeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_PreviewStorageLimitChangeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_PreviewStorageLimitChangeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_PreviewStorageLimitChangeResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_GetExternalStorageRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_GetExternalStorageRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_GetExternalStorageResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_GetExternalStorageResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_SetExternalConfigRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_SetExternalConfigRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_SetExternalConfigResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_SetExternalConfigResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_TriggerCleanupRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_TriggerCleanupRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_TriggerCleanupResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_TriggerCleanupResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_PreviewCleanupRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_PreviewCleanupRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_PreviewCleanupFile_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_PreviewCleanupFile_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_PreviewCleanupResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_PreviewCleanupResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_RefreshExternalStorageRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_RefreshExternalStorageRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_RefreshExternalStorageResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_RefreshExternalStorageResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_ListFormatVolumesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_ListFormatVolumesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_ListFormatVolumesResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_ListFormatVolumesResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_FormatVolumeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_FormatVolumeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_FormatVolumeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_FormatVolumeResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033bladewatch/v1/storage.proto\022\rbladewatc" +
      "h.v1\"v\n\nVolumeInfo\022\033\n\tvolume_id\030\001 \001(\tR\010v" +
      "olumeId\022\022\n\004uuid\030\002 \001(\tR\004uuid\022\030\n\007mounted\030\003" +
      " \001(\010R\007mounted\022\035\n\nmount_path\030\004 \001(\tR\tmount" +
      "Path\"\033\n\031GetStorageSettingsRequest\"\336\t\n\032Ge" +
      "tStorageSettingsResponse\022\030\n\007success\030\001 \001(" +
      "\010R\007success\022.\n\023recordings_limit_mb\030\002 \001(\003R" +
      "\021recordingsLimitMb\0222\n\025surveillance_limit" +
      "_mb\030\003 \001(\003R\023surveillanceLimitMb\022 \n\014min_li" +
      "mit_mb\030\004 \001(\003R\nminLimitMb\022 \n\014max_limit_mb" +
      "\030\005 \001(\003R\nmaxLimitMb\022.\n\024max_limit_mb_sd_ca" +
      "rd\030\006 \001(\003R\020maxLimitMbSdCard\022\'\n\017recordings" +
      "_path\030\007 \001(\tR\016recordingsPath\022+\n\021surveilla" +
      "nce_path\030\010 \001(\tR\020surveillancePath\022-\n\025reco" +
      "rdings_size_bytes\030\t \001(\003R\016recordingsSize\022" +
      "1\n\027surveillance_size_bytes\030\n \001(\003R\020survei" +
      "llanceSize\022)\n\020recordings_count\030\013 \001(\005R\017re" +
      "cordingsCount\022-\n\022surveillance_count\030\014 \001(" +
      "\005R\021surveillanceCount\0226\n\027recordings_stora" +
      "ge_type\030\r \001(\tR\025recordingsStorageType\022:\n\031" +
      "surveillance_storage_type\030\016 \001(\tR\027surveil" +
      "lanceStorageType\022*\n\021sd_card_available\030\017 " +
      "\001(\010R\017sdCardAvailable\022 \n\014sd_card_path\030\020 \001" +
      "(\tR\nsdCardPath\022+\n\022sd_card_free_bytes\030\021 \001" +
      "(\003R\017sdCardFreeSpace\022-\n\023sd_card_total_byt" +
      "es\030\022 \001(\003R\020sdCardTotalSpace\0223\n\026sd_card_fr" +
      "ee_formatted\030\023 \001(\tR\023sdCardFreeFormatted\022" +
      "5\n\027sd_card_total_formatted\030\024 \001(\tR\024sdCard" +
      "TotalFormatted\022.\n\023internal_free_bytes\030\025 " +
      "\001(\003R\021internalFreeSpace\0220\n\024internal_total" +
      "_bytes\030\026 \001(\003R\022internalTotalSpace\0226\n\027inte" +
      "rnal_free_formatted\030\027 \001(\tR\025internalFreeF" +
      "ormatted\0228\n\030internal_total_formatted\030\030 \001" +
      "(\tR\026internalTotalFormatted\022/\n\024sd_card_mo" +
      "unt_failed\030\031 \001(\010R\021sdCardMountFailed\022-\n\023s" +
      "d_card_mount_error\030\032 \001(\tR\020sdCardMountErr" +
      "or\"\363\001\n\031SetStorageSettingsRequest\022.\n\023reco" +
      "rdings_limit_mb\030\001 \001(\003R\021recordingsLimitMb" +
      "\0222\n\025surveillance_limit_mb\030\002 \001(\003R\023surveil" +
      "lanceLimitMb\0226\n\027recordings_storage_type\030" +
      "\003 \001(\tR\025recordingsStorageType\022:\n\031surveill" +
      "ance_storage_type\030\004 \001(\tR\027surveillanceSto" +
      "rageType\"O\n\rCleanupImpact\022\035\n\nfile_count\030" +
      "\001 \001(\005R\tfileCount\022\037\n\013total_bytes\030\002 \001(\003R\nt" +
      "otalBytes\"\346\001\n\032SetStorageSettingsResponse" +
      "\022\030\n\007success\030\001 \001(\010R\007success\022\024\n\005error\030\002 \001(" +
      "\tR\005error\022I\n\021recordings_impact\030\003 \001(\0132\034.bl" +
      "adewatch.v1.CleanupImpactR\020recordingsImp" +
      "act\022M\n\023surveillance_impact\030\004 \001(\0132\034.blade" +
      "watch.v1.CleanupImpactR\022surveillanceImpa" +
      "ct\"\206\001\n PreviewStorageLimitChangeRequest\022" +
      ".\n\023recordings_limit_mb\030\001 \001(\003R\021recordings" +
      "LimitMb\0222\n\025surveillance_limit_mb\030\002 \001(\003R\023" +
      "surveillanceLimitMb\"\355\001\n!PreviewStorageLi" +
      "mitChangeResponse\022\030\n\007success\030\001 \001(\010R\007succ" +
      "ess\022\024\n\005error\030\002 \001(\tR\005error\022I\n\021recordings_" +
      "impact\030\003 \001(\0132\034.bladewatch.v1.CleanupImpa" +
      "ctR\020recordingsImpact\022M\n\023surveillance_imp" +
      "act\030\004 \001(\0132\034.bladewatch.v1.CleanupImpactR" +
      "\022surveillanceImpact\"\033\n\031GetExternalStorag" +
      "eRequest\"\335\t\n\032GetExternalStorageResponse\022" +
      "\030\n\007success\030\001 \001(\010R\007success\022*\n\021sd_card_ava" +
      "ilable\030\002 \001(\010R\017sdCardAvailable\022 \n\014sd_card" +
      "_path\030\003 \001(\tR\nsdCardPath\022&\n\022sd_card_free_" +
      "bytes\030\004 \001(\003R\nsdCardFree\022(\n\023sd_card_total" +
      "_bytes\030\005 \001(\003R\013sdCardTotal\0223\n\026sd_card_fre" +
      "e_formatted\030\006 \001(\tR\023sdCardFreeFormatted\0225" +
      "\n\027sd_card_total_formatted\030\007 \001(\tR\024sdCardT" +
      "otalFormatted\022/\n\024sd_card_used_percent\030\010 " +
      "\001(\005R\021sdCardUsedPercent\022\031\n\010cdr_path\030\t \001(\t" +
      "R\007cdrPath\022!\n\017cdr_usage_bytes\030\n \001(\003R\010cdrU" +
      "sage\022.\n\023cdr_usage_formatted\030\013 \001(\tR\021cdrUs" +
      "ageFormatted\022$\n\016cdr_file_count\030\014 \001(\005R\014cd" +
      "rFileCount\022-\n\023cdr_protected_bytes\030\r \001(\003R" +
      "\020cdrProtectedSize\0226\n\027cdr_protected_forma" +
      "tted\030\016 \001(\tR\025cdrProtectedFormatted\022-\n\023cdr" +
      "_deletable_bytes\030\017 \001(\003R\020cdrDeletableSize" +
      "\0226\n\027cdr_deletable_formatted\030\020 \001(\tR\025cdrDe" +
      "letableFormatted\022\'\n\017cleanup_enabled\030\021 \001(" +
      "\010R\016cleanupEnabled\022*\n\021reserved_space_mb\030\022" +
      " \001(\003R\017reservedSpaceMb\022\'\n\017protected_hours" +
      "\030\023 \001(\005R\016protectedHours\022$\n\016min_files_keep" +
      "\030\024 \001(\005R\014minFilesKeep\022+\n\021monitoring_activ" +
      "e\030\025 \001(\010R\020monitoringActive\022*\n\021total_bytes" +
      "_freed\030\026 \001(\003R\017totalBytesFreed\022=\n\033total_b" +
      "ytes_freed_formatted\030\027 \001(\tR\030totalBytesFr" +
      "eedFormatted\022.\n\023total_files_deleted\030\030 \001(" +
      "\005R\021totalFilesDeleted\022-\n\024last_cleanup_tim" +
      "e_ms\030\031 \001(\003R\017lastCleanupTime\0225\n\027bladewatc" +
      "h_uses_sd_card\030\032 \001(\010R\024bladewatchUsesSdCa" +
      "rd\0224\n\026recommend_auto_cleanup\030\033 \001(\010R\024reco" +
      "mmendAutoCleanup\"\257\001\n\030SetExternalConfigRe" +
      "quest\022\030\n\007enabled\030\001 \001(\010R\007enabled\022*\n\021reser" +
      "ved_space_mb\030\002 \001(\003R\017reservedSpaceMb\022\'\n\017p" +
      "rotected_hours\030\003 \001(\005R\016protectedHours\022$\n\016" +
      "min_files_keep\030\004 \001(\005R\014minFilesKeep\"\357\001\n\031S" +
      "etExternalConfigResponse\022\030\n\007success\030\001 \001(" +
      "\010R\007success\022\'\n\017cleanup_enabled\030\002 \001(\010R\016cle" +
      "anupEnabled\022*\n\021reserved_space_mb\030\003 \001(\003R\017" +
      "reservedSpaceMb\022\'\n\017protected_hours\030\004 \001(\005" +
      "R\016protectedHours\022$\n\016min_files_keep\030\005 \001(\005" +
      "R\014minFilesKeep\022\024\n\005error\030\006 \001(\tR\005error\";\n\025" +
      "TriggerCleanupRequest\022\"\n\rbytes_to_free\030\001" +
      " \001(\003R\013bytesToFree\"\250\001\n\026TriggerCleanupResp" +
      "onse\022\030\n\007success\030\001 \001(\010R\007success\022\037\n\013bytes_" +
      "freed\030\002 \001(\003R\nbytesFreed\022#\n\rfiles_deleted" +
      "\030\003 \001(\005R\014filesDeleted\022\030\n\007message\030\004 \001(\tR\007m" +
      "essage\022\024\n\005error\030\005 \001(\tR\005error\";\n\025PreviewC" +
      "leanupRequest\022\"\n\rbytes_to_free\030\001 \001(\003R\013by" +
      "tesToFree\"S\n\022PreviewCleanupFile\022\022\n\004path\030" +
      "\001 \001(\tR\004path\022\030\n\nsize_bytes\030\002 \001(\003R\004sizeJ\004\010" +
      "\003\020\004R\tage_hours\"\277\001\n\026PreviewCleanupRespons" +
      "e\022\030\n\007success\030\001 \001(\010R\007success\0227\n\005files\030\002 \003" +
      "(\0132!.bladewatch.v1.PreviewCleanupFileR\005f" +
      "iles\022(\n\025total_deletable_bytes\030\003 \001(\003R\ttot" +
      "alSize\022(\n\025total_deletable_count\030\004 \001(\005R\tf" +
      "ileCount\"\037\n\035RefreshExternalStorageReques" +
      "t\":\n\036RefreshExternalStorageResponse\022\030\n\007s" +
      "uccess\030\001 \001(\010R\007success\"\032\n\030ListFormatVolum" +
      "esRequest\"j\n\031ListFormatVolumesResponse\022\030" +
      "\n\007success\030\001 \001(\010R\007success\0223\n\007volumes\030\002 \003(" +
      "\0132\031.bladewatch.v1.VolumeInfoR\007volumes\"2\n" +
      "\023FormatVolumeRequest\022\033\n\tvolume_id\030\001 \001(\tR" +
      "\010volumeId\"\177\n\024FormatVolumeResponse\022\030\n\007suc" +
      "cess\030\001 \001(\010R\007success\022\030\n\007message\030\002 \001(\tR\007me" +
      "ssage\022\035\n\nmount_path\030\003 \001(\tR\tmountPath\022\024\n\005" +
      "error\030\004 \001(\tR\005error*`\n\013StorageType\022\034\n\030STO" +
      "RAGE_TYPE_UNSPECIFIED\020\000\022\031\n\025STORAGE_TYPE_" +
      "INTERNAL\020\001\022\030\n\024STORAGE_TYPE_SD_CARD\020\0022\257\010\n" +
      "\016StorageService\022i\n\022GetStorageSettings\022(." +
      "bladewatch.v1.GetStorageSettingsRequest\032" +
      ").bladewatch.v1.GetStorageSettingsRespon" +
      "se\022i\n\022SetStorageSettings\022(.bladewatch.v1" +
      ".SetStorageSettingsRequest\032).bladewatch." +
      "v1.SetStorageSettingsResponse\022~\n\031Preview" +
      "StorageLimitChange\022/.bladewatch.v1.Previ" +
      "ewStorageLimitChangeRequest\0320.bladewatch" +
      ".v1.PreviewStorageLimitChangeResponse\022i\n" +
      "\022GetExternalStorage\022(.bladewatch.v1.GetE" +
      "xternalStorageRequest\032).bladewatch.v1.Ge" +
      "tExternalStorageResponse\022f\n\021SetExternalC" +
      "onfig\022\'.bladewatch.v1.SetExternalConfigR" +
      "equest\032(.bladewatch.v1.SetExternalConfig" +
      "Response\022]\n\016TriggerCleanup\022$.bladewatch." +
      "v1.TriggerCleanupRequest\032%.bladewatch.v1" +
      ".TriggerCleanupResponse\022]\n\016PreviewCleanu" +
      "p\022$.bladewatch.v1.PreviewCleanupRequest\032" +
      "%.bladewatch.v1.PreviewCleanupResponse\022u" +
      "\n\026RefreshExternalStorage\022,.bladewatch.v1" +
      ".RefreshExternalStorageRequest\032-.bladewa" +
      "tch.v1.RefreshExternalStorageResponse\022f\n" +
      "\021ListFormatVolumes\022\'.bladewatch.v1.ListF" +
      "ormatVolumesRequest\032(.bladewatch.v1.List" +
      "FormatVolumesResponse\022W\n\014FormatVolume\022\"." +
      "bladewatch.v1.FormatVolumeRequest\032#.blad" +
      "ewatch.v1.FormatVolumeResponseB\036\n\032net.bl" +
      "adewatch.app.grpc.v1P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_bladewatch_v1_VolumeInfo_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_bladewatch_v1_VolumeInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_VolumeInfo_descriptor,
        new java.lang.String[] { "VolumeId", "Uuid", "Mounted", "MountPath", });
    internal_static_bladewatch_v1_GetStorageSettingsRequest_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_bladewatch_v1_GetStorageSettingsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_GetStorageSettingsRequest_descriptor,
        new java.lang.String[] { });
    internal_static_bladewatch_v1_GetStorageSettingsResponse_descriptor =
      getDescriptor().getMessageType(2);
    internal_static_bladewatch_v1_GetStorageSettingsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_GetStorageSettingsResponse_descriptor,
        new java.lang.String[] { "Success", "RecordingsLimitMb", "SurveillanceLimitMb", "MinLimitMb", "MaxLimitMb", "MaxLimitMbSdCard", "RecordingsPath", "SurveillancePath", "RecordingsSizeBytes", "SurveillanceSizeBytes", "RecordingsCount", "SurveillanceCount", "RecordingsStorageType", "SurveillanceStorageType", "SdCardAvailable", "SdCardPath", "SdCardFreeBytes", "SdCardTotalBytes", "SdCardFreeFormatted", "SdCardTotalFormatted", "InternalFreeBytes", "InternalTotalBytes", "InternalFreeFormatted", "InternalTotalFormatted", "SdCardMountFailed", "SdCardMountError", });
    internal_static_bladewatch_v1_SetStorageSettingsRequest_descriptor =
      getDescriptor().getMessageType(3);
    internal_static_bladewatch_v1_SetStorageSettingsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_SetStorageSettingsRequest_descriptor,
        new java.lang.String[] { "RecordingsLimitMb", "SurveillanceLimitMb", "RecordingsStorageType", "SurveillanceStorageType", });
    internal_static_bladewatch_v1_CleanupImpact_descriptor =
      getDescriptor().getMessageType(4);
    internal_static_bladewatch_v1_CleanupImpact_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_CleanupImpact_descriptor,
        new java.lang.String[] { "FileCount", "TotalBytes", });
    internal_static_bladewatch_v1_SetStorageSettingsResponse_descriptor =
      getDescriptor().getMessageType(5);
    internal_static_bladewatch_v1_SetStorageSettingsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_SetStorageSettingsResponse_descriptor,
        new java.lang.String[] { "Success", "Error", "RecordingsImpact", "SurveillanceImpact", });
    internal_static_bladewatch_v1_PreviewStorageLimitChangeRequest_descriptor =
      getDescriptor().getMessageType(6);
    internal_static_bladewatch_v1_PreviewStorageLimitChangeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_PreviewStorageLimitChangeRequest_descriptor,
        new java.lang.String[] { "RecordingsLimitMb", "SurveillanceLimitMb", });
    internal_static_bladewatch_v1_PreviewStorageLimitChangeResponse_descriptor =
      getDescriptor().getMessageType(7);
    internal_static_bladewatch_v1_PreviewStorageLimitChangeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_PreviewStorageLimitChangeResponse_descriptor,
        new java.lang.String[] { "Success", "Error", "RecordingsImpact", "SurveillanceImpact", });
    internal_static_bladewatch_v1_GetExternalStorageRequest_descriptor =
      getDescriptor().getMessageType(8);
    internal_static_bladewatch_v1_GetExternalStorageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_GetExternalStorageRequest_descriptor,
        new java.lang.String[] { });
    internal_static_bladewatch_v1_GetExternalStorageResponse_descriptor =
      getDescriptor().getMessageType(9);
    internal_static_bladewatch_v1_GetExternalStorageResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_GetExternalStorageResponse_descriptor,
        new java.lang.String[] { "Success", "SdCardAvailable", "SdCardPath", "SdCardFreeBytes", "SdCardTotalBytes", "SdCardFreeFormatted", "SdCardTotalFormatted", "SdCardUsedPercent", "CdrPath", "CdrUsageBytes", "CdrUsageFormatted", "CdrFileCount", "CdrProtectedBytes", "CdrProtectedFormatted", "CdrDeletableBytes", "CdrDeletableFormatted", "CleanupEnabled", "ReservedSpaceMb", "ProtectedHours", "MinFilesKeep", "MonitoringActive", "TotalBytesFreed", "TotalBytesFreedFormatted", "TotalFilesDeleted", "LastCleanupTimeMs", "BladewatchUsesSdCard", "RecommendAutoCleanup", });
    internal_static_bladewatch_v1_SetExternalConfigRequest_descriptor =
      getDescriptor().getMessageType(10);
    internal_static_bladewatch_v1_SetExternalConfigRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_SetExternalConfigRequest_descriptor,
        new java.lang.String[] { "Enabled", "ReservedSpaceMb", "ProtectedHours", "MinFilesKeep", });
    internal_static_bladewatch_v1_SetExternalConfigResponse_descriptor =
      getDescriptor().getMessageType(11);
    internal_static_bladewatch_v1_SetExternalConfigResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_SetExternalConfigResponse_descriptor,
        new java.lang.String[] { "Success", "CleanupEnabled", "ReservedSpaceMb", "ProtectedHours", "MinFilesKeep", "Error", });
    internal_static_bladewatch_v1_TriggerCleanupRequest_descriptor =
      getDescriptor().getMessageType(12);
    internal_static_bladewatch_v1_TriggerCleanupRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_TriggerCleanupRequest_descriptor,
        new java.lang.String[] { "BytesToFree", });
    internal_static_bladewatch_v1_TriggerCleanupResponse_descriptor =
      getDescriptor().getMessageType(13);
    internal_static_bladewatch_v1_TriggerCleanupResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_TriggerCleanupResponse_descriptor,
        new java.lang.String[] { "Success", "BytesFreed", "FilesDeleted", "Message", "Error", });
    internal_static_bladewatch_v1_PreviewCleanupRequest_descriptor =
      getDescriptor().getMessageType(14);
    internal_static_bladewatch_v1_PreviewCleanupRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_PreviewCleanupRequest_descriptor,
        new java.lang.String[] { "BytesToFree", });
    internal_static_bladewatch_v1_PreviewCleanupFile_descriptor =
      getDescriptor().getMessageType(15);
    internal_static_bladewatch_v1_PreviewCleanupFile_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_PreviewCleanupFile_descriptor,
        new java.lang.String[] { "Path", "SizeBytes", });
    internal_static_bladewatch_v1_PreviewCleanupResponse_descriptor =
      getDescriptor().getMessageType(16);
    internal_static_bladewatch_v1_PreviewCleanupResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_PreviewCleanupResponse_descriptor,
        new java.lang.String[] { "Success", "Files", "TotalDeletableBytes", "TotalDeletableCount", });
    internal_static_bladewatch_v1_RefreshExternalStorageRequest_descriptor =
      getDescriptor().getMessageType(17);
    internal_static_bladewatch_v1_RefreshExternalStorageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_RefreshExternalStorageRequest_descriptor,
        new java.lang.String[] { });
    internal_static_bladewatch_v1_RefreshExternalStorageResponse_descriptor =
      getDescriptor().getMessageType(18);
    internal_static_bladewatch_v1_RefreshExternalStorageResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_RefreshExternalStorageResponse_descriptor,
        new java.lang.String[] { "Success", });
    internal_static_bladewatch_v1_ListFormatVolumesRequest_descriptor =
      getDescriptor().getMessageType(19);
    internal_static_bladewatch_v1_ListFormatVolumesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_ListFormatVolumesRequest_descriptor,
        new java.lang.String[] { });
    internal_static_bladewatch_v1_ListFormatVolumesResponse_descriptor =
      getDescriptor().getMessageType(20);
    internal_static_bladewatch_v1_ListFormatVolumesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_ListFormatVolumesResponse_descriptor,
        new java.lang.String[] { "Success", "Volumes", });
    internal_static_bladewatch_v1_FormatVolumeRequest_descriptor =
      getDescriptor().getMessageType(21);
    internal_static_bladewatch_v1_FormatVolumeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_FormatVolumeRequest_descriptor,
        new java.lang.String[] { "VolumeId", });
    internal_static_bladewatch_v1_FormatVolumeResponse_descriptor =
      getDescriptor().getMessageType(22);
    internal_static_bladewatch_v1_FormatVolumeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_FormatVolumeResponse_descriptor,
        new java.lang.String[] { "Success", "Message", "MountPath", "Error", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
