// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bladewatch/v1/surveillance.proto
// Protobuf Java Version: 4.35.0

package net.bladewatch.app.grpc.v1;

@com.google.protobuf.Generated
public interface SurveillanceConfigOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bladewatch.v1.SurveillanceConfig)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Whether surveillance is enabled (persisted user preference).
   * </pre>
   *
   * <code>bool enabled = 1 [json_name = "enabled"];</code>
   * @return The enabled.
   */
  boolean getEnabled();

  /**
   * <pre>
   * Motion detection sensitivity level 1-5 (1=strict, 5=aggressive).
   * </pre>
   *
   * <code>int32 sensitivity = 2 [json_name = "sensitivity"];</code>
   * @return The sensitivity.
   */
  int getSensitivity();

  /**
   * <pre>
   * Detection distance level 1-5 (1=near/3m, 5=far/15m).
   * </pre>
   *
   * <code>int32 distance = 3 [json_name = "distance"];</code>
   * @return The distance.
   */
  int getDistance();

  /**
   * <code>double sad_threshold = 4 [json_name = "sadThreshold"];</code>
   * @return The sadThreshold.
   */
  double getSadThreshold();

  /**
   * <code>int32 pre_record_seconds = 5 [json_name = "preRecordSeconds"];</code>
   * @return The preRecordSeconds.
   */
  int getPreRecordSeconds();

  /**
   * <code>int32 post_record_seconds = 6 [json_name = "postRecordSeconds"];</code>
   * @return The postRecordSeconds.
   */
  int getPostRecordSeconds();

  /**
   * <code>int32 total_blocks = 7 [json_name = "totalBlocks"];</code>
   * @return The totalBlocks.
   */
  int getTotalBlocks();

  /**
   * <code>int32 flash_immunity = 8 [json_name = "flashImmunity"];</code>
   * @return The flashImmunity.
   */
  int getFlashImmunity();

  /**
   * <code>bool ai_enabled = 9 [json_name = "aiEnabled"];</code>
   * @return The aiEnabled.
   */
  boolean getAiEnabled();

  /**
   * <code>double ai_confidence = 10 [json_name = "aiConfidence"];</code>
   * @return The aiConfidence.
   */
  double getAiConfidence();

  /**
   * <code>double min_object_size = 11 [json_name = "minObjectSize"];</code>
   * @return The minObjectSize.
   */
  double getMinObjectSize();

  /**
   * <code>bool detect_person = 12 [json_name = "detectPerson"];</code>
   * @return The detectPerson.
   */
  boolean getDetectPerson();

  /**
   * <code>bool detect_car = 13 [json_name = "detectCar"];</code>
   * @return The detectCar.
   */
  boolean getDetectCar();

  /**
   * <code>bool detect_bike = 14 [json_name = "detectBike"];</code>
   * @return The detectBike.
   */
  boolean getDetectBike();

  /**
   * <code>string distance_preset = 15 [json_name = "distancePreset"];</code>
   * @return The distancePreset.
   */
  java.lang.String getDistancePreset();
  /**
   * <code>string distance_preset = 15 [json_name = "distancePreset"];</code>
   * @return The bytes for distancePreset.
   */
  com.google.protobuf.ByteString
      getDistancePresetBytes();

  /**
   * <code>int32 block_size = 16 [json_name = "blockSize"];</code>
   * @return The blockSize.
   */
  int getBlockSize();

  /**
   * <code>double max_distance_m = 17 [json_name = "maxDistanceM"];</code>
   * @return The maxDistanceM.
   */
  double getMaxDistanceM();

  /**
   * <code>bool night_mode = 18 [json_name = "nightMode"];</code>
   * @return The nightMode.
   */
  boolean getNightMode();

  /**
   * <code>double shadow_threshold = 19 [json_name = "shadowThreshold"];</code>
   * @return The shadowThreshold.
   */
  double getShadowThreshold();

  /**
   * <code>double density_threshold = 20 [json_name = "densityThreshold"];</code>
   * @return The densityThreshold.
   */
  double getDensityThreshold();

  /**
   * <code>int32 alarm_block_threshold = 21 [json_name = "alarmBlockThreshold"];</code>
   * @return The alarmBlockThreshold.
   */
  int getAlarmBlockThreshold();

  /**
   * <pre>
   * Recording quality tier: ECONOMY/STANDARD/HIGH/PREMIUM/MAX.
   * </pre>
   *
   * <code>string recording_quality = 22 [json_name = "recordingQuality"];</code>
   * @return The recordingQuality.
   */
  java.lang.String getRecordingQuality();
  /**
   * <pre>
   * Recording quality tier: ECONOMY/STANDARD/HIGH/PREMIUM/MAX.
   * </pre>
   *
   * <code>string recording_quality = 22 [json_name = "recordingQuality"];</code>
   * @return The bytes for recordingQuality.
   */
  com.google.protobuf.ByteString
      getRecordingQualityBytes();

  /**
   * <pre>
   * Codec: H264 or H265.
   * </pre>
   *
   * <code>string recording_codec = 23 [json_name = "recordingCodec"];</code>
   * @return The recordingCodec.
   */
  java.lang.String getRecordingCodec();
  /**
   * <pre>
   * Codec: H264 or H265.
   * </pre>
   *
   * <code>string recording_codec = 23 [json_name = "recordingCodec"];</code>
   * @return The bytes for recordingCodec.
   */
  com.google.protobuf.ByteString
      getRecordingCodecBytes();

  /**
   * <pre>
   * Per-camera enable flags.
   * </pre>
   *
   * <code>bool camera_front = 24 [json_name = "cameraFront"];</code>
   * @return The cameraFront.
   */
  boolean getCameraFront();

  /**
   * <code>bool camera_right = 25 [json_name = "cameraRight"];</code>
   * @return The cameraRight.
   */
  boolean getCameraRight();

  /**
   * <code>bool camera_rear = 26 [json_name = "cameraRear"];</code>
   * @return The cameraRear.
   */
  boolean getCameraRear();

  /**
   * <code>bool camera_left = 27 [json_name = "cameraLeft"];</code>
   * @return The cameraLeft.
   */
  boolean getCameraLeft();

  /**
   * <pre>
   * Deterrent action: "silent", "flash", "beep", etc.
   * </pre>
   *
   * <code>string deterrent_action = 28 [json_name = "deterrentAction"];</code>
   * @return The deterrentAction.
   */
  java.lang.String getDeterrentAction();
  /**
   * <pre>
   * Deterrent action: "silent", "flash", "beep", etc.
   * </pre>
   *
   * <code>string deterrent_action = 28 [json_name = "deterrentAction"];</code>
   * @return The bytes for deterrentAction.
   */
  com.google.protobuf.ByteString
      getDeterrentActionBytes();

  /**
   * <pre>
   * Minimum seconds between deterrent triggers.
   * </pre>
   *
   * <code>int32 deterrent_cooldown_seconds = 29 [json_name = "deterrentCooldownSeconds"];</code>
   * @return The deterrentCooldownSeconds.
   */
  int getDeterrentCooldownSeconds();

  /**
   * <pre>
   * Per-quadrant region-of-interest motion masks (BladeWatch-9b0f).
   *
   * The motion pipeline has supported these all along
   * (SurveillanceEngineGpu.applyQuadrantRoi -&gt; NativeMotion.setQuadrantRoi), and
   * SurveillanceApiHandler already persists and applies them — but they were
   * absent from this message, so no ConnectRPC client could ever see or set one.
   *
   * Keyed "Q0".."Q3" (front/right/rear/left), matching the REST handler's own
   * quadrant keys exactly. A quadrant is simply absent when it has no polygon.
   * The explicit json_name keeps the wire shape byte-identical to what that
   * handler already reads and writes.
   * </pre>
   *
   * <code>map&lt;string, .bladewatch.v1.RoiPolygon&gt; roi_polygons = 30 [json_name = "roiPolygons"];</code>
   */
  int getRoiPolygonsCount();
  /**
   * <pre>
   * Per-quadrant region-of-interest motion masks (BladeWatch-9b0f).
   *
   * The motion pipeline has supported these all along
   * (SurveillanceEngineGpu.applyQuadrantRoi -&gt; NativeMotion.setQuadrantRoi), and
   * SurveillanceApiHandler already persists and applies them — but they were
   * absent from this message, so no ConnectRPC client could ever see or set one.
   *
   * Keyed "Q0".."Q3" (front/right/rear/left), matching the REST handler's own
   * quadrant keys exactly. A quadrant is simply absent when it has no polygon.
   * The explicit json_name keeps the wire shape byte-identical to what that
   * handler already reads and writes.
   * </pre>
   *
   * <code>map&lt;string, .bladewatch.v1.RoiPolygon&gt; roi_polygons = 30 [json_name = "roiPolygons"];</code>
   */
  boolean containsRoiPolygons(
      java.lang.String key);
  /**
   * Use {@link #getRoiPolygonsMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, net.bladewatch.app.grpc.v1.RoiPolygon>
  getRoiPolygons();
  /**
   * <pre>
   * Per-quadrant region-of-interest motion masks (BladeWatch-9b0f).
   *
   * The motion pipeline has supported these all along
   * (SurveillanceEngineGpu.applyQuadrantRoi -&gt; NativeMotion.setQuadrantRoi), and
   * SurveillanceApiHandler already persists and applies them — but they were
   * absent from this message, so no ConnectRPC client could ever see or set one.
   *
   * Keyed "Q0".."Q3" (front/right/rear/left), matching the REST handler's own
   * quadrant keys exactly. A quadrant is simply absent when it has no polygon.
   * The explicit json_name keeps the wire shape byte-identical to what that
   * handler already reads and writes.
   * </pre>
   *
   * <code>map&lt;string, .bladewatch.v1.RoiPolygon&gt; roi_polygons = 30 [json_name = "roiPolygons"];</code>
   */
  java.util.Map<java.lang.String, net.bladewatch.app.grpc.v1.RoiPolygon>
  getRoiPolygonsMap();
  /**
   * <pre>
   * Per-quadrant region-of-interest motion masks (BladeWatch-9b0f).
   *
   * The motion pipeline has supported these all along
   * (SurveillanceEngineGpu.applyQuadrantRoi -&gt; NativeMotion.setQuadrantRoi), and
   * SurveillanceApiHandler already persists and applies them — but they were
   * absent from this message, so no ConnectRPC client could ever see or set one.
   *
   * Keyed "Q0".."Q3" (front/right/rear/left), matching the REST handler's own
   * quadrant keys exactly. A quadrant is simply absent when it has no polygon.
   * The explicit json_name keeps the wire shape byte-identical to what that
   * handler already reads and writes.
   * </pre>
   *
   * <code>map&lt;string, .bladewatch.v1.RoiPolygon&gt; roi_polygons = 30 [json_name = "roiPolygons"];</code>
   */
  /* nullable */
net.bladewatch.app.grpc.v1.RoiPolygon getRoiPolygonsOrDefault(
      java.lang.String key,
      /* nullable */
net.bladewatch.app.grpc.v1.RoiPolygon defaultValue);
  /**
   * <pre>
   * Per-quadrant region-of-interest motion masks (BladeWatch-9b0f).
   *
   * The motion pipeline has supported these all along
   * (SurveillanceEngineGpu.applyQuadrantRoi -&gt; NativeMotion.setQuadrantRoi), and
   * SurveillanceApiHandler already persists and applies them — but they were
   * absent from this message, so no ConnectRPC client could ever see or set one.
   *
   * Keyed "Q0".."Q3" (front/right/rear/left), matching the REST handler's own
   * quadrant keys exactly. A quadrant is simply absent when it has no polygon.
   * The explicit json_name keeps the wire shape byte-identical to what that
   * handler already reads and writes.
   * </pre>
   *
   * <code>map&lt;string, .bladewatch.v1.RoiPolygon&gt; roi_polygons = 30 [json_name = "roiPolygons"];</code>
   */
  net.bladewatch.app.grpc.v1.RoiPolygon getRoiPolygonsOrThrow(
      java.lang.String key);

  /**
   * <pre>
   * Whether each quadrant's polygon is actually applied. Separate from the
   * polygon itself so a zone can be switched off without losing the shape the
   * user drew — the REST handler already models it that way.
   * </pre>
   *
   * <code>bool roi_enabled_q0 = 31 [json_name = "roiEnabled_Q0"];</code>
   * @return The roiEnabledQ0.
   */
  boolean getRoiEnabledQ0();

  /**
   * <code>bool roi_enabled_q1 = 32 [json_name = "roiEnabled_Q1"];</code>
   * @return The roiEnabledQ1.
   */
  boolean getRoiEnabledQ1();

  /**
   * <code>bool roi_enabled_q2 = 33 [json_name = "roiEnabled_Q2"];</code>
   * @return The roiEnabledQ2.
   */
  boolean getRoiEnabledQ2();

  /**
   * <code>bool roi_enabled_q3 = 34 [json_name = "roiEnabled_Q3"];</code>
   * @return The roiEnabledQ3.
   */
  boolean getRoiEnabledQ3();
}
