// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bladewatch/v1/system.proto
// Protobuf Java Version: 4.35.0

package net.bladewatch.app.grpc.v1;

@com.google.protobuf.Generated
public final class System extends com.google.protobuf.GeneratedFile {
  private System() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 0,
      /* suffix= */ "",
      "System");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_BatteryInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_BatteryInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_ChargingInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_ChargingInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_SocInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_SocInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_RangeInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_RangeInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_SohInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_SohInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_RecordingStatus_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_RecordingStatus_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_TripStatus_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_TripStatus_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_NetworkInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_NetworkInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_GpsStatusInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_GpsStatusInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_GetStatusRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_GetStatusRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_GetStatusResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_GetStatusResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_GetPerformanceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_GetPerformanceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_GetPerformanceResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_GetPerformanceResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_PlayAudioTestRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_PlayAudioTestRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_PlayAudioTestResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_PlayAudioTestResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_ModelInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_ModelInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_ListModelsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_ListModelsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_ListModelsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_ListModelsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_DownloadModelRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_DownloadModelRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_DownloadModelResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_DownloadModelResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_GetSohNominalRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_GetSohNominalRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_GetSohNominalResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_GetSohNominalResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_SetSohNominalRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_SetSohNominalRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_SetSohNominalResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_SetSohNominalResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_GetSohStatusRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_GetSohStatusRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_GetSohStatusResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_GetSohStatusResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_ResetSohRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_ResetSohRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_ResetSohResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_ResetSohResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_ResetPerformanceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_ResetPerformanceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_ResetPerformanceResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_ResetPerformanceResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_GetParkingDeltaRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_GetParkingDeltaRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_GetParkingDeltaResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_GetParkingDeltaResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_GetLastChargeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_GetLastChargeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_GetLastChargeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_GetLastChargeResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_GetSelectedModelRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_GetSelectedModelRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_GetSelectedModelResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_GetSelectedModelResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_SetSelectedModelRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_SetSelectedModelRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_SetSelectedModelResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_SetSelectedModelResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_GetModelsManifestRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_GetModelsManifestRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_GetModelsManifestResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_GetModelsManifestResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_PerformanceConnectRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_PerformanceConnectRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_PerformanceConnectResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_PerformanceConnectResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_PerformanceHeartbeatRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_PerformanceHeartbeatRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_PerformanceHeartbeatResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_PerformanceHeartbeatResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_PerformanceDisconnectRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_PerformanceDisconnectRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_PerformanceDisconnectResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_PerformanceDisconnectResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032bladewatch/v1/system.proto\022\rbladewatch" +
      ".v1\"Y\n\013BatteryInfo\022\024\n\005level\030\001 \001(\tR\005level" +
      "J\004\010\002\020\003J\004\010\003\020\004J\004\010\004\020\005R\006statusR\013is_chargingR" +
      "\rstatus_string\"\327\001\n\014ChargingInfo\022\035\n\nstate" +
      "_name\030\001 \001(\tR\tstateName\022\026\n\006status\030\002 \001(\tR\006" +
      "status\022+\n\022charging_power_k_w\030\003 \001(\001R\017char" +
      "gingPowerKW\022%\n\016is_discharging\030\004 \001(\010R\risD" +
      "ischarging\022\031\n\010is_error\030\005 \001(\010R\007isError\022!\n" +
      "\014is_estimated\030\006 \001(\010R\013isEstimated\"s\n\007SocI" +
      "nfo\022\030\n\007percent\030\001 \001(\001R\007percent\022\025\n\006is_low\030" +
      "\002 \001(\010R\005isLow\022\037\n\013is_critical\030\003 \001(\010R\nisCri" +
      "tical\022\026\n\006status\030\004 \001(\tR\006status\"\354\001\n\tRangeI" +
      "nfo\022\"\n\relec_range_km\030\001 \001(\001R\013elecRangeKm\022" +
      "\"\n\rfuel_range_km\030\002 \001(\001R\013fuelRangeKm\022$\n\016t" +
      "otal_range_km\030\003 \001(\001R\014totalRangeKm\022\025\n\006is_" +
      "low\030\004 \001(\010R\005isLow\022\037\n\013is_critical\030\005 \001(\010R\ni" +
      "sCritical\022\026\n\006status\030\006 \001(\tR\006status\022!\n\014fue" +
      "l_percent\030\007 \001(\001R\013fuelPercent\"#\n\007SohInfo\022" +
      "\030\n\007percent\030\001 \001(\001R\007percent\"\263\001\n\017RecordingS" +
      "tatus\022\'\n\017configured_mode\030\001 \001(\tR\016configur" +
      "edMode\022!\n\014is_recording\030\002 \001(\010R\013isRecordin" +
      "g\022)\n\020pipeline_running\030\003 \001(\010R\017pipelineRun" +
      "ning\022\022\n\004gear\030\004 \001(\tR\004gear\022\025\n\006acc_on\030\005 \001(\010" +
      "R\005accOn\"\233\001\n\nTripStatus\022\030\n\007enabled\030\001 \001(\010R" +
      "\007enabled\022\037\n\013trip_active\030\002 \001(\010R\ntripActiv" +
      "e\022&\n\017trip_start_time\030\003 \001(\003R\rtripStartTim" +
      "e\022*\n\021trip_duration_sec\030\004 \001(\003R\017tripDurati" +
      "onSec\"\214\002\n\013NetworkInfo\022\022\n\004type\030\001 \001(\tR\004typ" +
      "e\022\022\n\004ssid\030\002 \001(\tR\004ssid\022\016\n\002ip\030\003 \001(\tR\002ip\022(\n" +
      "\020lan_http_enabled\030\004 \001(\010R\016lanHttpEnabled\022" +
      "\033\n\thttp_bind\030\005 \001(\tR\010httpBind\022*\n\021http_mod" +
      "e_warning\030\006 \001(\tR\017httpModeWarning\022(\n\020this" +
      "_month_bytes\030\007 \001(\003R\016thisMonthBytes\022(\n\020la" +
      "st_month_bytes\030\010 \001(\003R\016lastMonthBytes\"s\n\r" +
      "GpsStatusInfo\022\020\n\003lat\030\001 \001(\001R\003lat\022\020\n\003lng\030\002" +
      " \001(\001R\003lng\022\033\n\tspeed_kmh\030\003 \001(\001R\010speedKmh\022!" +
      "\n\014has_location\030\004 \001(\010R\013hasLocation\"\022\n\020Get" +
      "StatusRequest\"\317\007\n\021GetStatusResponse\022\033\n\td" +
      "evice_id\030\001 \001(\tR\010deviceId\022,\n\022vehicle_data" +
      "_ready\030\002 \001(\010R\020vehicleDataReady\022\037\n\013app_ve" +
      "rsion\030\003 \001(\tR\nappVersion\022\034\n\trecording\030\004 \003" +
      "(\005R\trecording\022\030\n\007viewing\030\005 \003(\005R\007viewing\022" +
      "\026\n\006active\030\006 \003(\005R\006active\022\034\n\tavailable\030\007 \003" +
      "(\005R\tavailable\0224\n\007battery\030\010 \001(\0132\032.bladewa" +
      "tch.v1.BatteryInfoR\007battery\022\020\n\003acc\030\t \001(\010" +
      "R\003acc\0227\n\010charging\030\n \001(\0132\033.bladewatch.v1." +
      "ChargingInfoR\010charging\022(\n\003soc\030\013 \001(\0132\026.bl" +
      "adewatch.v1.SocInfoR\003soc\022.\n\005range\030\014 \001(\0132" +
      "\030.bladewatch.v1.RangeInfoR\005range\022(\n\003soh\030" +
      "\r \001(\0132\026.bladewatch.v1.SohInfoR\003soh\022#\n\rdi" +
      "stance_unit\030\016 \001(\tR\014distanceUnit\022\026\n\006local" +
      "e\030\017 \001(\tR\006locale\0220\n\024safe_zone_suppressed\030" +
      "\020 \001(\010R\022safeZoneSuppressed\022 \n\014in_safe_zon" +
      "e\030\021 \001(\010R\ninSafeZone\022$\n\016safe_zone_name\030\022 " +
      "\001(\tR\014safeZoneName\022)\n\020gpu_surveillance\030\023 " +
      "\001(\010R\017gpuSurveillance\022I\n\020recording_status" +
      "\030\024 \001(\0132\036.bladewatch.v1.RecordingStatusR\017" +
      "recordingStatus\022:\n\013trip_status\030\025 \001(\0132\031.b" +
      "ladewatch.v1.TripStatusR\ntripStatus\0224\n\007n" +
      "etwork\030\027 \001(\0132\032.bladewatch.v1.NetworkInfo" +
      "R\007network\022,\n\022vehicle_data_error\030\030 \001(\tR\020v" +
      "ehicleDataErrorJ\004\010\026\020\027R\010gps_json\"\027\n\025GetPe" +
      "rformanceRequest\"]\n\026GetPerformanceRespon" +
      "se\022\030\n\007success\030\001 \001(\010R\007success\022)\n\020performa" +
      "nce_json\030\002 \001(\tR\017performanceJson\"7\n\024PlayA" +
      "udioTestRequest\022\037\n\013duration_ms\030\001 \001(\005R\ndu" +
      "rationMs\"a\n\025PlayAudioTestResponse\022\030\n\007suc" +
      "cess\030\001 \001(\010R\007success\022\030\n\007message\030\002 \001(\tR\007me" +
      "ssage\022\024\n\005error\030\003 \001(\tR\005error\"i\n\tModelInfo" +
      "\022\022\n\004name\030\001 \001(\tR\004name\022\036\n\ndownloaded\030\003 \001(\010" +
      "R\ndownloaded\022\035\n\nsize_bytes\030\004 \001(\003R\tsizeBy" +
      "tesJ\004\010\002\020\003R\003url\"\023\n\021ListModelsRequest\"U\n\022L" +
      "istModelsResponse\0220\n\006models\030\002 \003(\0132\030.blad" +
      "ewatch.v1.ModelInfoR\006modelsJ\004\010\001\020\002R\007succe" +
      "ss\"<\n\024DownloadModelRequest\022\020\n\003url\030\001 \001(\tR" +
      "\003url\022\022\n\004name\030\002 \001(\tR\004name\"a\n\025DownloadMode" +
      "lResponse\022\030\n\007success\030\001 \001(\010R\007success\022\030\n\007m" +
      "essage\030\002 \001(\tR\007message\022\024\n\005error\030\003 \001(\tR\005er" +
      "ror\"\026\n\024GetSohNominalRequest\"t\n\025GetSohNom" +
      "inalResponse\022$\n\013nominal_kwh\030\001 \001(\001H\000R\nnom" +
      "inalKwh\210\001\001\022%\n\016nominal_source\030\002 \001(\tR\rnomi" +
      "nalSourceB\016\n\014_nominal_kwh\"L\n\024SetSohNomin" +
      "alRequest\022$\n\013nominal_kwh\030\001 \001(\001H\000R\nnomina" +
      "lKwh\210\001\001B\016\n\014_nominal_kwh\"G\n\025SetSohNominal" +
      "Response\022\030\n\007success\030\001 \001(\010R\007success\022\024\n\005er" +
      "ror\030\002 \001(\tR\005error\"\025\n\023GetSohStatusRequest\"" +
      "\347\001\n\024GetSohStatusResponse\022\030\n\007success\030\001 \001(" +
      "\010R\007success\0220\n\024nominal_capacity_kwh\030\002 \001(\001" +
      "R\022nominalCapacityKwh\022%\n\016nominal_source\030\003" +
      " \001(\tR\rnominalSource\022\037\n\013display_soh\030\004 \001(\001" +
      "R\ndisplaySoh\022%\n\016display_source\030\005 \001(\tR\rdi" +
      "splaySource\022\024\n\005error\030\006 \001(\tR\005error\"\021\n\017Res" +
      "etSohRequest\"B\n\020ResetSohResponse\022\030\n\007succ" +
      "ess\030\001 \001(\010R\007success\022\024\n\005error\030\002 \001(\tR\005error" +
      "\"9\n\027ResetPerformanceRequest\022\036\n\ncategorie" +
      "s\030\001 \003(\tR\ncategories\"m\n\030ResetPerformanceR" +
      "esponse\022\030\n\007success\030\001 \001(\010R\007success\022!\n\014res" +
      "ults_json\030\002 \001(\tR\013resultsJson\022\024\n\005error\030\003 " +
      "\001(\tR\005error\"<\n\026GetParkingDeltaRequest\022\"\n\r" +
      "max_age_hours\030\001 \001(\005R\013maxAgeHours\"R\n\027GetP" +
      "arkingDeltaResponse\022\034\n\tavailable\030\001 \001(\010R\t" +
      "available\022\031\n\010raw_json\030\002 \001(\tR\007rawJson\"5\n\024" +
      "GetLastChargeRequest\022\035\n\nhours_back\030\001 \001(\005" +
      "R\thoursBack\"P\n\025GetLastChargeResponse\022\034\n\t" +
      "available\030\001 \001(\010R\tavailable\022\031\n\010raw_json\030\002" +
      " \001(\tR\007rawJson\"\031\n\027GetSelectedModelRequest" +
      "\"K\n\030GetSelectedModelResponse\022\031\n\010model_id" +
      "\030\001 \001(\tR\007modelId\022\024\n\005color\030\002 \001(\tR\005color\"J\n" +
      "\027SetSelectedModelRequest\022\031\n\010model_id\030\001 \001" +
      "(\tR\007modelId\022\024\n\005color\030\002 \001(\tR\005color\"@\n\030Set" +
      "SelectedModelResponse\022\016\n\002ok\030\001 \001(\010R\002ok\022\024\n" +
      "\005error\030\002 \001(\tR\005error\"\032\n\030GetModelsManifest" +
      "Request\"@\n\031GetModelsManifestResponse\022#\n\r" +
      "manifest_json\030\001 \001(\tR\014manifestJson\"8\n\031Per" +
      "formanceConnectRequest\022\033\n\tclient_id\030\001 \001(" +
      "\tR\010clientId\"i\n\032PerformanceConnectRespons" +
      "e\022\030\n\007success\030\001 \001(\010R\007success\022\033\n\tclient_id" +
      "\030\002 \001(\tR\010clientId\022\024\n\005error\030\003 \001(\tR\005error\":" +
      "\n\033PerformanceHeartbeatRequest\022\033\n\tclient_" +
      "id\030\001 \001(\tR\010clientId\"N\n\034PerformanceHeartbe" +
      "atResponse\022\030\n\007success\030\001 \001(\010R\007success\022\024\n\005" +
      "error\030\002 \001(\tR\005error\";\n\034PerformanceDisconn" +
      "ectRequest\022\033\n\tclient_id\030\001 \001(\tR\010clientId\"" +
      "O\n\035PerformanceDisconnectResponse\022\030\n\007succ" +
      "ess\030\001 \001(\010R\007success\022\024\n\005error\030\002 \001(\tR\005error" +
      "2\314\r\n\rSystemService\022N\n\tGetStatus\022\037.bladew" +
      "atch.v1.GetStatusRequest\032 .bladewatch.v1" +
      ".GetStatusResponse\022]\n\016GetPerformance\022$.b" +
      "ladewatch.v1.GetPerformanceRequest\032%.bla" +
      "dewatch.v1.GetPerformanceResponse\022Z\n\rPla" +
      "yAudioTest\022#.bladewatch.v1.PlayAudioTest" +
      "Request\032$.bladewatch.v1.PlayAudioTestRes" +
      "ponse\022Q\n\nListModels\022 .bladewatch.v1.List" +
      "ModelsRequest\032!.bladewatch.v1.ListModels" +
      "Response\022Z\n\rDownloadModel\022#.bladewatch.v" +
      "1.DownloadModelRequest\032$.bladewatch.v1.D" +
      "ownloadModelResponse\022Z\n\rGetSohNominal\022#." +
      "bladewatch.v1.GetSohNominalRequest\032$.bla" +
      "dewatch.v1.GetSohNominalResponse\022Z\n\rSetS" +
      "ohNominal\022#.bladewatch.v1.SetSohNominalR" +
      "equest\032$.bladewatch.v1.SetSohNominalResp" +
      "onse\022W\n\014GetSohStatus\022\".bladewatch.v1.Get" +
      "SohStatusRequest\032#.bladewatch.v1.GetSohS" +
      "tatusResponse\022K\n\010ResetSoh\022\036.bladewatch.v" +
      "1.ResetSohRequest\032\037.bladewatch.v1.ResetS" +
      "ohResponse\022c\n\020ResetPerformance\022&.bladewa" +
      "tch.v1.ResetPerformanceRequest\032\'.bladewa" +
      "tch.v1.ResetPerformanceResponse\022`\n\017GetPa" +
      "rkingDelta\022%.bladewatch.v1.GetParkingDel" +
      "taRequest\032&.bladewatch.v1.GetParkingDelt" +
      "aResponse\022Z\n\rGetLastCharge\022#.bladewatch." +
      "v1.GetLastChargeRequest\032$.bladewatch.v1." +
      "GetLastChargeResponse\022c\n\020GetSelectedMode" +
      "l\022&.bladewatch.v1.GetSelectedModelReques" +
      "t\032\'.bladewatch.v1.GetSelectedModelRespon" +
      "se\022c\n\020SetSelectedModel\022&.bladewatch.v1.S" +
      "etSelectedModelRequest\032\'.bladewatch.v1.S" +
      "etSelectedModelResponse\022f\n\021GetModelsMani" +
      "fest\022\'.bladewatch.v1.GetModelsManifestRe" +
      "quest\032(.bladewatch.v1.GetModelsManifestR" +
      "esponse\022i\n\022PerformanceConnect\022(.bladewat" +
      "ch.v1.PerformanceConnectRequest\032).bladew" +
      "atch.v1.PerformanceConnectResponse\022o\n\024Pe" +
      "rformanceHeartbeat\022*.bladewatch.v1.Perfo" +
      "rmanceHeartbeatRequest\032+.bladewatch.v1.P" +
      "erformanceHeartbeatResponse\022r\n\025Performan" +
      "ceDisconnect\022+.bladewatch.v1.Performance" +
      "DisconnectRequest\032,.bladewatch.v1.Perfor" +
      "manceDisconnectResponseB\036\n\032net.bladewatc" +
      "h.app.grpc.v1P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_bladewatch_v1_BatteryInfo_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_bladewatch_v1_BatteryInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_BatteryInfo_descriptor,
        new java.lang.String[] { "Level", });
    internal_static_bladewatch_v1_ChargingInfo_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_bladewatch_v1_ChargingInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_ChargingInfo_descriptor,
        new java.lang.String[] { "StateName", "Status", "ChargingPowerKW", "IsDischarging", "IsError", "IsEstimated", });
    internal_static_bladewatch_v1_SocInfo_descriptor =
      getDescriptor().getMessageType(2);
    internal_static_bladewatch_v1_SocInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_SocInfo_descriptor,
        new java.lang.String[] { "Percent", "IsLow", "IsCritical", "Status", });
    internal_static_bladewatch_v1_RangeInfo_descriptor =
      getDescriptor().getMessageType(3);
    internal_static_bladewatch_v1_RangeInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_RangeInfo_descriptor,
        new java.lang.String[] { "ElecRangeKm", "FuelRangeKm", "TotalRangeKm", "IsLow", "IsCritical", "Status", "FuelPercent", });
    internal_static_bladewatch_v1_SohInfo_descriptor =
      getDescriptor().getMessageType(4);
    internal_static_bladewatch_v1_SohInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_SohInfo_descriptor,
        new java.lang.String[] { "Percent", });
    internal_static_bladewatch_v1_RecordingStatus_descriptor =
      getDescriptor().getMessageType(5);
    internal_static_bladewatch_v1_RecordingStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_RecordingStatus_descriptor,
        new java.lang.String[] { "ConfiguredMode", "IsRecording", "PipelineRunning", "Gear", "AccOn", });
    internal_static_bladewatch_v1_TripStatus_descriptor =
      getDescriptor().getMessageType(6);
    internal_static_bladewatch_v1_TripStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_TripStatus_descriptor,
        new java.lang.String[] { "Enabled", "TripActive", "TripStartTime", "TripDurationSec", });
    internal_static_bladewatch_v1_NetworkInfo_descriptor =
      getDescriptor().getMessageType(7);
    internal_static_bladewatch_v1_NetworkInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_NetworkInfo_descriptor,
        new java.lang.String[] { "Type", "Ssid", "Ip", "LanHttpEnabled", "HttpBind", "HttpModeWarning", "ThisMonthBytes", "LastMonthBytes", });
    internal_static_bladewatch_v1_GpsStatusInfo_descriptor =
      getDescriptor().getMessageType(8);
    internal_static_bladewatch_v1_GpsStatusInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_GpsStatusInfo_descriptor,
        new java.lang.String[] { "Lat", "Lng", "SpeedKmh", "HasLocation", });
    internal_static_bladewatch_v1_GetStatusRequest_descriptor =
      getDescriptor().getMessageType(9);
    internal_static_bladewatch_v1_GetStatusRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_GetStatusRequest_descriptor,
        new java.lang.String[] { });
    internal_static_bladewatch_v1_GetStatusResponse_descriptor =
      getDescriptor().getMessageType(10);
    internal_static_bladewatch_v1_GetStatusResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_GetStatusResponse_descriptor,
        new java.lang.String[] { "DeviceId", "VehicleDataReady", "AppVersion", "Recording", "Viewing", "Active", "Available", "Battery", "Acc", "Charging", "Soc", "Range", "Soh", "DistanceUnit", "Locale", "SafeZoneSuppressed", "InSafeZone", "SafeZoneName", "GpuSurveillance", "RecordingStatus", "TripStatus", "Network", "VehicleDataError", });
    internal_static_bladewatch_v1_GetPerformanceRequest_descriptor =
      getDescriptor().getMessageType(11);
    internal_static_bladewatch_v1_GetPerformanceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_GetPerformanceRequest_descriptor,
        new java.lang.String[] { });
    internal_static_bladewatch_v1_GetPerformanceResponse_descriptor =
      getDescriptor().getMessageType(12);
    internal_static_bladewatch_v1_GetPerformanceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_GetPerformanceResponse_descriptor,
        new java.lang.String[] { "Success", "PerformanceJson", });
    internal_static_bladewatch_v1_PlayAudioTestRequest_descriptor =
      getDescriptor().getMessageType(13);
    internal_static_bladewatch_v1_PlayAudioTestRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_PlayAudioTestRequest_descriptor,
        new java.lang.String[] { "DurationMs", });
    internal_static_bladewatch_v1_PlayAudioTestResponse_descriptor =
      getDescriptor().getMessageType(14);
    internal_static_bladewatch_v1_PlayAudioTestResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_PlayAudioTestResponse_descriptor,
        new java.lang.String[] { "Success", "Message", "Error", });
    internal_static_bladewatch_v1_ModelInfo_descriptor =
      getDescriptor().getMessageType(15);
    internal_static_bladewatch_v1_ModelInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_ModelInfo_descriptor,
        new java.lang.String[] { "Name", "Downloaded", "SizeBytes", });
    internal_static_bladewatch_v1_ListModelsRequest_descriptor =
      getDescriptor().getMessageType(16);
    internal_static_bladewatch_v1_ListModelsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_ListModelsRequest_descriptor,
        new java.lang.String[] { });
    internal_static_bladewatch_v1_ListModelsResponse_descriptor =
      getDescriptor().getMessageType(17);
    internal_static_bladewatch_v1_ListModelsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_ListModelsResponse_descriptor,
        new java.lang.String[] { "Models", });
    internal_static_bladewatch_v1_DownloadModelRequest_descriptor =
      getDescriptor().getMessageType(18);
    internal_static_bladewatch_v1_DownloadModelRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_DownloadModelRequest_descriptor,
        new java.lang.String[] { "Url", "Name", });
    internal_static_bladewatch_v1_DownloadModelResponse_descriptor =
      getDescriptor().getMessageType(19);
    internal_static_bladewatch_v1_DownloadModelResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_DownloadModelResponse_descriptor,
        new java.lang.String[] { "Success", "Message", "Error", });
    internal_static_bladewatch_v1_GetSohNominalRequest_descriptor =
      getDescriptor().getMessageType(20);
    internal_static_bladewatch_v1_GetSohNominalRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_GetSohNominalRequest_descriptor,
        new java.lang.String[] { });
    internal_static_bladewatch_v1_GetSohNominalResponse_descriptor =
      getDescriptor().getMessageType(21);
    internal_static_bladewatch_v1_GetSohNominalResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_GetSohNominalResponse_descriptor,
        new java.lang.String[] { "NominalKwh", "NominalSource", });
    internal_static_bladewatch_v1_SetSohNominalRequest_descriptor =
      getDescriptor().getMessageType(22);
    internal_static_bladewatch_v1_SetSohNominalRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_SetSohNominalRequest_descriptor,
        new java.lang.String[] { "NominalKwh", });
    internal_static_bladewatch_v1_SetSohNominalResponse_descriptor =
      getDescriptor().getMessageType(23);
    internal_static_bladewatch_v1_SetSohNominalResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_SetSohNominalResponse_descriptor,
        new java.lang.String[] { "Success", "Error", });
    internal_static_bladewatch_v1_GetSohStatusRequest_descriptor =
      getDescriptor().getMessageType(24);
    internal_static_bladewatch_v1_GetSohStatusRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_GetSohStatusRequest_descriptor,
        new java.lang.String[] { });
    internal_static_bladewatch_v1_GetSohStatusResponse_descriptor =
      getDescriptor().getMessageType(25);
    internal_static_bladewatch_v1_GetSohStatusResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_GetSohStatusResponse_descriptor,
        new java.lang.String[] { "Success", "NominalCapacityKwh", "NominalSource", "DisplaySoh", "DisplaySource", "Error", });
    internal_static_bladewatch_v1_ResetSohRequest_descriptor =
      getDescriptor().getMessageType(26);
    internal_static_bladewatch_v1_ResetSohRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_ResetSohRequest_descriptor,
        new java.lang.String[] { });
    internal_static_bladewatch_v1_ResetSohResponse_descriptor =
      getDescriptor().getMessageType(27);
    internal_static_bladewatch_v1_ResetSohResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_ResetSohResponse_descriptor,
        new java.lang.String[] { "Success", "Error", });
    internal_static_bladewatch_v1_ResetPerformanceRequest_descriptor =
      getDescriptor().getMessageType(28);
    internal_static_bladewatch_v1_ResetPerformanceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_ResetPerformanceRequest_descriptor,
        new java.lang.String[] { "Categories", });
    internal_static_bladewatch_v1_ResetPerformanceResponse_descriptor =
      getDescriptor().getMessageType(29);
    internal_static_bladewatch_v1_ResetPerformanceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_ResetPerformanceResponse_descriptor,
        new java.lang.String[] { "Success", "ResultsJson", "Error", });
    internal_static_bladewatch_v1_GetParkingDeltaRequest_descriptor =
      getDescriptor().getMessageType(30);
    internal_static_bladewatch_v1_GetParkingDeltaRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_GetParkingDeltaRequest_descriptor,
        new java.lang.String[] { "MaxAgeHours", });
    internal_static_bladewatch_v1_GetParkingDeltaResponse_descriptor =
      getDescriptor().getMessageType(31);
    internal_static_bladewatch_v1_GetParkingDeltaResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_GetParkingDeltaResponse_descriptor,
        new java.lang.String[] { "Available", "RawJson", });
    internal_static_bladewatch_v1_GetLastChargeRequest_descriptor =
      getDescriptor().getMessageType(32);
    internal_static_bladewatch_v1_GetLastChargeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_GetLastChargeRequest_descriptor,
        new java.lang.String[] { "HoursBack", });
    internal_static_bladewatch_v1_GetLastChargeResponse_descriptor =
      getDescriptor().getMessageType(33);
    internal_static_bladewatch_v1_GetLastChargeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_GetLastChargeResponse_descriptor,
        new java.lang.String[] { "Available", "RawJson", });
    internal_static_bladewatch_v1_GetSelectedModelRequest_descriptor =
      getDescriptor().getMessageType(34);
    internal_static_bladewatch_v1_GetSelectedModelRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_GetSelectedModelRequest_descriptor,
        new java.lang.String[] { });
    internal_static_bladewatch_v1_GetSelectedModelResponse_descriptor =
      getDescriptor().getMessageType(35);
    internal_static_bladewatch_v1_GetSelectedModelResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_GetSelectedModelResponse_descriptor,
        new java.lang.String[] { "ModelId", "Color", });
    internal_static_bladewatch_v1_SetSelectedModelRequest_descriptor =
      getDescriptor().getMessageType(36);
    internal_static_bladewatch_v1_SetSelectedModelRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_SetSelectedModelRequest_descriptor,
        new java.lang.String[] { "ModelId", "Color", });
    internal_static_bladewatch_v1_SetSelectedModelResponse_descriptor =
      getDescriptor().getMessageType(37);
    internal_static_bladewatch_v1_SetSelectedModelResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_SetSelectedModelResponse_descriptor,
        new java.lang.String[] { "Ok", "Error", });
    internal_static_bladewatch_v1_GetModelsManifestRequest_descriptor =
      getDescriptor().getMessageType(38);
    internal_static_bladewatch_v1_GetModelsManifestRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_GetModelsManifestRequest_descriptor,
        new java.lang.String[] { });
    internal_static_bladewatch_v1_GetModelsManifestResponse_descriptor =
      getDescriptor().getMessageType(39);
    internal_static_bladewatch_v1_GetModelsManifestResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_GetModelsManifestResponse_descriptor,
        new java.lang.String[] { "ManifestJson", });
    internal_static_bladewatch_v1_PerformanceConnectRequest_descriptor =
      getDescriptor().getMessageType(40);
    internal_static_bladewatch_v1_PerformanceConnectRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_PerformanceConnectRequest_descriptor,
        new java.lang.String[] { "ClientId", });
    internal_static_bladewatch_v1_PerformanceConnectResponse_descriptor =
      getDescriptor().getMessageType(41);
    internal_static_bladewatch_v1_PerformanceConnectResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_PerformanceConnectResponse_descriptor,
        new java.lang.String[] { "Success", "ClientId", "Error", });
    internal_static_bladewatch_v1_PerformanceHeartbeatRequest_descriptor =
      getDescriptor().getMessageType(42);
    internal_static_bladewatch_v1_PerformanceHeartbeatRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_PerformanceHeartbeatRequest_descriptor,
        new java.lang.String[] { "ClientId", });
    internal_static_bladewatch_v1_PerformanceHeartbeatResponse_descriptor =
      getDescriptor().getMessageType(43);
    internal_static_bladewatch_v1_PerformanceHeartbeatResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_PerformanceHeartbeatResponse_descriptor,
        new java.lang.String[] { "Success", "Error", });
    internal_static_bladewatch_v1_PerformanceDisconnectRequest_descriptor =
      getDescriptor().getMessageType(44);
    internal_static_bladewatch_v1_PerformanceDisconnectRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_PerformanceDisconnectRequest_descriptor,
        new java.lang.String[] { "ClientId", });
    internal_static_bladewatch_v1_PerformanceDisconnectResponse_descriptor =
      getDescriptor().getMessageType(45);
    internal_static_bladewatch_v1_PerformanceDisconnectResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_PerformanceDisconnectResponse_descriptor,
        new java.lang.String[] { "Success", "Error", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
