// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bladewatch/v1/settings.proto
// Protobuf Java Version: 4.35.0

package net.bladewatch.app.grpc.v1;

@com.google.protobuf.Generated
public interface VerifySettingsPinRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bladewatch.v1.VerifySettingsPinRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string pin = 1 [json_name = "pin"];</code>
   * @return The pin.
   */
  java.lang.String getPin();
  /**
   * <code>string pin = 1 [json_name = "pin"];</code>
   * @return The bytes for pin.
   */
  com.google.protobuf.ByteString
      getPinBytes();
}
