// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bladewatch/v1/settings.proto
// Protobuf Java Version: 4.35.0

package net.bladewatch.app.grpc.v1;

@com.google.protobuf.Generated
public interface VerifySettingsPinResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bladewatch.v1.VerifySettingsPinResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool ok = 1 [json_name = "ok"];</code>
   * @return The ok.
   */
  boolean getOk();

  /**
   * <pre>
   * &gt; 0: locked out; ok is false and the PIN given was not checked.
   * </pre>
   *
   * <code>int64 retry_after_ms = 2 [json_name = "retryAfterMs"];</code>
   * @return The retryAfterMs.
   */
  long getRetryAfterMs();

  /**
   * <pre>
   * Wrong PINs left before the next lockout.
   * </pre>
   *
   * <code>int32 attempts_left = 3 [json_name = "attemptsLeft"];</code>
   * @return The attemptsLeft.
   */
  int getAttemptsLeft();
}
