// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bladewatch/v1/settings.proto
// Protobuf Java Version: 4.35.0

package net.bladewatch.app.grpc.v1;

/**
 * Protobuf type {@code bladewatch.v1.VerifySettingsPinResponse}
 */
@com.google.protobuf.Generated
public final class VerifySettingsPinResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:bladewatch.v1.VerifySettingsPinResponse)
    VerifySettingsPinResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 0,
      /* suffix= */ "",
      "VerifySettingsPinResponse");
  }
  // Use VerifySettingsPinResponse.newBuilder() to construct.
  private VerifySettingsPinResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private VerifySettingsPinResponse() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return net.bladewatch.app.grpc.v1.Settings.internal_static_bladewatch_v1_VerifySettingsPinResponse_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return net.bladewatch.app.grpc.v1.Settings.internal_static_bladewatch_v1_VerifySettingsPinResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return net.bladewatch.app.grpc.v1.Settings.internal_static_bladewatch_v1_VerifySettingsPinResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            net.bladewatch.app.grpc.v1.VerifySettingsPinResponse.class, net.bladewatch.app.grpc.v1.VerifySettingsPinResponse.Builder.class);
  }

  public static final int OK_FIELD_NUMBER = 1;
  private boolean ok_ = false;
  /**
   * <code>bool ok = 1 [json_name = "ok"];</code>
   * @return The ok.
   */
  @java.lang.Override
  public boolean getOk() {
    return ok_;
  }

  public static final int RETRY_AFTER_MS_FIELD_NUMBER = 2;
  private long retryAfterMs_ = 0L;
  /**
   * <pre>
   * &gt; 0: locked out; ok is false and the PIN given was not checked.
   * </pre>
   *
   * <code>int64 retry_after_ms = 2 [json_name = "retryAfterMs"];</code>
   * @return The retryAfterMs.
   */
  @java.lang.Override
  public long getRetryAfterMs() {
    return retryAfterMs_;
  }

  public static final int ATTEMPTS_LEFT_FIELD_NUMBER = 3;
  private int attemptsLeft_ = 0;
  /**
   * <pre>
   * Wrong PINs left before the next lockout.
   * </pre>
   *
   * <code>int32 attempts_left = 3 [json_name = "attemptsLeft"];</code>
   * @return The attemptsLeft.
   */
  @java.lang.Override
  public int getAttemptsLeft() {
    return attemptsLeft_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (ok_ != false) {
      output.writeBool(1, ok_);
    }
    if (retryAfterMs_ != 0L) {
      output.writeInt64(2, retryAfterMs_);
    }
    if (attemptsLeft_ != 0) {
      output.writeInt32(3, attemptsLeft_);
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;
    if (ok_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, ok_);
    }
    if (retryAfterMs_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, retryAfterMs_);
    }
    if (attemptsLeft_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, attemptsLeft_);
    }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof net.bladewatch.app.grpc.v1.VerifySettingsPinResponse)) {
      return super.equals(obj);
    }
    net.bladewatch.app.grpc.v1.VerifySettingsPinResponse other = (net.bladewatch.app.grpc.v1.VerifySettingsPinResponse) obj;

    if (getOk()
        != other.getOk()) return false;
    if (getRetryAfterMs()
        != other.getRetryAfterMs()) return false;
    if (getAttemptsLeft()
        != other.getAttemptsLeft()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + OK_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getOk());
    hash = (37 * hash) + RETRY_AFTER_MS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getRetryAfterMs());
    hash = (37 * hash) + ATTEMPTS_LEFT_FIELD_NUMBER;
    hash = (53 * hash) + getAttemptsLeft();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static net.bladewatch.app.grpc.v1.VerifySettingsPinResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.bladewatch.app.grpc.v1.VerifySettingsPinResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.bladewatch.app.grpc.v1.VerifySettingsPinResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.bladewatch.app.grpc.v1.VerifySettingsPinResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.bladewatch.app.grpc.v1.VerifySettingsPinResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.bladewatch.app.grpc.v1.VerifySettingsPinResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.bladewatch.app.grpc.v1.VerifySettingsPinResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static net.bladewatch.app.grpc.v1.VerifySettingsPinResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static net.bladewatch.app.grpc.v1.VerifySettingsPinResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static net.bladewatch.app.grpc.v1.VerifySettingsPinResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static net.bladewatch.app.grpc.v1.VerifySettingsPinResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static net.bladewatch.app.grpc.v1.VerifySettingsPinResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(net.bladewatch.app.grpc.v1.VerifySettingsPinResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code bladewatch.v1.VerifySettingsPinResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:bladewatch.v1.VerifySettingsPinResponse)
      net.bladewatch.app.grpc.v1.VerifySettingsPinResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.bladewatch.app.grpc.v1.Settings.internal_static_bladewatch_v1_VerifySettingsPinResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.bladewatch.app.grpc.v1.Settings.internal_static_bladewatch_v1_VerifySettingsPinResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.bladewatch.app.grpc.v1.VerifySettingsPinResponse.class, net.bladewatch.app.grpc.v1.VerifySettingsPinResponse.Builder.class);
    }

    // Construct using net.bladewatch.app.grpc.v1.VerifySettingsPinResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      ok_ = false;
      retryAfterMs_ = 0L;
      attemptsLeft_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return net.bladewatch.app.grpc.v1.Settings.internal_static_bladewatch_v1_VerifySettingsPinResponse_descriptor;
    }

    @java.lang.Override
    public net.bladewatch.app.grpc.v1.VerifySettingsPinResponse getDefaultInstanceForType() {
      return net.bladewatch.app.grpc.v1.VerifySettingsPinResponse.getDefaultInstance();
    }

    @java.lang.Override
    public net.bladewatch.app.grpc.v1.VerifySettingsPinResponse build() {
      net.bladewatch.app.grpc.v1.VerifySettingsPinResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public net.bladewatch.app.grpc.v1.VerifySettingsPinResponse buildPartial() {
      net.bladewatch.app.grpc.v1.VerifySettingsPinResponse result = new net.bladewatch.app.grpc.v1.VerifySettingsPinResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(net.bladewatch.app.grpc.v1.VerifySettingsPinResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.ok_ = ok_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.retryAfterMs_ = retryAfterMs_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.attemptsLeft_ = attemptsLeft_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof net.bladewatch.app.grpc.v1.VerifySettingsPinResponse) {
        return mergeFrom((net.bladewatch.app.grpc.v1.VerifySettingsPinResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(net.bladewatch.app.grpc.v1.VerifySettingsPinResponse other) {
      if (other == net.bladewatch.app.grpc.v1.VerifySettingsPinResponse.getDefaultInstance()) return this;
      if (other.getOk() != false) {
        setOk(other.getOk());
      }
      if (other.getRetryAfterMs() != 0L) {
        setRetryAfterMs(other.getRetryAfterMs());
      }
      if (other.getAttemptsLeft() != 0) {
        setAttemptsLeft(other.getAttemptsLeft());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              ok_ = input.readBool();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              retryAfterMs_ = input.readInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              attemptsLeft_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private boolean ok_ ;
    /**
     * <code>bool ok = 1 [json_name = "ok"];</code>
     * @return The ok.
     */
    @java.lang.Override
    public boolean getOk() {
      return ok_;
    }
    /**
     * <code>bool ok = 1 [json_name = "ok"];</code>
     * @param value The ok to set.
     * @return This builder for chaining.
     */
    public Builder setOk(boolean value) {

      ok_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>bool ok = 1 [json_name = "ok"];</code>
     * @return This builder for chaining.
     */
    public Builder clearOk() {
      bitField0_ = (bitField0_ & ~0x00000001);
      ok_ = false;
      onChanged();
      return this;
    }

    private long retryAfterMs_ ;
    /**
     * <pre>
     * &gt; 0: locked out; ok is false and the PIN given was not checked.
     * </pre>
     *
     * <code>int64 retry_after_ms = 2 [json_name = "retryAfterMs"];</code>
     * @return The retryAfterMs.
     */
    @java.lang.Override
    public long getRetryAfterMs() {
      return retryAfterMs_;
    }
    /**
     * <pre>
     * &gt; 0: locked out; ok is false and the PIN given was not checked.
     * </pre>
     *
     * <code>int64 retry_after_ms = 2 [json_name = "retryAfterMs"];</code>
     * @param value The retryAfterMs to set.
     * @return This builder for chaining.
     */
    public Builder setRetryAfterMs(long value) {

      retryAfterMs_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * &gt; 0: locked out; ok is false and the PIN given was not checked.
     * </pre>
     *
     * <code>int64 retry_after_ms = 2 [json_name = "retryAfterMs"];</code>
     * @return This builder for chaining.
     */
    public Builder clearRetryAfterMs() {
      bitField0_ = (bitField0_ & ~0x00000002);
      retryAfterMs_ = 0L;
      onChanged();
      return this;
    }

    private int attemptsLeft_ ;
    /**
     * <pre>
     * Wrong PINs left before the next lockout.
     * </pre>
     *
     * <code>int32 attempts_left = 3 [json_name = "attemptsLeft"];</code>
     * @return The attemptsLeft.
     */
    @java.lang.Override
    public int getAttemptsLeft() {
      return attemptsLeft_;
    }
    /**
     * <pre>
     * Wrong PINs left before the next lockout.
     * </pre>
     *
     * <code>int32 attempts_left = 3 [json_name = "attemptsLeft"];</code>
     * @param value The attemptsLeft to set.
     * @return This builder for chaining.
     */
    public Builder setAttemptsLeft(int value) {

      attemptsLeft_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Wrong PINs left before the next lockout.
     * </pre>
     *
     * <code>int32 attempts_left = 3 [json_name = "attemptsLeft"];</code>
     * @return This builder for chaining.
     */
    public Builder clearAttemptsLeft() {
      bitField0_ = (bitField0_ & ~0x00000004);
      attemptsLeft_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:bladewatch.v1.VerifySettingsPinResponse)
  }

  // @@protoc_insertion_point(class_scope:bladewatch.v1.VerifySettingsPinResponse)
  private static final net.bladewatch.app.grpc.v1.VerifySettingsPinResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new net.bladewatch.app.grpc.v1.VerifySettingsPinResponse();
  }

  public static net.bladewatch.app.grpc.v1.VerifySettingsPinResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<VerifySettingsPinResponse>
      PARSER = new com.google.protobuf.AbstractParser<VerifySettingsPinResponse>() {
    @java.lang.Override
    public VerifySettingsPinResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<VerifySettingsPinResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<VerifySettingsPinResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public net.bladewatch.app.grpc.v1.VerifySettingsPinResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

